/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './item';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../services/item-service';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import18 from '@angular/core/src/linker/query_list';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/slides/slides.ngfactory';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import28 from '../../node_modules/ionic-angular/components/radio/radio-group.ngfactory';
import * as import29 from 'ionic-angular/config/config';
import * as import30 from '@angular/core/src/linker/element_ref';
import * as import31 from 'ionic-angular/navigation/view-controller';
import * as import32 from 'ionic-angular/components/app/app';
import * as import33 from 'ionic-angular/components/menu/menu-controller';
import * as import34 from 'ionic-angular/components/toolbar/toolbar';
import * as import35 from 'ionic-angular/util/keyboard';
import * as import36 from '@angular/core/src/zone/ng_zone';
import * as import37 from 'ionic-angular/components/tabs/tabs';
import * as import38 from '@angular/core/src/linker/template_ref';
import * as import39 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import40 from 'ionic-angular/gestures/gesture-controller';
import * as import41 from 'ionic-angular/util/form';
import * as import42 from 'ionic-angular/components/icon/icon';
import * as import43 from 'ionic-angular/components/button/button';
import * as import44 from 'ionic-angular/components/menu/menu-toggle';
import * as import45 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import46 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import47 from 'ionic-angular/components/navbar/navbar';
import * as import48 from '@angular/common/src/directives/ng_for';
import * as import49 from 'ionic-angular/components/slides/slides';
import * as import50 from 'ionic-angular/components/typography/typography';
import * as import51 from 'ionic-angular/components/grid/grid';
import * as import52 from 'ionic-angular/components/item/item';
import * as import53 from 'ionic-angular/components/list/list';
import * as import54 from 'ionic-angular/components/radio/radio-group';
import * as import55 from '@angular/forms/src/directives/control_value_accessor';
import * as import56 from 'ionic-angular/components/content/content';
import * as import57 from '@angular/core/src/security';
import * as import58 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import59 from '../../node_modules/ionic-angular/components/checkbox/checkbox.ngfactory';
import * as import60 from 'ionic-angular/components/label/label';
import * as import61 from 'ionic-angular/components/checkbox/checkbox';
import * as import62 from '../../node_modules/ionic-angular/components/radio/radio-button.ngfactory';
import * as import63 from 'ionic-angular/components/radio/radio-button';
export class Wrapper_ItemPage {
  context:import0.ItemPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.ItemPage(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_ItemPage_Host:import2.RenderComponentType = (null as any);
class _View_ItemPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ItemPage_0_4:Wrapper_ItemPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ItemPage_Host0,renderType_ItemPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-item',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ItemPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemPage_0_4 = new Wrapper_ItemPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.ItemService),this.parentInjector.get(import10.AlertController));
    this._appEl_0.initComponent(this._ItemPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ItemPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ItemPage) && (0 === requestNodeIndex))) { return this._ItemPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ItemPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ItemPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ItemPage_Host === (null as any))) { (renderType_ItemPage_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ItemPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ItemPageNgFactory:import12.ComponentFactory<import0.ItemPage> = new import12.ComponentFactory<import0.ItemPage>('page-item',viewFactory_ItemPage_Host0,import0.ItemPage);
const styles_ItemPage:any[] = ([] as any[]);
var renderType_ItemPage:import2.RenderComponentType = (null as any);
class _View_ItemPage0 extends import1.AppView<import0.ItemPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import13.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import14.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import15.Wrapper_Button;
  _MenuToggle_5_5:import16.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import17.Wrapper_ToolbarItem;
  _query_Button_5_0:import18.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import19.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _ToolbarTitle_10_4:import20.Wrapper_ToolbarTitle;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _ToolbarItem_13_3:import17.Wrapper_ToolbarItem;
  _query_Button_13_0:import18.QueryList<any>;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Button_15_4:import15.Wrapper_Button;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import19.Wrapper_Icon;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Content_23_4:import21.Wrapper_Content;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Slides_28_4:import22.Wrapper_Slides;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _TemplateRef_30_5:any;
  _NgFor_30_6:import23.Wrapper_NgFor;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _Typography_35_3:import24.Wrapper_Typography;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _Typography_38_3:import24.Wrapper_Typography;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _el_44:any;
  _Grid_44_3:import25.Wrapper_Grid;
  _text_45:any;
  _el_46:any;
  _Row_46_3:import25.Wrapper_Row;
  _text_47:any;
  _el_48:any;
  _Col_48_3:import25.Wrapper_Col;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Button_50_4:import15.Wrapper_Button;
  _text_51:any;
  _el_52:any;
  _Icon_52_3:import19.Wrapper_Icon;
  _text_53:any;
  _el_54:any;
  _Icon_54_3:import19.Wrapper_Icon;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _text_60:any;
  _el_61:any;
  _Col_61_3:import25.Wrapper_Col;
  _text_62:any;
  _el_63:any;
  /*private*/ _appEl_63:import3.AppElement;
  _Button_63_4:import15.Wrapper_Button;
  _text_64:any;
  _el_65:any;
  _Icon_65_3:import19.Wrapper_Icon;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _el_74:any;
  _List_74_3:import26.Wrapper_List;
  _text_75:any;
  _el_76:any;
  /*private*/ _appEl_76:import3.AppElement;
  _Item_76_4:import27.Wrapper_Item;
  _query_Label_76_0:import18.QueryList<any>;
  _query_Button_76_1:import18.QueryList<any>;
  _query_Icon_76_2:import18.QueryList<any>;
  _text_77:any;
  _text_78:any;
  _anchor_79:any;
  /*private*/ _appEl_79:import3.AppElement;
  _TemplateRef_79_5:any;
  _NgFor_79_6:import23.Wrapper_NgFor;
  _text_80:any;
  _el_81:any;
  /*private*/ _appEl_81:import3.AppElement;
  _Item_81_4:import27.Wrapper_Item;
  _query_Label_81_0:import18.QueryList<any>;
  _query_Button_81_1:import18.QueryList<any>;
  _query_Icon_81_2:import18.QueryList<any>;
  _text_82:any;
  _text_83:any;
  _anchor_84:any;
  /*private*/ _appEl_84:import3.AppElement;
  _TemplateRef_84_5:any;
  _NgFor_84_6:import23.Wrapper_NgFor;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _List_87_3:import26.Wrapper_List;
  _RadioGroup_87_4:import28.Wrapper_RadioGroup;
  __NG_VALUE_ACCESSOR_87_5:any[];
  _query_ListHeader_87_0:import18.QueryList<any>;
  _text_88:any;
  _el_89:any;
  /*private*/ _appEl_89:import3.AppElement;
  _Item_89_4:import27.Wrapper_Item;
  _query_Label_89_0:import18.QueryList<any>;
  _query_Button_89_1:import18.QueryList<any>;
  _query_Icon_89_2:import18.QueryList<any>;
  _text_90:any;
  _text_91:any;
  _anchor_92:any;
  /*private*/ _appEl_92:import3.AppElement;
  _TemplateRef_92_5:any;
  _NgFor_92_6:import23.Wrapper_NgFor;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_29:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ItemPage0,renderType_ItemPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_87_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_87_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_87_5 = [this._RadioGroup_87_4.context]); }
    return this.__NG_VALUE_ACCESSOR_87_5;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import13.Wrapper_Header(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import31.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import14.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import14.Wrapper_Navbar(this.parentInjector.get(import32.App),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import15.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import15.Wrapper_Button('','',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import16.Wrapper_MenuToggle(this.parentInjector.get(import33.MenuController),new import30.ElementRef(this._el_5),this.parentInjector.get(import31.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import34.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import18.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import19.Wrapper_Icon(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_10 = new import3.AppElement(10,3,this,this._el_10);
    var compView_10:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(10),this._appEl_10);
    this._ToolbarTitle_10_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import34.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_10.initComponent(this._ToolbarTitle_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'Item',(null as any));
    compView_10.create(this._ToolbarTitle_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_13,'end','');
    this._ToolbarItem_13_3 = new import17.Wrapper_ToolbarItem(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import34.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_13_0 = new import18.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'ion-button','');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import15.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import15.Wrapper_Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._Button_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_17,'name','md-more');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import19.Wrapper_Icon(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_15.create(this._Button_15_4.context,[([] as any[]).concat([
        this._text_16,
        this._el_17,
        this._text_18
      ]
    )],(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]),
      ([] as any[]).concat([this._el_13]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._el_10,
        this._text_12,
        this._text_20
      ]
      )
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_23 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_23 = new import3.AppElement(23,(null as any),this,this._el_23);
    var compView_23:any = import21.viewFactory_Content0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Content_23_4 = new import21.Wrapper_Content(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import32.App),this.parentInjector.get(import35.Keyboard),this.parentInjector.get(import36.NgZone),this.parentInjector.get(import31.ViewController,(null as any)),this.parentInjector.get(import37.Tabs,(null as any)));
    this._appEl_23.initComponent(this._Content_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','cover');
    this._text_27 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'ion-slides',(null as any));
    this.renderer.setElementAttribute(this._el_28,'pager','');
    this._appEl_28 = new import3.AppElement(28,26,this,this._el_28);
    var compView_28:any = import22.viewFactory_Slides0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Slides_28_4 = new import22.Wrapper_Slides(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_28),this.renderer);
    this._appEl_28.initComponent(this._Slides_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_30 = new import3.AppElement(30,28,this,this._anchor_30);
    this._TemplateRef_30_5 = new import38.TemplateRef_(this._appEl_30,viewFactory_ItemPage1);
    this._NgFor_30_6 = new import23.Wrapper_NgFor(this._appEl_30.vcRef,this._TemplateRef_30_5,this.parentInjector.get(import39.IterableDiffers),this.ref);
    this._text_31 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_28.create(this._Slides_28_4.context,[([] as any[]).concat([
        this._text_29,
        this._appEl_30,
        this._text_31
      ]
    )],(null as any));
    this._text_32 = this.renderer.createText(this._el_26,'\n\n    ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_26,'div',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','overlay');
    this._text_34 = this.renderer.createText(this._el_33,'\n      ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'span',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','pull-left');
    this.renderer.setElementAttribute(this._el_35,'color','light');
    this._Typography_35_3 = new import24.Wrapper_Typography(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_35),this.renderer);
    this._text_36 = this.renderer.createText(this._el_35,'',(null as any));
    this._text_37 = this.renderer.createText(this._el_33,'\n\n      ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_33,'span',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','pull-right price');
    this.renderer.setElementAttribute(this._el_38,'color','light');
    this._Typography_38_3 = new import24.Wrapper_Typography(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_38),this.renderer);
    this._text_39 = this.renderer.createText(this._el_38,'',(null as any));
    this._text_40 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._text_41 = this.renderer.createText(this._el_26,'\n  ',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_44,'no-padding','');
    this._Grid_44_3 = new import25.Wrapper_Grid();
    this._text_45 = this.renderer.createText(this._el_44,'\n    ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_44,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','item-button-group');
    this.renderer.setElementAttribute(this._el_46,'no-padding','');
    this._Row_46_3 = new import25.Wrapper_Row();
    this._text_47 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_48,'no-padding','');
    this._Col_48_3 = new import25.Wrapper_Col();
    this._text_49 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'button',(null as any));
    this.renderer.setElementAttribute(this._el_50,'block','');
    this.renderer.setElementAttribute(this._el_50,'color','gray');
    this.renderer.setElementAttribute(this._el_50,'ion-button','');
    this._appEl_50 = new import3.AppElement(50,48,this,this._el_50);
    var compView_50:any = import15.viewFactory_Button0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Button_50_4 = new import15.Wrapper_Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_50),this.renderer);
    this._appEl_50.initComponent(this._Button_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_52 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_52,'class','text-2x');
    this.renderer.setElementAttribute(this._el_52,'name','ios-star');
    this.renderer.setElementAttribute(this._el_52,'role','img');
    this._Icon_52_3 = new import19.Wrapper_Icon(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_52),this.renderer);
    this._text_53 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','text-2x');
    this.renderer.setElementAttribute(this._el_54,'name','ios-star-outline');
    this.renderer.setElementAttribute(this._el_54,'role','img');
    this._Icon_54_3 = new import19.Wrapper_Icon(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_54),this.renderer);
    this._text_55 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','text-sm');
    this._text_57 = this.renderer.createText(this._el_56,'Adicionar aos favoritos',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_50.create(this._Button_50_4.context,[([] as any[]).concat([
        this._text_51,
        this._el_52,
        this._text_53,
        this._el_54,
        this._text_55,
        this._el_56,
        this._text_58
      ]
    )],(null as any));
    this._text_59 = this.renderer.createText(this._el_48,'\n      ',(null as any));
    this._text_60 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_46,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_61,'no-padding','');
    this._Col_61_3 = new import25.Wrapper_Col();
    this._text_62 = this.renderer.createText(this._el_61,'\n        ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_61,'button',(null as any));
    this.renderer.setElementAttribute(this._el_63,'block','');
    this.renderer.setElementAttribute(this._el_63,'ion-button','');
    this._appEl_63 = new import3.AppElement(63,61,this,this._el_63);
    var compView_63:any = import15.viewFactory_Button0(this.viewUtils,this.injector(63),this._appEl_63);
    this._Button_63_4 = new import15.Wrapper_Button((null as any),'',this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_63),this.renderer);
    this._appEl_63.initComponent(this._Button_63_4.context,([] as any[]),compView_63);
    this._text_64 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_65 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_65,'class','text-2x');
    this.renderer.setElementAttribute(this._el_65,'name','ios-cart-outline');
    this.renderer.setElementAttribute(this._el_65,'role','img');
    this._Icon_65_3 = new import19.Wrapper_Icon(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_65),this.renderer);
    this._text_66 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_67 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_67,'class','text-sm');
    this._text_68 = this.renderer.createText(this._el_67,'Adicionar ao carrinho',(null as any));
    this._text_69 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_63.create(this._Button_63_4.context,[([] as any[]).concat([
        this._text_64,
        this._el_65,
        this._text_66,
        this._el_67,
        this._text_69
      ]
    )],(null as any));
    this._text_70 = this.renderer.createText(this._el_61,'\n      ',(null as any));
    this._text_71 = this.renderer.createText(this._el_46,'\n    ',(null as any));
    this._text_72 = this.renderer.createText(this._el_44,'\n  ',(null as any));
    this._text_73 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_74 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_74,'class','list-full-border');
    this.renderer.setElementAttribute(this._el_74,'no-margin','');
    this._List_74_3 = new import26.Wrapper_List(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_74),this.renderer,this.parentInjector.get(import40.GestureController));
    this._text_75 = this.renderer.createText(this._el_74,'\n    ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_74,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','item');
    this._appEl_76 = new import3.AppElement(76,74,this,this._el_76);
    var compView_76:any = import27.viewFactory_Item0(this.viewUtils,this.injector(76),this._appEl_76);
    this._Item_76_4 = new import27.Wrapper_Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_76),this.renderer);
    this._query_Label_76_0 = new import18.QueryList<any>();
    this._query_Button_76_1 = new import18.QueryList<any>();
    this._query_Icon_76_2 = new import18.QueryList<any>();
    this._appEl_76.initComponent(this._Item_76_4.context,([] as any[]),compView_76);
    this._text_77 = this.renderer.createText((null as any),'Options',(null as any));
    this._query_Label_76_0.reset(([] as any[]));
    this._Item_76_4.context.contentLabel = this._query_Label_76_0.first;
    compView_76.create(this._Item_76_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_77]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_78 = this.renderer.createText(this._el_74,'\n    ',(null as any));
    this._anchor_79 = this.renderer.createTemplateAnchor(this._el_74,(null as any));
    this._appEl_79 = new import3.AppElement(79,74,this,this._anchor_79);
    this._TemplateRef_79_5 = new import38.TemplateRef_(this._appEl_79,viewFactory_ItemPage2);
    this._NgFor_79_6 = new import23.Wrapper_NgFor(this._appEl_79.vcRef,this._TemplateRef_79_5,this.parentInjector.get(import39.IterableDiffers),this.ref);
    this._text_80 = this.renderer.createText(this._el_74,'\n\n    ',(null as any));
    this._el_81 = this.renderer.createElement(this._el_74,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_81,'class','item');
    this._appEl_81 = new import3.AppElement(81,74,this,this._el_81);
    var compView_81:any = import27.viewFactory_Item0(this.viewUtils,this.injector(81),this._appEl_81);
    this._Item_81_4 = new import27.Wrapper_Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_81),this.renderer);
    this._query_Label_81_0 = new import18.QueryList<any>();
    this._query_Button_81_1 = new import18.QueryList<any>();
    this._query_Icon_81_2 = new import18.QueryList<any>();
    this._appEl_81.initComponent(this._Item_81_4.context,([] as any[]),compView_81);
    this._text_82 = this.renderer.createText((null as any),'Extras',(null as any));
    this._query_Label_81_0.reset(([] as any[]));
    this._Item_81_4.context.contentLabel = this._query_Label_81_0.first;
    compView_81.create(this._Item_81_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_82]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_83 = this.renderer.createText(this._el_74,'\n    ',(null as any));
    this._anchor_84 = this.renderer.createTemplateAnchor(this._el_74,(null as any));
    this._appEl_84 = new import3.AppElement(84,74,this,this._anchor_84);
    this._TemplateRef_84_5 = new import38.TemplateRef_(this._appEl_84,viewFactory_ItemPage3);
    this._NgFor_84_6 = new import23.Wrapper_NgFor(this._appEl_84.vcRef,this._TemplateRef_84_5,this.parentInjector.get(import39.IterableDiffers),this.ref);
    this._text_85 = this.renderer.createText(this._el_74,'\n  ',(null as any));
    this._text_86 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_87 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_87,'class','list-full-border');
    this.renderer.setElementAttribute(this._el_87,'no-margin','');
    this.renderer.setElementAttribute(this._el_87,'radio-group','');
    this.renderer.setElementAttribute(this._el_87,'role','radiogroup');
    this._List_87_3 = new import26.Wrapper_List(this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_87),this.renderer,this.parentInjector.get(import40.GestureController));
    this._RadioGroup_87_4 = new import28.Wrapper_RadioGroup(this.renderer,new import30.ElementRef(this._el_87));
    this._query_ListHeader_87_0 = new import18.QueryList<any>();
    this._text_88 = this.renderer.createText(this._el_87,'\n    ',(null as any));
    this._el_89 = this.renderer.createElement(this._el_87,'ion-item-divider',(null as any));
    this.renderer.setElementAttribute(this._el_89,'class','item');
    this._appEl_89 = new import3.AppElement(89,87,this,this._el_89);
    var compView_89:any = import27.viewFactory_Item0(this.viewUtils,this.injector(89),this._appEl_89);
    this._Item_89_4 = new import27.Wrapper_Item(this.parentInjector.get(import41.Form),this.parentInjector.get(import29.Config),new import30.ElementRef(this._el_89),this.renderer);
    this._query_Label_89_0 = new import18.QueryList<any>();
    this._query_Button_89_1 = new import18.QueryList<any>();
    this._query_Icon_89_2 = new import18.QueryList<any>();
    this._appEl_89.initComponent(this._Item_89_4.context,([] as any[]),compView_89);
    this._text_90 = this.renderer.createText((null as any),'Sizes',(null as any));
    this._query_Label_89_0.reset(([] as any[]));
    this._Item_89_4.context.contentLabel = this._query_Label_89_0.first;
    compView_89.create(this._Item_89_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([this._text_90]),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_91 = this.renderer.createText(this._el_87,'\n    ',(null as any));
    this._anchor_92 = this.renderer.createTemplateAnchor(this._el_87,(null as any));
    this._appEl_92 = new import3.AppElement(92,87,this,this._anchor_92);
    this._TemplateRef_92_5 = new import38.TemplateRef_(this._appEl_92,viewFactory_ItemPage4);
    this._NgFor_92_6 = new import23.Wrapper_NgFor(this._appEl_92.vcRef,this._TemplateRef_92_5,this.parentInjector.get(import39.IterableDiffers),this.ref);
    this._text_93 = this.renderer.createText(this._el_87,'\n  ',(null as any));
    this._query_ListHeader_87_0.reset(([] as any[]));
    this._RadioGroup_87_4.context._header = this._query_ListHeader_87_0.first;
    this._text_94 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_23.create(this._Content_23_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._text_25,
        this._el_26,
        this._text_42,
        this._text_43,
        this._el_44,
        this._text_73,
        this._el_74,
        this._text_86,
        this._el_87,
        this._text_94
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_95 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_50,'click',this.eventHandler(this._handle_click_50_0.bind(this)));
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_25 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_63,'click',this.eventHandler(this._handle_click_63_0.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._anchor_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._text_83,
      this._anchor_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._el_89,
      this._text_90,
      this._text_91,
      this._anchor_92,
      this._text_93,
      this._text_94,
      this._text_95
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import43.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import44.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import45.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import46.ToolbarTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarTitle_10_4.context; }
    if (((token === import42.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3.context; }
    if (((token === import43.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_15_4.context; }
    if (((token === import45.ToolbarItem) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ToolbarItem_13_3.context; }
    if (((token === import47.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Navbar_3_4.context; }
    if (((token === import34.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Header_1_3.context; }
    if (((token === import38.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import48.NgFor) && (30 === requestNodeIndex))) { return this._NgFor_30_6.context; }
    if (((token === import49.Slides) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Slides_28_4.context; }
    if (((token === import50.Typography) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Typography_35_3.context; }
    if (((token === import50.Typography) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Typography_38_3.context; }
    if (((token === import42.Icon) && (52 === requestNodeIndex))) { return this._Icon_52_3.context; }
    if (((token === import42.Icon) && (54 === requestNodeIndex))) { return this._Icon_54_3.context; }
    if (((token === import43.Button) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Button_50_4.context; }
    if (((token === import51.Col) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 59)))) { return this._Col_48_3.context; }
    if (((token === import42.Icon) && (65 === requestNodeIndex))) { return this._Icon_65_3.context; }
    if (((token === import43.Button) && ((63 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Button_63_4.context; }
    if (((token === import51.Col) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 70)))) { return this._Col_61_3.context; }
    if (((token === import51.Row) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._Row_46_3.context; }
    if (((token === import51.Grid) && ((44 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._Grid_44_3.context; }
    if (((token === import52.Item) && ((76 <= requestNodeIndex) && (requestNodeIndex <= 77)))) { return this._Item_76_4.context; }
    if (((token === import38.TemplateRef) && (79 === requestNodeIndex))) { return this._TemplateRef_79_5; }
    if (((token === import48.NgFor) && (79 === requestNodeIndex))) { return this._NgFor_79_6.context; }
    if (((token === import52.Item) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 82)))) { return this._Item_81_4.context; }
    if (((token === import38.TemplateRef) && (84 === requestNodeIndex))) { return this._TemplateRef_84_5; }
    if (((token === import48.NgFor) && (84 === requestNodeIndex))) { return this._NgFor_84_6.context; }
    if (((token === import53.List) && ((74 <= requestNodeIndex) && (requestNodeIndex <= 85)))) { return this._List_74_3.context; }
    if (((token === import52.Item) && ((89 <= requestNodeIndex) && (requestNodeIndex <= 90)))) { return this._Item_89_4.context; }
    if (((token === import38.TemplateRef) && (92 === requestNodeIndex))) { return this._TemplateRef_92_5; }
    if (((token === import48.NgFor) && (92 === requestNodeIndex))) { return this._NgFor_92_6.context; }
    if (((token === import53.List) && ((87 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._List_87_3.context; }
    if (((token === import54.RadioGroup) && ((87 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._RadioGroup_87_4.context; }
    if (((token === import55.NG_VALUE_ACCESSOR) && ((87 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._NG_VALUE_ACCESSOR_87_5; }
    if (((token === import56.Content) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._Content_23_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_7_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._ToolbarTitle_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._ToolbarItem_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    if (this._Button_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'md-more';
    this._Icon_17_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    if (this._Content_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    const currVal_11:any = '';
    this._Slides_28_4.check_pager(currVal_11,throwOnChange,false);
    if (this._Slides_28_4.detectChangesInternal(this,this._el_28,throwOnChange)) { this._appEl_28.componentView.markAsCheckOnce(); }
    const currVal_12:any = this.context.item.images;
    this._NgFor_30_6.check_ngForOf(currVal_12,throwOnChange,false);
    this._NgFor_30_6.detectChangesInternal(this,this._anchor_30,throwOnChange);
    const currVal_13:any = 'light';
    this._Typography_35_3.check_color(currVal_13,throwOnChange,false);
    this._Typography_35_3.detectChangesInternal(this,this._el_35,throwOnChange);
    const currVal_15:any = 'light';
    this._Typography_38_3.check_color(currVal_15,throwOnChange,false);
    this._Typography_38_3.detectChangesInternal(this,this._el_38,throwOnChange);
    this._Grid_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    this._Row_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    this._Col_48_3.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_18:any = '';
    this._Button_50_4.check_block(currVal_18,throwOnChange,false);
    const currVal_19:any = 'gray';
    this._Button_50_4.check_color(currVal_19,throwOnChange,false);
    if (this._Button_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    const currVal_21:any = 'ios-star';
    this._Icon_52_3.check_name(currVal_21,throwOnChange,false);
    this._Icon_52_3.detectChangesInternal(this,this._el_52,throwOnChange);
    const currVal_24:any = 'ios-star-outline';
    this._Icon_54_3.check_name(currVal_24,throwOnChange,false);
    this._Icon_54_3.detectChangesInternal(this,this._el_54,throwOnChange);
    this._Col_61_3.detectChangesInternal(this,this._el_61,throwOnChange);
    const currVal_27:any = '';
    this._Button_63_4.check_block(currVal_27,throwOnChange,false);
    if (this._Button_63_4.detectChangesInternal(this,this._el_63,throwOnChange)) { this._appEl_63.componentView.markAsCheckOnce(); }
    const currVal_28:any = 'ios-cart-outline';
    this._Icon_65_3.check_name(currVal_28,throwOnChange,false);
    this._Icon_65_3.detectChangesInternal(this,this._el_65,throwOnChange);
    this._List_74_3.detectChangesInternal(this,this._el_74,throwOnChange);
    if (this._Item_76_4.detectChangesInternal(this,this._el_76,throwOnChange)) { this._appEl_76.componentView.markAsCheckOnce(); }
    const currVal_30:any = this.context.item.options;
    this._NgFor_79_6.check_ngForOf(currVal_30,throwOnChange,false);
    this._NgFor_79_6.detectChangesInternal(this,this._anchor_79,throwOnChange);
    if (this._Item_81_4.detectChangesInternal(this,this._el_81,throwOnChange)) { this._appEl_81.componentView.markAsCheckOnce(); }
    const currVal_31:any = this.context.item.extras;
    this._NgFor_84_6.check_ngForOf(currVal_31,throwOnChange,false);
    this._NgFor_84_6.detectChangesInternal(this,this._anchor_84,throwOnChange);
    this._List_87_3.detectChangesInternal(this,this._el_87,throwOnChange);
    this._RadioGroup_87_4.detectChangesInternal(this,this._el_87,throwOnChange);
    if (this._Item_89_4.detectChangesInternal(this,this._el_89,throwOnChange)) { this._appEl_89.componentView.markAsCheckOnce(); }
    const currVal_32:any = this.context.item.sizes;
    this._NgFor_92_6.check_ngForOf(currVal_32,throwOnChange,false);
    this._NgFor_92_6.detectChangesInternal(this,this._anchor_92,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_13_0.dirty) {
        this._query_Button_13_0.reset([this._Button_15_4.context]);
        this._ToolbarItem_13_3.context._buttons = this._query_Button_13_0;
        this._query_Button_13_0.notifyOnChanges();
      }
      if (this._query_Button_76_1.dirty) {
        this._query_Button_76_1.reset(([] as any[]));
        this._Item_76_4.context._buttons = this._query_Button_76_1;
        this._query_Button_76_1.notifyOnChanges();
      }
      if (this._query_Icon_76_2.dirty) {
        this._query_Icon_76_2.reset(([] as any[]));
        this._Item_76_4.context._icons = this._query_Icon_76_2;
        this._query_Icon_76_2.notifyOnChanges();
      }
      if (this._query_Button_81_1.dirty) {
        this._query_Button_81_1.reset(([] as any[]));
        this._Item_81_4.context._buttons = this._query_Button_81_1;
        this._query_Button_81_1.notifyOnChanges();
      }
      if (this._query_Icon_81_2.dirty) {
        this._query_Icon_81_2.reset(([] as any[]));
        this._Item_81_4.context._icons = this._query_Icon_81_2;
        this._query_Icon_81_2.notifyOnChanges();
      }
      if (this._query_Button_89_1.dirty) {
        this._query_Button_89_1.reset(([] as any[]));
        this._Item_89_4.context._buttons = this._query_Button_89_1;
        this._query_Button_89_1.notifyOnChanges();
      }
      if (this._query_Icon_89_2.dirty) {
        this._query_Icon_89_2.reset(([] as any[]));
        this._Item_89_4.context._icons = this._query_Icon_89_2;
        this._query_Icon_89_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_50_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_63_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_76_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_81_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_89_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RadioGroup_87_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = this._Icon_17_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_17,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_23_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_14:any = import4.interpolate(1,'\n        ',this.context.item.description,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_36,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_16:any = import4.interpolate(1,'\n        $',this.context.item.price,'\n      ');
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_39,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_20:boolean = !this.context.item.faved;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementProperty(this._el_52,'hidden',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_22:any = this._Icon_52_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_52,'hide',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this.context.item.faved;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementProperty(this._el_54,'hidden',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_25:any = this._Icon_54_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_54,'hide',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_29:any = this._Icon_65_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_65,'hide',currVal_29);
      this._expr_29 = currVal_29;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Icon_17_3.context.ngOnDestroy();
    this._Icon_52_3.context.ngOnDestroy();
    this._Icon_54_3.context.ngOnDestroy();
    this._Icon_65_3.context.ngOnDestroy();
    this._Content_23_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_50_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.toggleFav(this.context.item)) !== false);
    return (true && pd_0);
  }
  private _handle_click_63_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.addCart()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ItemPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ItemPage> {
  if ((renderType_ItemPage === (null as any))) { (renderType_ItemPage = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_ItemPage,{})); }
  return new _View_ItemPage0(viewUtils,parentInjector,declarationEl);
}
class _View_ItemPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Slide_0_4:import22.Wrapper_Slide;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ItemPage1,renderType_ItemPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-slide',(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import22.viewFactory_Slide0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Slide_0_4 = new import22.Wrapper_Slide(new import30.ElementRef(this._el_0),(<_View_ItemPage0>this.parent)._Slides_28_4.context);
    this._appEl_0.initComponent(this._Slide_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_2,'alt','');
    this.renderer.setElementAttribute(this._el_2,'class','full-image');
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_0.create(this._Slide_0_4.context,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_3
      ]
    )],(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import49.Slide) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Slide_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Slide_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'src',this.viewUtils.sanitizer.sanitize(import57.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Slide_0_4.context.ngOnDestroy();
  }
}
function viewFactory_ItemPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ItemPage1(viewUtils,parentInjector,declarationEl);
}
class _View_ItemPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import27.Wrapper_Item;
  _ItemContent_0_5:import27.Wrapper_ItemContent;
  _query_Label_0_0:import18.QueryList<any>;
  _query_Button_0_1:import18.QueryList<any>;
  _query_Icon_0_2:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import58.Wrapper_Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Checkbox_5_4:import59.Wrapper_Checkbox;
  __NG_VALUE_ACCESSOR_5_5:any[];
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ItemPage2,renderType_ItemPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_5_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_5_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_5_5 = [this._Checkbox_5_4.context]); }
    return this.__NG_VALUE_ACCESSOR_5_5;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import27.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import27.Wrapper_Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import27.Wrapper_ItemContent();
    this._query_Label_0_0 = new import18.QueryList<any>();
    this._query_Button_0_1 = new import18.QueryList<any>();
    this._query_Icon_0_2 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import58.Wrapper_Label(this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-checkbox',(null as any));
    this.renderer.setElementAttribute(this._el_5,'color','primary');
    this._appEl_5 = new import3.AppElement(5,0,this,this._el_5);
    var compView_5:any = import59.viewFactory_Checkbox0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Checkbox_5_4 = new import59.Wrapper_Checkbox(this.parent.parentInjector.get(import29.Config),this.parent.parentInjector.get(import41.Form),this._Item_0_4.context,new import30.ElementRef(this._el_5),this.renderer);
    this._appEl_5.initComponent(this._Checkbox_5_4.context,([] as any[]),compView_5);
    compView_5.create(this._Checkbox_5_4.context,([] as any[]),(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset([this._Label_2_3.context]);
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([
        this._text_1,
        this._text_4,
        this._text_6
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import60.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3.context; }
    if (((token === import61.Checkbox) && (5 === requestNodeIndex))) { return this._Checkbox_5_4.context; }
    if (((token === import55.NG_VALUE_ACCESSOR) && (5 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_5_5; }
    if (((token === import52.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_0_4.context; }
    if (((token === import52.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Label_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_2:any = 'primary';
    this._Checkbox_5_4.check_color(currVal_2,throwOnChange,false);
    this._Checkbox_5_4.detectChangesInternal(this,this._el_5,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Checkbox_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = this._Checkbox_5_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_5,'checkbox-disabled',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Checkbox_5_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this._appEl_5.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Checkbox_5_4.context._click($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ItemPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ItemPage2(viewUtils,parentInjector,declarationEl);
}
class _View_ItemPage3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import27.Wrapper_Item;
  _ItemContent_0_5:import27.Wrapper_ItemContent;
  _query_Label_0_0:import18.QueryList<any>;
  _query_Button_0_1:import18.QueryList<any>;
  _query_Icon_0_2:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import58.Wrapper_Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Checkbox_5_4:import59.Wrapper_Checkbox;
  __NG_VALUE_ACCESSOR_5_5:any[];
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ItemPage3,renderType_ItemPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_5_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_5_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_5_5 = [this._Checkbox_5_4.context]); }
    return this.__NG_VALUE_ACCESSOR_5_5;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import27.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import27.Wrapper_Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import27.Wrapper_ItemContent();
    this._query_Label_0_0 = new import18.QueryList<any>();
    this._query_Button_0_1 = new import18.QueryList<any>();
    this._query_Icon_0_2 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import58.Wrapper_Label(this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-checkbox',(null as any));
    this.renderer.setElementAttribute(this._el_5,'color','primary');
    this._appEl_5 = new import3.AppElement(5,0,this,this._el_5);
    var compView_5:any = import59.viewFactory_Checkbox0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Checkbox_5_4 = new import59.Wrapper_Checkbox(this.parent.parentInjector.get(import29.Config),this.parent.parentInjector.get(import41.Form),this._Item_0_4.context,new import30.ElementRef(this._el_5),this.renderer);
    this._appEl_5.initComponent(this._Checkbox_5_4.context,([] as any[]),compView_5);
    compView_5.create(this._Checkbox_5_4.context,([] as any[]),(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset([this._Label_2_3.context]);
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([
        this._text_1,
        this._text_4,
        this._text_6
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import60.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3.context; }
    if (((token === import61.Checkbox) && (5 === requestNodeIndex))) { return this._Checkbox_5_4.context; }
    if (((token === import55.NG_VALUE_ACCESSOR) && (5 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_5_5; }
    if (((token === import52.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_0_4.context; }
    if (((token === import52.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Label_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_2:any = 'primary';
    this._Checkbox_5_4.check_color(currVal_2,throwOnChange,false);
    this._Checkbox_5_4.detectChangesInternal(this,this._el_5,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Checkbox_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(2,'',this.context.$implicit.name,': $',this.context.$implicit.price,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = this._Checkbox_5_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_5,'checkbox-disabled',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Checkbox_5_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this._appEl_5.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._Checkbox_5_4.context._click($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ItemPage3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ItemPage3(viewUtils,parentInjector,declarationEl);
}
class _View_ItemPage4 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import27.Wrapper_Item;
  _ItemContent_0_5:import27.Wrapper_ItemContent;
  _query_Label_0_0:import18.QueryList<any>;
  _query_Button_0_1:import18.QueryList<any>;
  _query_Icon_0_2:import18.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Label_2_3:import58.Wrapper_Label;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _RadioButton_5_4:import62.Wrapper_RadioButton;
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_ItemPage4,renderType_ItemPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import27.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import27.Wrapper_Item(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import27.Wrapper_ItemContent();
    this._query_Label_0_0 = new import18.QueryList<any>();
    this._query_Button_0_1 = new import18.QueryList<any>();
    this._query_Icon_0_2 = new import18.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this._Label_2_3 = new import58.Wrapper_Label(this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_2),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-radio',(null as any));
    this._appEl_5 = new import3.AppElement(5,0,this,this._el_5);
    var compView_5:any = import62.viewFactory_RadioButton0(this.viewUtils,this.injector(5),this._appEl_5);
    this._RadioButton_5_4 = new import62.Wrapper_RadioButton(this.parent.parentInjector.get(import41.Form),this.parent.parentInjector.get(import29.Config),new import30.ElementRef(this._el_5),this.renderer,this._Item_0_4.context,(<_View_ItemPage0>this.parent)._RadioGroup_87_4.context);
    this._appEl_5.initComponent(this._RadioButton_5_4.context,([] as any[]),compView_5);
    compView_5.create(this._RadioButton_5_4.context,([] as any[]),(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset([this._Label_2_3.context]);
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([
        this._text_1,
        this._text_4,
        this._text_6
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_5])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import60.Label) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._Label_2_3.context; }
    if (((token === import63.RadioButton) && (5 === requestNodeIndex))) { return this._RadioButton_5_4.context; }
    if (((token === import52.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Item_0_4.context; }
    if (((token === import52.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Label_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._RadioButton_5_4.detectChangesInternal(this,this._el_5,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(2,'',this.context.$implicit.name,': $',this.context.$implicit.price,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_2:any = this._RadioButton_5_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_5,'radio-disabled',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RadioButton_5_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this._appEl_5.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._RadioButton_5_4.context._click($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ItemPage4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_ItemPage4(viewUtils,parentInjector,declarationEl);
}