/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from 'ionic-angular/module';
import * as import9 from 'angularfire2/angularfire2';
import * as import10 from '@angular/common/src/localization';
import * as import11 from 'ionic-angular/components/app/app';
import * as import12 from '@angular/core/src/application_init';
import * as import13 from '@angular/core/src/testability/testability';
import * as import14 from '@angular/core/src/application_ref';
import * as import15 from '@angular/core/src/linker/compiler';
import * as import16 from 'ionic-angular/gestures/gesture-config';
import * as import17 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import18 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import19 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import20 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import21 from '@angular/core/src/linker/view_utils';
import * as import22 from '@angular/platform-browser/src/browser/title';
import * as import23 from '@angular/http/src/backends/browser_xhr';
import * as import24 from '@angular/http/src/base_response_options';
import * as import25 from '@angular/http/src/backends/xhr_backend';
import * as import26 from '@angular/http/src/base_request_options';
import * as import27 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import28 from '@angular/forms/src/form_builder';
import * as import29 from 'angularfire2/auth/auth';
import * as import30 from 'angularfire2/database/database';
import * as import31 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import32 from 'ionic-angular/components/alert/alert';
import * as import33 from 'ionic-angular/util/events';
import * as import34 from 'ionic-angular/util/form';
import * as import35 from 'ionic-angular/util/haptic';
import * as import36 from 'ionic-angular/gestures/gesture-controller';
import * as import37 from 'ionic-angular/util/keyboard';
import * as import38 from 'ionic-angular/components/loading/loading';
import * as import39 from '@angular/common/src/location/location';
import * as import40 from 'ionic-angular/components/menu/menu-controller';
import * as import41 from 'ionic-angular/components/modal/modal';
import * as import42 from 'ionic-angular/components/picker/picker';
import * as import43 from 'ionic-angular/components/popover/popover';
import * as import44 from 'ionic-angular/components/tap-click/tap-click';
import * as import45 from 'ionic-angular/components/toast/toast';
import * as import46 from 'ionic-angular/translation/translate';
import * as import47 from 'ionic-angular/transitions/transition-controller';
import * as import48 from '../services/menu-service';
import * as import49 from '../services/category-service';
import * as import50 from '../services/item-service';
import * as import51 from '../services/cart-service';
import * as import52 from '../services/post-service';
import * as import53 from '../services/chat-service';
import * as import54 from '../services/user-service';
import * as import55 from '../services/fire-service';
import * as import56 from '@angular/core/src/di/injector';
import * as import57 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import58 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as import59 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as import60 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as import61 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as import62 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as import63 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as import64 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as import65 from './app.component.ngfactory';
import * as import66 from '../pages/about/about.ngfactory';
import * as import67 from '../pages/address/address.ngfactory';
import * as import68 from '../pages/cart/cart.ngfactory';
import * as import69 from '../pages/categories/categories.ngfactory';
import * as import70 from '../pages/category/category.ngfactory';
import * as import71 from '../pages/chat-detail/chat-detail.ngfactory';
import * as import72 from '../pages/chats/chats.ngfactory';
import * as import73 from '../pages/checkout/checkout.ngfactory';
import * as import74 from '../pages/favorite/favorite.ngfactory';
import * as import75 from '../pages/home/home.ngfactory';
import * as import76 from '../pages/item/item.ngfactory';
import * as import77 from '../pages/login/login.ngfactory';
import * as import78 from '../pages/news/news.ngfactory';
import * as import79 from '../pages/offer/offer.ngfactory';
import * as import80 from '../pages/register/register.ngfactory';
import * as import81 from '../pages/setting/setting.ngfactory';
import * as import82 from '../pages/user/user.ngfactory';
import * as import83 from '@angular/core/src/application_tokens';
import * as import84 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import85 from '@angular/platform-browser/src/dom/events/key_events';
import * as import86 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import87 from '@angular/core/src/zone/ng_zone';
import * as import88 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import89 from './app.component';
import * as import90 from '@angular/common/src/location/platform_location';
import * as import91 from '@angular/common/src/location/location_strategy';
import * as import92 from 'ionic-angular/navigation/url-serializer';
import * as import93 from 'ionic-angular/navigation/deep-linker';
import * as import94 from 'ionic-angular/platform/query-params';
import * as import95 from 'ionic-angular/platform/platform-registry';
import * as import96 from 'ionic-angular/platform/platform';
import * as import97 from 'ionic-angular/config/config';
import * as import98 from 'ionic-angular/config/mode-registry';
import * as import99 from 'ionic-angular/transitions/transition-registry';
import * as import100 from '@angular/core/src/console';
import * as import101 from '@angular/core/src/i18n/tokens';
import * as import102 from '@angular/core/src/error_handler';
import * as import103 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import104 from '@angular/platform-browser/src/dom/animation_driver';
import * as import105 from '@angular/core/src/render/api';
import * as import106 from '@angular/core/src/security';
import * as import107 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import108 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import109 from '@angular/http/src/interfaces';
import * as import110 from '@angular/http/src/http';
import * as import111 from 'angularfire2/tokens';
import * as import112 from 'angularfire2/auth/auth_backend';
import * as import113 from 'ionic-angular/components/app/app-root';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _ReactiveFormsModule_6:import7.ReactiveFormsModule;
  _IonicModule_7:import8.IonicModule;
  _AngularFireModule_8:import9.AngularFireModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import10.NgLocaleLocalization;
  _ErrorHandler_12:any;
  _ConfigToken_13:any;
  _UrlToken_14:any;
  _QueryParams_15:any;
  _PlatformConfigToken_16:any;
  _UserAgentToken_17:any;
  _NavigatorPlatformToken_18:any;
  _DocumentDirToken_19:any;
  _DocLangToken_20:any;
  _Platform_21:any;
  _Config_22:any;
  _App_23:import11.App;
  _APP_INITIALIZER_24:any[];
  _ApplicationInitStatus_25:import12.ApplicationInitStatus;
  _Testability_26:import13.Testability;
  _ApplicationRef__27:import14.ApplicationRef_;
  __ApplicationRef_28:any;
  __Compiler_29:import15.Compiler;
  __APP_ID_30:any;
  __DOCUMENT_31:any;
  __HAMMER_GESTURE_CONFIG_32:import16.IonicGestureConfig;
  __EVENT_MANAGER_PLUGINS_33:any[];
  __EventManager_34:import17.EventManager;
  __DomSharedStylesHost_35:import18.DomSharedStylesHost;
  __AnimationDriver_36:any;
  __DomRootRenderer_37:import19.DomRootRenderer_;
  __RootRenderer_38:any;
  __DomSanitizer_39:import20.DomSanitizerImpl;
  __Sanitizer_40:any;
  __ViewUtils_41:import21.ViewUtils;
  __IterableDiffers_42:any;
  __KeyValueDiffers_43:any;
  __SharedStylesHost_44:any;
  __Title_45:import22.Title;
  __BrowserXhr_46:import23.BrowserXhr;
  __ResponseOptions_47:import24.BaseResponseOptions;
  __XSRFStrategy_48:any;
  __XHRBackend_49:import25.XHRBackend;
  __RequestOptions_50:import26.BaseRequestOptions;
  __Http_51:any;
  __RadioControlRegistry_52:import27.RadioControlRegistry;
  __FormBuilder_53:import28.FormBuilder;
  __FirebaseUserConfig_54:any;
  __FirebaseConfig_55:any;
  __FirebaseApp_56:any;
  __AuthBackend_57:any;
  __WindowLocation_58:any;
  __FirebaseAuthConfig_59:any;
  __AngularFireAuth_60:import29.AngularFireAuth;
  __FirebaseAuth_61:any;
  __AngularFireDatabase_62:import30.AngularFireDatabase;
  __AngularFire_63:import9.AngularFire;
  __AppRootToken_64:any;
  __DeepLinkConfigToken_65:any;
  __ActionSheetController_66:import31.ActionSheetController;
  __AlertController_67:import32.AlertController;
  __Events_68:import33.Events;
  __Form_69:import34.Form;
  __Haptic_70:import35.Haptic;
  __GestureController_71:import36.GestureController;
  __Keyboard_72:import37.Keyboard;
  __LoadingController_73:import38.LoadingController;
  __LocationStrategy_74:any;
  __Location_75:import39.Location;
  __MenuController_76:import40.MenuController;
  __ModalController_77:import41.ModalController;
  __PickerController_78:import42.PickerController;
  __PopoverController_79:import43.PopoverController;
  __TapClick_80:import44.TapClick;
  __ToastController_81:import45.ToastController;
  __Translate_82:import46.Translate;
  __TransitionController_83:import47.TransitionController;
  __UrlSerializer_84:any;
  __DeepLinker_85:any;
  __MenuService_86:import48.MenuService;
  __CategoryService_87:import49.CategoryService;
  __ItemService_88:import50.ItemService;
  __CartService_89:import51.CartService;
  __PostService_90:import52.PostService;
  __ChatService_91:import53.ChatService;
  __UserService_92:import54.UserService;
  __FireService_93:import55.FireService;
  constructor(parent:import56.Injector) {
    super(parent,[
      import57.ActionSheetCmpNgFactory,
      import58.AlertCmpNgFactory,
      import59.IonicAppNgFactory,
      import60.LoadingCmpNgFactory,
      import61.ModalCmpNgFactory,
      import62.PickerCmpNgFactory,
      import63.PopoverCmpNgFactory,
      import64.ToastCmpNgFactory,
      import65.MyAppNgFactory,
      import65.MyAppNgFactory,
      import66.AboutPageNgFactory,
      import67.AddressPageNgFactory,
      import68.CartPageNgFactory,
      import69.CategoriesPageNgFactory,
      import70.CategoryPageNgFactory,
      import71.ChatDetailPageNgFactory,
      import72.ChatsPageNgFactory,
      import73.CheckoutPageNgFactory,
      import74.FavoritePageNgFactory,
      import75.HomePageNgFactory,
      import76.ItemPageNgFactory,
      import77.LoginPageNgFactory,
      import78.NewsPageNgFactory,
      import79.OfferPageNgFactory,
      import80.RegisterPageNgFactory,
      import81.SettingPageNgFactory,
      import82.UserPageNgFactory,
      import59.IonicAppNgFactory
    ]
    ,[import59.IonicAppNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == (null as any))) { (this.__LOCALE_ID_10 = 'en-US'); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import10.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_28():any {
    if ((this.__ApplicationRef_28 == (null as any))) { (this.__ApplicationRef_28 = this._ApplicationRef__27); }
    return this.__ApplicationRef_28;
  }
  get _Compiler_29():import15.Compiler {
    if ((this.__Compiler_29 == (null as any))) { (this.__Compiler_29 = new import15.Compiler()); }
    return this.__Compiler_29;
  }
  get _APP_ID_30():any {
    if ((this.__APP_ID_30 == (null as any))) { (this.__APP_ID_30 = import83._appIdRandomProviderFactory()); }
    return this.__APP_ID_30;
  }
  get _DOCUMENT_31():any {
    if ((this.__DOCUMENT_31 == (null as any))) { (this.__DOCUMENT_31 = import4._document()); }
    return this.__DOCUMENT_31;
  }
  get _HAMMER_GESTURE_CONFIG_32():import16.IonicGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_32 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_32 = new import16.IonicGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_32;
  }
  get _EVENT_MANAGER_PLUGINS_33():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_33 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_33 = [
      new import84.DomEventsPlugin(),
      new import85.KeyEventsPlugin(),
      new import86.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_32)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_33;
  }
  get _EventManager_34():import17.EventManager {
    if ((this.__EventManager_34 == (null as any))) { (this.__EventManager_34 = new import17.EventManager(this._EVENT_MANAGER_PLUGINS_33,this.parent.get(import87.NgZone))); }
    return this.__EventManager_34;
  }
  get _DomSharedStylesHost_35():import18.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_35 == (null as any))) { (this.__DomSharedStylesHost_35 = new import18.DomSharedStylesHost(this._DOCUMENT_31)); }
    return this.__DomSharedStylesHost_35;
  }
  get _AnimationDriver_36():any {
    if ((this.__AnimationDriver_36 == (null as any))) { (this.__AnimationDriver_36 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_36;
  }
  get _DomRootRenderer_37():import19.DomRootRenderer_ {
    if ((this.__DomRootRenderer_37 == (null as any))) { (this.__DomRootRenderer_37 = new import19.DomRootRenderer_(this._DOCUMENT_31,this._EventManager_34,this._DomSharedStylesHost_35,this._AnimationDriver_36)); }
    return this.__DomRootRenderer_37;
  }
  get _RootRenderer_38():any {
    if ((this.__RootRenderer_38 == (null as any))) { (this.__RootRenderer_38 = import88._createConditionalRootRenderer(this._DomRootRenderer_37,this.parent.get(import88.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_38;
  }
  get _DomSanitizer_39():import20.DomSanitizerImpl {
    if ((this.__DomSanitizer_39 == (null as any))) { (this.__DomSanitizer_39 = new import20.DomSanitizerImpl()); }
    return this.__DomSanitizer_39;
  }
  get _Sanitizer_40():any {
    if ((this.__Sanitizer_40 == (null as any))) { (this.__Sanitizer_40 = this._DomSanitizer_39); }
    return this.__Sanitizer_40;
  }
  get _ViewUtils_41():import21.ViewUtils {
    if ((this.__ViewUtils_41 == (null as any))) { (this.__ViewUtils_41 = new import21.ViewUtils(this._RootRenderer_38,this._APP_ID_30,this._Sanitizer_40)); }
    return this.__ViewUtils_41;
  }
  get _IterableDiffers_42():any {
    if ((this.__IterableDiffers_42 == (null as any))) { (this.__IterableDiffers_42 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_42;
  }
  get _KeyValueDiffers_43():any {
    if ((this.__KeyValueDiffers_43 == (null as any))) { (this.__KeyValueDiffers_43 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_43;
  }
  get _SharedStylesHost_44():any {
    if ((this.__SharedStylesHost_44 == (null as any))) { (this.__SharedStylesHost_44 = this._DomSharedStylesHost_35); }
    return this.__SharedStylesHost_44;
  }
  get _Title_45():import22.Title {
    if ((this.__Title_45 == (null as any))) { (this.__Title_45 = new import22.Title()); }
    return this.__Title_45;
  }
  get _BrowserXhr_46():import23.BrowserXhr {
    if ((this.__BrowserXhr_46 == (null as any))) { (this.__BrowserXhr_46 = new import23.BrowserXhr()); }
    return this.__BrowserXhr_46;
  }
  get _ResponseOptions_47():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_47 == (null as any))) { (this.__ResponseOptions_47 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_47;
  }
  get _XSRFStrategy_48():any {
    if ((this.__XSRFStrategy_48 == (null as any))) { (this.__XSRFStrategy_48 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_48;
  }
  get _XHRBackend_49():import25.XHRBackend {
    if ((this.__XHRBackend_49 == (null as any))) { (this.__XHRBackend_49 = new import25.XHRBackend(this._BrowserXhr_46,this._ResponseOptions_47,this._XSRFStrategy_48)); }
    return this.__XHRBackend_49;
  }
  get _RequestOptions_50():import26.BaseRequestOptions {
    if ((this.__RequestOptions_50 == (null as any))) { (this.__RequestOptions_50 = new import26.BaseRequestOptions()); }
    return this.__RequestOptions_50;
  }
  get _Http_51():any {
    if ((this.__Http_51 == (null as any))) { (this.__Http_51 = import5.httpFactory(this._XHRBackend_49,this._RequestOptions_50)); }
    return this.__Http_51;
  }
  get _RadioControlRegistry_52():import27.RadioControlRegistry {
    if ((this.__RadioControlRegistry_52 == (null as any))) { (this.__RadioControlRegistry_52 = new import27.RadioControlRegistry()); }
    return this.__RadioControlRegistry_52;
  }
  get _FormBuilder_53():import28.FormBuilder {
    if ((this.__FormBuilder_53 == (null as any))) { (this.__FormBuilder_53 = new import28.FormBuilder()); }
    return this.__FormBuilder_53;
  }
  get _FirebaseUserConfig_54():any {
    if ((this.__FirebaseUserConfig_54 == (null as any))) { (this.__FirebaseUserConfig_54 = {
      apiKey: 'AIzaSyANDjWZuEIbS9RZ38BLiNKpdCjO-co0XDc',
      authDomain: 'appfood-150302.firebaseapp.com',
      databaseURL: 'https://appfood-150302.firebaseio.com',
      storageBucket: 'appfood-150302.appspot.com',
      messagingSenderId: '157769908167'
    }
    ); }
    return this.__FirebaseUserConfig_54;
  }
  get _FirebaseConfig_55():any {
    if ((this.__FirebaseConfig_55 == (null as any))) { (this.__FirebaseConfig_55 = import9._getDefaultFirebase(this._FirebaseUserConfig_54)); }
    return this.__FirebaseConfig_55;
  }
  get _FirebaseApp_56():any {
    if ((this.__FirebaseApp_56 == (null as any))) { (this.__FirebaseApp_56 = import9._getFirebase(this._FirebaseConfig_55)); }
    return this.__FirebaseApp_56;
  }
  get _AuthBackend_57():any {
    if ((this.__AuthBackend_57 == (null as any))) { (this.__AuthBackend_57 = import9._getAuthBackend(this._FirebaseApp_56)); }
    return this.__AuthBackend_57;
  }
  get _WindowLocation_58():any {
    if ((this.__WindowLocation_58 == (null as any))) { (this.__WindowLocation_58 = import9._getWindowLocation()); }
    return this.__WindowLocation_58;
  }
  get _FirebaseAuthConfig_59():any {
    if ((this.__FirebaseAuthConfig_59 == (null as any))) { (this.__FirebaseAuthConfig_59 = (null as any)); }
    return this.__FirebaseAuthConfig_59;
  }
  get _AngularFireAuth_60():import29.AngularFireAuth {
    if ((this.__AngularFireAuth_60 == (null as any))) { (this.__AngularFireAuth_60 = new import29.AngularFireAuth(this._AuthBackend_57,this._WindowLocation_58,this._FirebaseAuthConfig_59)); }
    return this.__AngularFireAuth_60;
  }
  get _FirebaseAuth_61():any {
    if ((this.__FirebaseAuth_61 == (null as any))) { (this.__FirebaseAuth_61 = this._AngularFireAuth_60); }
    return this.__FirebaseAuth_61;
  }
  get _AngularFireDatabase_62():import30.AngularFireDatabase {
    if ((this.__AngularFireDatabase_62 == (null as any))) { (this.__AngularFireDatabase_62 = new import30.AngularFireDatabase(this._FirebaseConfig_55,this._FirebaseApp_56)); }
    return this.__AngularFireDatabase_62;
  }
  get _AngularFire_63():import9.AngularFire {
    if ((this.__AngularFire_63 == (null as any))) { (this.__AngularFire_63 = new import9.AngularFire(this._FirebaseConfig_55,this._AngularFireAuth_60,this._AngularFireDatabase_62)); }
    return this.__AngularFire_63;
  }
  get _AppRootToken_64():any {
    if ((this.__AppRootToken_64 == (null as any))) { (this.__AppRootToken_64 = import89.MyApp); }
    return this.__AppRootToken_64;
  }
  get _DeepLinkConfigToken_65():any {
    if ((this.__DeepLinkConfigToken_65 == (null as any))) { (this.__DeepLinkConfigToken_65 = (null as any)); }
    return this.__DeepLinkConfigToken_65;
  }
  get _ActionSheetController_66():import31.ActionSheetController {
    if ((this.__ActionSheetController_66 == (null as any))) { (this.__ActionSheetController_66 = new import31.ActionSheetController(this._App_23)); }
    return this.__ActionSheetController_66;
  }
  get _AlertController_67():import32.AlertController {
    if ((this.__AlertController_67 == (null as any))) { (this.__AlertController_67 = new import32.AlertController(this._App_23)); }
    return this.__AlertController_67;
  }
  get _Events_68():import33.Events {
    if ((this.__Events_68 == (null as any))) { (this.__Events_68 = new import33.Events()); }
    return this.__Events_68;
  }
  get _Form_69():import34.Form {
    if ((this.__Form_69 == (null as any))) { (this.__Form_69 = new import34.Form()); }
    return this.__Form_69;
  }
  get _Haptic_70():import35.Haptic {
    if ((this.__Haptic_70 == (null as any))) { (this.__Haptic_70 = new import35.Haptic(this._Platform_21)); }
    return this.__Haptic_70;
  }
  get _GestureController_71():import36.GestureController {
    if ((this.__GestureController_71 == (null as any))) { (this.__GestureController_71 = new import36.GestureController(this._App_23)); }
    return this.__GestureController_71;
  }
  get _Keyboard_72():import37.Keyboard {
    if ((this.__Keyboard_72 == (null as any))) { (this.__Keyboard_72 = new import37.Keyboard(this._Config_22,this._Form_69,this.parent.get(import87.NgZone))); }
    return this.__Keyboard_72;
  }
  get _LoadingController_73():import38.LoadingController {
    if ((this.__LoadingController_73 == (null as any))) { (this.__LoadingController_73 = new import38.LoadingController(this._App_23)); }
    return this.__LoadingController_73;
  }
  get _LocationStrategy_74():any {
    if ((this.__LocationStrategy_74 == (null as any))) { (this.__LocationStrategy_74 = import8.provideLocationStrategy(this.parent.get(import90.PlatformLocation),this.parent.get(import91.APP_BASE_HREF,(null as any)),this._Config_22)); }
    return this.__LocationStrategy_74;
  }
  get _Location_75():import39.Location {
    if ((this.__Location_75 == (null as any))) { (this.__Location_75 = new import39.Location(this._LocationStrategy_74)); }
    return this.__Location_75;
  }
  get _MenuController_76():import40.MenuController {
    if ((this.__MenuController_76 == (null as any))) { (this.__MenuController_76 = new import40.MenuController()); }
    return this.__MenuController_76;
  }
  get _ModalController_77():import41.ModalController {
    if ((this.__ModalController_77 == (null as any))) { (this.__ModalController_77 = new import41.ModalController(this._App_23)); }
    return this.__ModalController_77;
  }
  get _PickerController_78():import42.PickerController {
    if ((this.__PickerController_78 == (null as any))) { (this.__PickerController_78 = new import42.PickerController(this._App_23)); }
    return this.__PickerController_78;
  }
  get _PopoverController_79():import43.PopoverController {
    if ((this.__PopoverController_79 == (null as any))) { (this.__PopoverController_79 = new import43.PopoverController(this._App_23)); }
    return this.__PopoverController_79;
  }
  get _TapClick_80():import44.TapClick {
    if ((this.__TapClick_80 == (null as any))) { (this.__TapClick_80 = new import44.TapClick(this._Config_22,this._App_23,this.parent.get(import87.NgZone))); }
    return this.__TapClick_80;
  }
  get _ToastController_81():import45.ToastController {
    if ((this.__ToastController_81 == (null as any))) { (this.__ToastController_81 = new import45.ToastController(this._App_23)); }
    return this.__ToastController_81;
  }
  get _Translate_82():import46.Translate {
    if ((this.__Translate_82 == (null as any))) { (this.__Translate_82 = new import46.Translate()); }
    return this.__Translate_82;
  }
  get _TransitionController_83():import47.TransitionController {
    if ((this.__TransitionController_83 == (null as any))) { (this.__TransitionController_83 = new import47.TransitionController(this._Config_22)); }
    return this.__TransitionController_83;
  }
  get _UrlSerializer_84():any {
    if ((this.__UrlSerializer_84 == (null as any))) { (this.__UrlSerializer_84 = import92.setupUrlSerializer(this._DeepLinkConfigToken_65)); }
    return this.__UrlSerializer_84;
  }
  get _DeepLinker_85():any {
    if ((this.__DeepLinker_85 == (null as any))) { (this.__DeepLinker_85 = import93.setupDeepLinker(this._App_23,this._UrlSerializer_84,this._Location_75)); }
    return this.__DeepLinker_85;
  }
  get _MenuService_86():import48.MenuService {
    if ((this.__MenuService_86 == (null as any))) { (this.__MenuService_86 = new import48.MenuService()); }
    return this.__MenuService_86;
  }
  get _CategoryService_87():import49.CategoryService {
    if ((this.__CategoryService_87 == (null as any))) { (this.__CategoryService_87 = new import49.CategoryService()); }
    return this.__CategoryService_87;
  }
  get _ItemService_88():import50.ItemService {
    if ((this.__ItemService_88 == (null as any))) { (this.__ItemService_88 = new import50.ItemService()); }
    return this.__ItemService_88;
  }
  get _CartService_89():import51.CartService {
    if ((this.__CartService_89 == (null as any))) { (this.__CartService_89 = new import51.CartService()); }
    return this.__CartService_89;
  }
  get _PostService_90():import52.PostService {
    if ((this.__PostService_90 == (null as any))) { (this.__PostService_90 = new import52.PostService()); }
    return this.__PostService_90;
  }
  get _ChatService_91():import53.ChatService {
    if ((this.__ChatService_91 == (null as any))) { (this.__ChatService_91 = new import53.ChatService()); }
    return this.__ChatService_91;
  }
  get _UserService_92():import54.UserService {
    if ((this.__UserService_92 == (null as any))) { (this.__UserService_92 = new import54.UserService(this._Events_68)); }
    return this.__UserService_92;
  }
  get _FireService_93():import55.FireService {
    if ((this.__FireService_93 == (null as any))) { (this.__FireService_93 = new import55.FireService(this._Events_68,this._AngularFire_63,this._UserService_92)); }
    return this.__FireService_93;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._ReactiveFormsModule_6 = new import7.ReactiveFormsModule();
    this._IonicModule_7 = new import8.IonicModule();
    this._AngularFireModule_8 = new import9.AngularFireModule();
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = import4.errorHandler();
    this._ConfigToken_13 = (null as any);
    this._UrlToken_14 = import8.provideLocationHref();
    this._QueryParams_15 = import94.setupQueryParams(this._UrlToken_14);
    this._PlatformConfigToken_16 = import95.providePlatformConfigs();
    this._UserAgentToken_17 = import8.provideUserAgent();
    this._NavigatorPlatformToken_18 = import8.provideNavigatorPlatform();
    this._DocumentDirToken_19 = import8.provideDocumentDirection();
    this._DocLangToken_20 = import8.provideDocumentLang();
    this._Platform_21 = import96.setupPlatform(this._PlatformConfigToken_16,this._QueryParams_15,this._UserAgentToken_17,this._NavigatorPlatformToken_18,this._DocumentDirToken_19,this._DocLangToken_20,this.parent.get(import87.NgZone));
    this._Config_22 = import97.setupConfig(this._ConfigToken_13,this._QueryParams_15,this._Platform_21);
    this._App_23 = new import11.App(this._Config_22,this._Platform_21);
    this._APP_INITIALIZER_24 = [
      import98.registerModeConfigs(this._Config_22),
      import99.registerTransitions(this._Config_22),
      import33.setupProvideEvents(this._Platform_21),
      import44.setupTapClick(this._Config_22,this._App_23,this.parent.get(import87.NgZone))
    ]
    ;
    this._ApplicationInitStatus_25 = new import12.ApplicationInitStatus(this._APP_INITIALIZER_24);
    this._Testability_26 = new import13.Testability(this.parent.get(import87.NgZone));
    this._ApplicationRef__27 = new import14.ApplicationRef_(this.parent.get(import87.NgZone),this.parent.get(import100.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_25,this.parent.get(import13.TestabilityRegistry,(null as any)),this._Testability_26);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import8.IonicModule)) { return this._IonicModule_7; }
    if ((token === import9.AngularFireModule)) { return this._AngularFireModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import101.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import102.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import97.ConfigToken)) { return this._ConfigToken_13; }
    if ((token === import94.UrlToken)) { return this._UrlToken_14; }
    if ((token === import94.QueryParams)) { return this._QueryParams_15; }
    if ((token === import95.PlatformConfigToken)) { return this._PlatformConfigToken_16; }
    if ((token === import96.UserAgentToken)) { return this._UserAgentToken_17; }
    if ((token === import96.NavigatorPlatformToken)) { return this._NavigatorPlatformToken_18; }
    if ((token === import96.DocumentDirToken)) { return this._DocumentDirToken_19; }
    if ((token === import96.DocLangToken)) { return this._DocLangToken_20; }
    if ((token === import96.Platform)) { return this._Platform_21; }
    if ((token === import97.Config)) { return this._Config_22; }
    if ((token === import11.App)) { return this._App_23; }
    if ((token === import12.APP_INITIALIZER)) { return this._APP_INITIALIZER_24; }
    if ((token === import12.ApplicationInitStatus)) { return this._ApplicationInitStatus_25; }
    if ((token === import13.Testability)) { return this._Testability_26; }
    if ((token === import14.ApplicationRef_)) { return this._ApplicationRef__27; }
    if ((token === import14.ApplicationRef)) { return this._ApplicationRef_28; }
    if ((token === import15.Compiler)) { return this._Compiler_29; }
    if ((token === import83.APP_ID)) { return this._APP_ID_30; }
    if ((token === import103.DOCUMENT)) { return this._DOCUMENT_31; }
    if ((token === import86.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_32; }
    if ((token === import17.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_33; }
    if ((token === import17.EventManager)) { return this._EventManager_34; }
    if ((token === import18.DomSharedStylesHost)) { return this._DomSharedStylesHost_35; }
    if ((token === import104.AnimationDriver)) { return this._AnimationDriver_36; }
    if ((token === import19.DomRootRenderer)) { return this._DomRootRenderer_37; }
    if ((token === import105.RootRenderer)) { return this._RootRenderer_38; }
    if ((token === import20.DomSanitizer)) { return this._DomSanitizer_39; }
    if ((token === import106.Sanitizer)) { return this._Sanitizer_40; }
    if ((token === import21.ViewUtils)) { return this._ViewUtils_41; }
    if ((token === import107.IterableDiffers)) { return this._IterableDiffers_42; }
    if ((token === import108.KeyValueDiffers)) { return this._KeyValueDiffers_43; }
    if ((token === import18.SharedStylesHost)) { return this._SharedStylesHost_44; }
    if ((token === import22.Title)) { return this._Title_45; }
    if ((token === import23.BrowserXhr)) { return this._BrowserXhr_46; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_47; }
    if ((token === import109.XSRFStrategy)) { return this._XSRFStrategy_48; }
    if ((token === import25.XHRBackend)) { return this._XHRBackend_49; }
    if ((token === import26.RequestOptions)) { return this._RequestOptions_50; }
    if ((token === import110.Http)) { return this._Http_51; }
    if ((token === import27.RadioControlRegistry)) { return this._RadioControlRegistry_52; }
    if ((token === import28.FormBuilder)) { return this._FormBuilder_53; }
    if ((token === import111.FirebaseUserConfig)) { return this._FirebaseUserConfig_54; }
    if ((token === import111.FirebaseConfig)) { return this._FirebaseConfig_55; }
    if ((token === import111.FirebaseApp)) { return this._FirebaseApp_56; }
    if ((token === import112.AuthBackend)) { return this._AuthBackend_57; }
    if ((token === import111.WindowLocation)) { return this._WindowLocation_58; }
    if ((token === import111.FirebaseAuthConfig)) { return this._FirebaseAuthConfig_59; }
    if ((token === import29.AngularFireAuth)) { return this._AngularFireAuth_60; }
    if ((token === import29.FirebaseAuth)) { return this._FirebaseAuth_61; }
    if ((token === import30.AngularFireDatabase)) { return this._AngularFireDatabase_62; }
    if ((token === import9.AngularFire)) { return this._AngularFire_63; }
    if ((token === import113.AppRootToken)) { return this._AppRootToken_64; }
    if ((token === import92.DeepLinkConfigToken)) { return this._DeepLinkConfigToken_65; }
    if ((token === import31.ActionSheetController)) { return this._ActionSheetController_66; }
    if ((token === import32.AlertController)) { return this._AlertController_67; }
    if ((token === import33.Events)) { return this._Events_68; }
    if ((token === import34.Form)) { return this._Form_69; }
    if ((token === import35.Haptic)) { return this._Haptic_70; }
    if ((token === import36.GestureController)) { return this._GestureController_71; }
    if ((token === import37.Keyboard)) { return this._Keyboard_72; }
    if ((token === import38.LoadingController)) { return this._LoadingController_73; }
    if ((token === import91.LocationStrategy)) { return this._LocationStrategy_74; }
    if ((token === import39.Location)) { return this._Location_75; }
    if ((token === import40.MenuController)) { return this._MenuController_76; }
    if ((token === import41.ModalController)) { return this._ModalController_77; }
    if ((token === import42.PickerController)) { return this._PickerController_78; }
    if ((token === import43.PopoverController)) { return this._PopoverController_79; }
    if ((token === import44.TapClick)) { return this._TapClick_80; }
    if ((token === import45.ToastController)) { return this._ToastController_81; }
    if ((token === import46.Translate)) { return this._Translate_82; }
    if ((token === import47.TransitionController)) { return this._TransitionController_83; }
    if ((token === import92.UrlSerializer)) { return this._UrlSerializer_84; }
    if ((token === import93.DeepLinker)) { return this._DeepLinker_85; }
    if ((token === import48.MenuService)) { return this._MenuService_86; }
    if ((token === import49.CategoryService)) { return this._CategoryService_87; }
    if ((token === import50.ItemService)) { return this._ItemService_88; }
    if ((token === import51.CartService)) { return this._CartService_89; }
    if ((token === import52.PostService)) { return this._PostService_90; }
    if ((token === import53.ChatService)) { return this._ChatService_91; }
    if ((token === import54.UserService)) { return this._UserService_92; }
    if ((token === import55.FireService)) { return this._FireService_93; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__27.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);