/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/platform/platform';
import * as import9 from '../services/fire-service';
import * as import10 from 'ionic-angular/util/events';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/core/src/linker/query_list';
import * as import14 from '../node_modules/ionic-angular/components/menu/menu.ngfactory';
import * as import15 from '../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import16 from '../node_modules/ionic-angular/components/menu/menu-close.ngfactory';
import * as import17 from '../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import18 from '../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import19 from '../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import20 from '../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import21 from '../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import22 from '../node_modules/ionic-angular/components/nav/nav.ngfactory';
import * as import23 from 'ionic-angular/components/menu/menu-controller';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from 'ionic-angular/util/keyboard';
import * as import27 from '@angular/core/src/zone/ng_zone';
import * as import28 from 'ionic-angular/gestures/gesture-controller';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from '@angular/core/src/linker/template_ref';
import * as import33 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import34 from 'ionic-angular/util/form';
import * as import35 from 'ionic-angular/navigation/nav-controller-base';
import * as import36 from '@angular/core/src/linker/component_factory_resolver';
import * as import37 from 'ionic-angular/transitions/transition-controller';
import * as import38 from 'ionic-angular/navigation/deep-linker';
import * as import39 from 'ionic-angular/components/typography/typography';
import * as import40 from 'ionic-angular/components/menu/menu-close';
import * as import41 from '@angular/common/src/directives/ng_for';
import * as import42 from 'ionic-angular/components/icon/icon';
import * as import43 from 'ionic-angular/components/item/item';
import * as import44 from 'ionic-angular/components/list/list';
import * as import45 from 'ionic-angular/components/content/content';
import * as import46 from 'ionic-angular/components/menu/menu';
import * as import47 from 'ionic-angular/components/nav/nav';
import * as import48 from '@angular/core/src/security';
import * as import49 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import50 from '@angular/common/src/directives/ng_if';
import * as import51 from '../node_modules/ionic-angular/components/badge/badge.ngfactory';
import * as import52 from 'ionic-angular/components/badge/badge';
export class Wrapper_MyApp {
  context:import0.MyApp;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.MyApp(p0,p1,p2);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_MyApp_Host:import2.RenderComponentType = (null as any);
class _View_MyApp_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _MyApp_0_4:Wrapper_MyApp;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp_Host0,renderType_MyApp_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ng-component',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_MyApp0(this.viewUtils,this.injector(0),this._appEl_0);
    this._MyApp_0_4 = new Wrapper_MyApp(this.parentInjector.get(import8.Platform),this.parentInjector.get(import9.FireService),this.parentInjector.get(import10.Events));
    this._appEl_0.initComponent(this._MyApp_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._MyApp_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.MyApp) && (0 === requestNodeIndex))) { return this._MyApp_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._MyApp_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyApp_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_MyApp_Host === (null as any))) { (renderType_MyApp_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_MyApp_Host0(viewUtils,parentInjector,declarationEl);
}
export const MyAppNgFactory:import12.ComponentFactory<import0.MyApp> = new import12.ComponentFactory<import0.MyApp>('ng-component',viewFactory_MyApp_Host0,import0.MyApp);
const styles_MyApp:any[] = ([] as any[]);
var renderType_MyApp:import2.RenderComponentType = (null as any);
class _View_MyApp0 extends import1.AppView<import0.MyApp> {
  _viewQuery_content_0:import13.QueryList<any>;
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Menu_0_4:import14.Wrapper_Menu;
  _query_Content_0_0:import13.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Content_2_4:import15.Wrapper_Content;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _MenuClose_7_3:import16.Wrapper_MenuClose;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _Typography_11_3:import17.Wrapper_Typography;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _List_16_3:import18.Wrapper_List;
  _text_17:any;
  _anchor_18:any;
  /*private*/ _appEl_18:import3.AppElement;
  _TemplateRef_18_5:any;
  _NgFor_18_6:import19.Wrapper_NgFor;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _Item_20_4:import20.Wrapper_Item;
  _ItemContent_20_5:import20.Wrapper_ItemContent;
  _MenuClose_20_6:import16.Wrapper_MenuClose;
  _query_Label_20_0:import13.QueryList<any>;
  _query_Button_20_1:import13.QueryList<any>;
  _query_Icon_20_2:import13.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Icon_22_3:import21.Wrapper_Icon;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Nav_28_4:import22.Wrapper_Nav;
  _text_29:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_13:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp0,renderType_MyApp,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_content_0 = new import13.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-menu',(null as any));
    this.renderer.setElementAttribute(this._el_0,'role','navigation');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import14.viewFactory_Menu0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Menu_0_4 = new import14.Wrapper_Menu(this.parentInjector.get(import23.MenuController),new import24.ElementRef(this._el_0),this.parentInjector.get(import25.Config),this.parentInjector.get(import8.Platform),this.renderer,this.parentInjector.get(import26.Keyboard),this.parentInjector.get(import27.NgZone),this.parentInjector.get(import28.GestureController));
    this._query_Content_0_0 = new import13.QueryList<any>();
    this._appEl_0.initComponent(this._Menu_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','menu-left');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import15.viewFactory_Content0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Content_2_4 = new import15.Wrapper_Content(this.parentInjector.get(import25.Config),new import24.ElementRef(this._el_2),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import26.Keyboard),this.parentInjector.get(import27.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_2.initComponent(this._Content_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','primary-bg menu-left');
    this.renderer.setElementAttribute(this._el_5,'padding-bottom','');
    this.renderer.setElementAttribute(this._el_5,'padding-top','');
    this.renderer.setElementAttribute(this._el_5,'text-center','');
    this._text_6 = this.renderer.createText(this._el_5,'\n      ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'a',(null as any));
    this.renderer.setElementAttribute(this._el_7,'menuClose','');
    this._MenuClose_7_3 = new import16.Wrapper_MenuClose(this.parentInjector.get(import23.MenuController));
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'img',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','profile-picture');
    this._text_10 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_11 = this.renderer.createElement(this._el_7,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_11,'color','light');
    this._Typography_11_3 = new import17.Wrapper_Typography(this.parentInjector.get(import25.Config),new import24.ElementRef(this._el_11),this.renderer);
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_14 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','list-full-border');
    this._List_16_3 = new import18.Wrapper_List(this.parentInjector.get(import25.Config),new import24.ElementRef(this._el_16),this.renderer,this.parentInjector.get(import28.GestureController));
    this._text_17 = this.renderer.createText(this._el_16,'\n      ',(null as any));
    this._anchor_18 = this.renderer.createTemplateAnchor(this._el_16,(null as any));
    this._appEl_18 = new import3.AppElement(18,16,this,this._anchor_18);
    this._TemplateRef_18_5 = new import32.TemplateRef_(this._appEl_18,viewFactory_MyApp1);
    this._NgFor_18_6 = new import19.Wrapper_NgFor(this._appEl_18.vcRef,this._TemplateRef_18_5,this.parentInjector.get(import33.IterableDiffers),this.ref);
    this._text_19 = this.renderer.createText(this._el_16,'\n      \n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_16,'button',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','item item-block');
    this.renderer.setElementAttribute(this._el_20,'ion-item','');
    this.renderer.setElementAttribute(this._el_20,'menuClose','');
    this._appEl_20 = new import3.AppElement(20,16,this,this._el_20);
    var compView_20:any = import20.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import20.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import25.Config),new import24.ElementRef(this._el_20),this.renderer);
    this._ItemContent_20_5 = new import20.Wrapper_ItemContent();
    this._MenuClose_20_6 = new import16.Wrapper_MenuClose(this.parentInjector.get(import23.MenuController));
    this._query_Label_20_0 = new import13.QueryList<any>();
    this._query_Button_20_1 = new import13.QueryList<any>();
    this._query_Icon_20_2 = new import13.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4.context,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_22,'item-left','');
    this.renderer.setElementAttribute(this._el_22,'name','ios-exit-outline');
    this.renderer.setElementAttribute(this._el_22,'role','img');
    this._Icon_22_3 = new import21.Wrapper_Icon(this.parentInjector.get(import25.Config),new import24.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText((null as any),'\n        Logout\n      ',(null as any));
    this._query_Label_20_0.reset(([] as any[]));
    this._Item_20_4.context.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4.context,[
      ([] as any[]).concat([this._el_22]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_21,
        this._text_23
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Content_2_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_4,
        this._el_5,
        this._text_15,
        this._el_16,
        this._text_25
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._query_Content_0_0.reset([this._Content_2_4.context]);
    this._Menu_0_4.context.menuContent = this._query_Content_0_0.first;
      compView_0.create(this._Menu_0_4.context,[([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_26
      ]
    )],(null as any));
    this._text_27 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_28 = this.renderer.createElement(parentRenderNode,'ion-nav',(null as any));
    this.renderer.setElementAttribute(this._el_28,'swipeBackEnabled','false');
    this._appEl_28 = new import3.AppElement(28,(null as any),this,this._el_28);
    var compView_28:any = import22.viewFactory_Nav0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Nav_28_4 = new import22.Wrapper_Nav(this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import35.NavControllerBase,(null as any)),this.parentInjector.get(import29.App),this.parentInjector.get(import25.Config),this.parentInjector.get(import26.Keyboard),new import24.ElementRef(this._el_28),this.parentInjector.get(import27.NgZone),this.renderer,this.parentInjector.get(import36.ComponentFactoryResolver),this.parentInjector.get(import28.GestureController),this.parentInjector.get(import37.TransitionController),this.parentInjector.get(import38.DeepLinker,(null as any)));
    this._appEl_28.initComponent(this._Nav_28_4.context,([] as any[]),compView_28);
    compView_28.create(this._Nav_28_4.context,([] as any[]),(null as any));
    this._text_29 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._viewQuery_content_0.reset([this._Nav_28_4.context]);
    this.context.nav = this._viewQuery_content_0.first;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._anchor_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.Typography) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Typography_11_3.context; }
    if (((token === import40.MenuClose) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._MenuClose_7_3.context; }
    if (((token === import32.TemplateRef) && (18 === requestNodeIndex))) { return this._TemplateRef_18_5; }
    if (((token === import41.NgFor) && (18 === requestNodeIndex))) { return this._NgFor_18_6.context; }
    if (((token === import42.Icon) && (22 === requestNodeIndex))) { return this._Icon_22_3.context; }
    if (((token === import43.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_20_4.context; }
    if (((token === import43.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemContent_20_5.context; }
    if (((token === import40.MenuClose) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._MenuClose_20_6.context; }
    if (((token === import44.List) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._List_16_3.context; }
    if (((token === import45.Content) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Content_2_4.context; }
    if (((token === import46.Menu) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Menu_0_4.context; }
    if (((token === import47.Nav) && (28 === requestNodeIndex))) { return this._Nav_28_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_0:any = this._Nav_28_4.context;
    this._Menu_0_4.check_content(currVal_0,throwOnChange,false);
    if (this._Menu_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (this._Content_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuClose_7_3.check_menuClose(currVal_4,throwOnChange,false);
    this._MenuClose_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    const currVal_6:any = 'light';
    this._Typography_11_3.check_color(currVal_6,throwOnChange,false);
    this._Typography_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    this._List_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_8:any = this.context.pages;
    this._NgFor_18_6.check_ngForOf(currVal_8,throwOnChange,false);
    this._NgFor_18_6.detectChangesInternal(this,this._anchor_18,throwOnChange);
    if (this._Item_20_4.detectChangesInternal(this,this._el_20,throwOnChange)) { this._appEl_20.componentView.markAsCheckOnce(); }
    this._ItemContent_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_11:any = '';
    this._MenuClose_20_6.check_menuClose(currVal_11,throwOnChange,false);
    this._MenuClose_20_6.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_12:any = 'ios-exit-outline';
    this._Icon_22_3.check_name(currVal_12,throwOnChange,false);
    this._Icon_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_14:any = this.context.rootPage;
    this._Nav_28_4.check_root(currVal_14,throwOnChange,false);
    const currVal_15:any = 'false';
    this._Nav_28_4.check_swipeBackEnabled(currVal_15,throwOnChange,false);
    this._Nav_28_4.detectChangesInternal(this,this._el_28,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset(([] as any[]));
        this._Item_20_4.context._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset([this._Icon_22_3.context]);
        this._Item_20_4.context._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_20_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Content_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_5:any = this.context.user.imageUrl;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_9,'src',this.viewUtils.sanitizer.sanitize(import48.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = import4.interpolate(1,'',this.context.user.displayName,'');
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setText(this._text_12,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_13:any = this._Icon_22_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_22,'hide',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Nav_28_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_22_3.context.ngOnDestroy();
    this._Content_2_4.context.ngOnDestroy();
    this._Menu_0_4.context.ngOnDestroy();
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.viewMyProfile()) !== false);
    const pd_1:any = ((<any>this._MenuClose_7_3.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.logout()) !== false);
    const pd_1:any = ((<any>this._MenuClose_20_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
export function viewFactory_MyApp0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.MyApp> {
  if ((renderType_MyApp === (null as any))) { (renderType_MyApp = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_MyApp,{})); }
  return new _View_MyApp0(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import20.Wrapper_Item;
  _ItemContent_0_5:import20.Wrapper_ItemContent;
  _MenuClose_0_6:import16.Wrapper_MenuClose;
  _query_Label_0_0:import13.QueryList<any>;
  _query_Button_0_1:import13.QueryList<any>;
  _query_Icon_0_2:import13.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Icon_2_3:import21.Wrapper_Icon;
  _text_3:any;
  _anchor_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _TemplateRef_4_5:any;
  _NgIf_4_6:import49.Wrapper_NgIf;
  _text_5:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp1,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'ion-item','');
    this.renderer.setElementAttribute(this._el_0,'menuClose','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import20.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import20.Wrapper_Item(this.parent.parentInjector.get(import34.Form),this.parent.parentInjector.get(import25.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import20.Wrapper_ItemContent();
    this._MenuClose_0_6 = new import16.Wrapper_MenuClose(this.parent.parentInjector.get(import23.MenuController));
    this._query_Label_0_0 = new import13.QueryList<any>();
    this._query_Button_0_1 = new import13.QueryList<any>();
    this._query_Icon_0_2 = new import13.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this.renderer.setElementAttribute(this._el_2,'role','img');
    this._Icon_2_3 = new import21.Wrapper_Icon(this.parent.parentInjector.get(import25.Config),new import24.ElementRef(this._el_2),this.renderer);
    this._text_3 = this.renderer.createText((null as any),'',(null as any));
    this._anchor_4 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_4 = new import3.AppElement(4,0,this,this._anchor_4);
    this._TemplateRef_4_5 = new import32.TemplateRef_(this._appEl_4,viewFactory_MyApp2);
    this._NgIf_4_6 = new import49.Wrapper_NgIf(this._appEl_4.vcRef,this._TemplateRef_4_5);
    this._text_5 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_3,
        this._text_5
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._appEl_4])
    ]
    ,(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._anchor_4,
      this._text_5
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import42.Icon) && (2 === requestNodeIndex))) { return this._Icon_2_3.context; }
    if (((token === import32.TemplateRef) && (4 === requestNodeIndex))) { return this._TemplateRef_4_5; }
    if (((token === import50.NgIf) && (4 === requestNodeIndex))) { return this._NgIf_4_6.context; }
    if (((token === import43.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Item_0_4.context; }
    if (((token === import43.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ItemContent_0_5.context; }
    if (((token === import40.MenuClose) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._MenuClose_0_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_2:any = '';
    this._MenuClose_0_6.check_menuClose(currVal_2,throwOnChange,false);
    this._MenuClose_0_6.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.icon,'');
    this._Icon_2_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_6:any = this.context.$implicit.count;
    this._NgIf_4_6.check_ngIf(currVal_6,throwOnChange,false);
    this._NgIf_4_6.detectChangesInternal(this,this._anchor_4,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset([this._Icon_2_3.context]);
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_4:any = this._Icon_2_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,'\n        ',this.context.$implicit.title,'\n        ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_3,currVal_5);
      this._expr_5 = currVal_5;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_2_3.context.ngOnDestroy();
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.openPage(this.context.$implicit)) !== false);
    const pd_1:any = ((<any>this._MenuClose_0_6.context.close()) !== false);
    return ((true && pd_0) && pd_1);
  }
}
function viewFactory_MyApp1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyApp1(viewUtils,parentInjector,declarationEl);
}
class _View_MyApp2 extends import1.AppView<any> {
  _el_0:any;
  _Badge_0_3:import51.Wrapper_Badge;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_MyApp2,renderType_MyApp,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-badge',(null as any));
    this.renderer.setElementAttribute(this._el_0,'danger','');
    this.renderer.setElementAttribute(this._el_0,'item-right','');
    this._Badge_0_3 = new import51.Wrapper_Badge(this.parent.parent.parentInjector.get(import25.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import52.Badge) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._Badge_0_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Badge_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.$implicit.count,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_MyApp2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_MyApp2(viewUtils,parentInjector,declarationEl);
}