/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './register';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../services/user-service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import21 from 'ionic-angular/config/config';
import * as import22 from '@angular/core/src/linker/element_ref';
import * as import23 from 'ionic-angular/components/app/app';
import * as import24 from 'ionic-angular/util/keyboard';
import * as import25 from '@angular/core/src/zone/ng_zone';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/tabs/tabs';
import * as import28 from 'ionic-angular/gestures/gesture-controller';
import * as import29 from 'ionic-angular/util/form';
import * as import30 from 'ionic-angular/platform/platform';
import * as import31 from '@angular/forms/src/directives/ng_control';
import * as import32 from 'ionic-angular/components/icon/icon';
import * as import33 from 'ionic-angular/components/typography/typography';
import * as import34 from 'ionic-angular/components/label/label';
import * as import35 from 'ionic-angular/components/input/input';
import * as import36 from 'ionic-angular/components/item/item';
import * as import37 from 'ionic-angular/components/list/list';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/components/content/content';
export class Wrapper_RegisterPage {
  context:import0.RegisterPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.RegisterPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_RegisterPage_Host:import2.RenderComponentType = (null as any);
class _View_RegisterPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _RegisterPage_0_4:Wrapper_RegisterPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RegisterPage_Host0,renderType_RegisterPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-register',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_RegisterPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._RegisterPage_0_4 = new Wrapper_RegisterPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.UserService));
    this._appEl_0.initComponent(this._RegisterPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._RegisterPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.RegisterPage) && (0 === requestNodeIndex))) { return this._RegisterPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._RegisterPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_RegisterPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_RegisterPage_Host === (null as any))) { (renderType_RegisterPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_RegisterPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const RegisterPageNgFactory:import11.ComponentFactory<import0.RegisterPage> = new import11.ComponentFactory<import0.RegisterPage>('page-register',viewFactory_RegisterPage_Host0,import0.RegisterPage);
const styles_RegisterPage:any[] = ([] as any[]);
var renderType_RegisterPage:import2.RenderComponentType = (null as any);
class _View_RegisterPage0 extends import1.AppView<import0.RegisterPage> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _Content_1_4:import12.Wrapper_Content;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _Icon_10_3:import13.Wrapper_Icon;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _Typography_13_3:import14.Wrapper_Typography;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _List_18_3:import15.Wrapper_List;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _Item_20_4:import16.Wrapper_Item;
  _ItemContent_20_5:import16.Wrapper_ItemContent;
  _query_Label_20_0:import17.QueryList<any>;
  _query_Button_20_1:import17.QueryList<any>;
  _query_Icon_20_2:import17.QueryList<any>;
  _text_21:any;
  _el_22:any;
  _Label_22_3:import18.Wrapper_Label;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _TextInput_25_4:import19.Wrapper_TextInput;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Item_28_4:import16.Wrapper_Item;
  _ItemContent_28_5:import16.Wrapper_ItemContent;
  _query_Label_28_0:import17.QueryList<any>;
  _query_Button_28_1:import17.QueryList<any>;
  _query_Icon_28_2:import17.QueryList<any>;
  _text_29:any;
  _el_30:any;
  _Label_30_3:import18.Wrapper_Label;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _TextInput_33_4:import19.Wrapper_TextInput;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import3.AppElement;
  _Item_36_4:import16.Wrapper_Item;
  _ItemContent_36_5:import16.Wrapper_ItemContent;
  _query_Label_36_0:import17.QueryList<any>;
  _query_Button_36_1:import17.QueryList<any>;
  _query_Icon_36_2:import17.QueryList<any>;
  _text_37:any;
  _el_38:any;
  _Label_38_3:import18.Wrapper_Label;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _TextInput_41_4:import19.Wrapper_TextInput;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _Button_47_4:import20.Wrapper_Button;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _Typography_54_3:import14.Wrapper_Typography;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_RegisterPage0,renderType_RegisterPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_1,'class','auth-bg');
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import12.viewFactory_Content0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Content_1_4 = new import12.Wrapper_Content(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import23.App),this.parentInjector.get(import24.Keyboard),this.parentInjector.get(import25.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import27.Tabs,(null as any)));
    this._appEl_1.initComponent(this._Content_1_4.context,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','login-content');
    this._text_4 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._text_5 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'padding','');
    this.renderer.setElementAttribute(this._el_6,'text-center','');
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'div',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','logo primary-bg');
    this._text_9 = this.renderer.createText(this._el_8,'\n        ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_8,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_10,'color','light');
    this.renderer.setElementAttribute(this._el_10,'name','md-restaurant');
    this.renderer.setElementAttribute(this._el_10,'role','img');
    this._Icon_10_3 = new import13.Wrapper_Icon(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_10),this.renderer);
    this._text_11 = this.renderer.createText(this._el_8,'\n      ',(null as any));
    this._text_12 = this.renderer.createText(this._el_6,'\n      ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_6,'h2',(null as any));
    this.renderer.setElementAttribute(this._el_13,'color','light');
    this._Typography_13_3 = new import14.Wrapper_Typography(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_13),this.renderer);
    this._text_14 = this.renderer.createText(this._el_13,'\n        Ionic 2 Restaurant\n      ',(null as any));
    this._text_15 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._text_17 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_3,'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','list-form');
    this.renderer.setElementAttribute(this._el_18,'padding','');
    this._List_18_3 = new import15.Wrapper_List(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_18),this.renderer,this.parentInjector.get(import28.GestureController));
    this._text_19 = this.renderer.createText(this._el_18,'\n\n      ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','item item-block');
    this._appEl_20 = new import3.AppElement(20,18,this,this._el_20);
    var compView_20:any = import16.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import16.Wrapper_Item(this.parentInjector.get(import29.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_20),this.renderer);
    this._ItemContent_20_5 = new import16.Wrapper_ItemContent();
    this._query_Label_20_0 = new import17.QueryList<any>();
    this._query_Button_20_1 = new import17.QueryList<any>();
    this._query_Icon_20_2 = new import17.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4.context,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_22,'stacked','');
    this._Label_22_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_22),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Name',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_25,'type','text');
    this._appEl_25 = new import3.AppElement(25,20,this,this._el_25);
    var compView_25:any = import19.viewFactory_TextInput0(this.viewUtils,this.injector(25),this._appEl_25);
    this._TextInput_25_4 = new import19.Wrapper_TextInput(this.parentInjector.get(import21.Config),this.parentInjector.get(import29.Form),this._Item_20_4.context,this.parentInjector.get(import23.App),this.parentInjector.get(import30.Platform),new import22.ElementRef(this._el_25),this.renderer,this._Content_1_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import31.NgControl,(null as any)));
    this._appEl_25.initComponent(this._TextInput_25_4.context,([] as any[]),compView_25);
    compView_25.create(this._TextInput_25_4.context,([] as any[]),(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_20_0.reset([this._Label_22_3.context]);
    this._Item_20_4.context.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_22]),
      ([] as any[]).concat([
        this._text_21,
        this._text_24,
        this._text_26
      ]
      ),
      ([] as any[]).concat([this._el_25]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_27 = this.renderer.createText(this._el_18,'\n\n      ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_18,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','item item-block');
    this._appEl_28 = new import3.AppElement(28,18,this,this._el_28);
    var compView_28:any = import16.viewFactory_Item0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Item_28_4 = new import16.Wrapper_Item(this.parentInjector.get(import29.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_28),this.renderer);
    this._ItemContent_28_5 = new import16.Wrapper_ItemContent();
    this._query_Label_28_0 = new import17.QueryList<any>();
    this._query_Button_28_1 = new import17.QueryList<any>();
    this._query_Icon_28_2 = new import17.QueryList<any>();
    this._appEl_28.initComponent(this._Item_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_30,'stacked','');
    this._Label_30_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_30),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'Email',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_33,'type','text');
    this._appEl_33 = new import3.AppElement(33,28,this,this._el_33);
    var compView_33:any = import19.viewFactory_TextInput0(this.viewUtils,this.injector(33),this._appEl_33);
    this._TextInput_33_4 = new import19.Wrapper_TextInput(this.parentInjector.get(import21.Config),this.parentInjector.get(import29.Form),this._Item_28_4.context,this.parentInjector.get(import23.App),this.parentInjector.get(import30.Platform),new import22.ElementRef(this._el_33),this.renderer,this._Content_1_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import31.NgControl,(null as any)));
    this._appEl_33.initComponent(this._TextInput_33_4.context,([] as any[]),compView_33);
    compView_33.create(this._TextInput_33_4.context,([] as any[]),(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_28_0.reset([this._Label_30_3.context]);
    this._Item_28_4.context.contentLabel = this._query_Label_28_0.first;
    compView_28.create(this._Item_28_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_30]),
      ([] as any[]).concat([
        this._text_29,
        this._text_32,
        this._text_34
      ]
      ),
      ([] as any[]).concat([this._el_33]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_18,'\n\n      ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_18,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','item item-block');
    this._appEl_36 = new import3.AppElement(36,18,this,this._el_36);
    var compView_36:any = import16.viewFactory_Item0(this.viewUtils,this.injector(36),this._appEl_36);
    this._Item_36_4 = new import16.Wrapper_Item(this.parentInjector.get(import29.Form),this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_36),this.renderer);
    this._ItemContent_36_5 = new import16.Wrapper_ItemContent();
    this._query_Label_36_0 = new import17.QueryList<any>();
    this._query_Button_36_1 = new import17.QueryList<any>();
    this._query_Icon_36_2 = new import17.QueryList<any>();
    this._appEl_36.initComponent(this._Item_36_4.context,([] as any[]),compView_36);
    this._text_37 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_38,'stacked','');
    this._Label_38_3 = new import18.Wrapper_Label(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_38),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'Password',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_41,'type','password');
    this._appEl_41 = new import3.AppElement(41,36,this,this._el_41);
    var compView_41:any = import19.viewFactory_TextInput0(this.viewUtils,this.injector(41),this._appEl_41);
    this._TextInput_41_4 = new import19.Wrapper_TextInput(this.parentInjector.get(import21.Config),this.parentInjector.get(import29.Form),this._Item_36_4.context,this.parentInjector.get(import23.App),this.parentInjector.get(import30.Platform),new import22.ElementRef(this._el_41),this.renderer,this._Content_1_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import31.NgControl,(null as any)));
    this._appEl_41.initComponent(this._TextInput_41_4.context,([] as any[]),compView_41);
    compView_41.create(this._TextInput_41_4.context,([] as any[]),(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_36_0.reset([this._Label_38_3.context]);
    this._Item_36_4.context.contentLabel = this._query_Label_36_0.first;
    compView_36.create(this._Item_36_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_38]),
      ([] as any[]).concat([
        this._text_37,
        this._text_40,
        this._text_42
      ]
      ),
      ([] as any[]).concat([this._el_41]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_43 = this.renderer.createText(this._el_18,'\n\n    ',(null as any));
    this._text_44 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_45,'margin-top','');
    this._text_46 = this.renderer.createText(this._el_45,'\n      ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'button',(null as any));
    this.renderer.setElementAttribute(this._el_47,'block','');
    this.renderer.setElementAttribute(this._el_47,'color','primary');
    this.renderer.setElementAttribute(this._el_47,'ion-button','');
    this._appEl_47 = new import3.AppElement(47,45,this,this._el_47);
    var compView_47:any = import20.viewFactory_Button0(this.viewUtils,this.injector(47),this._appEl_47);
    this._Button_47_4 = new import20.Wrapper_Button((null as any),'',this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_47),this.renderer);
    this._appEl_47.initComponent(this._Button_47_4.context,([] as any[]),compView_47);
    this._text_48 = this.renderer.createText((null as any),'\n        SIGN UP\n      ',(null as any));
    compView_47.create(this._Button_47_4.context,[([] as any[]).concat([this._text_48])],(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n    ',(null as any));
    this._text_50 = this.renderer.createText(this._el_3,'\n\n    ',(null as any));
    this._text_51 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_3,'div',(null as any));
    this.renderer.setElementAttribute(this._el_52,'margin-top','');
    this.renderer.setElementAttribute(this._el_52,'text-center','');
    this._text_53 = this.renderer.createText(this._el_52,'\n      ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_52,'span',(null as any));
    this.renderer.setElementAttribute(this._el_54,'color','light');
    this._Typography_54_3 = new import14.Wrapper_Typography(this.parentInjector.get(import21.Config),new import22.ElementRef(this._el_54),this.renderer);
    this._text_55 = this.renderer.createText(this._el_54,'I have an account',(null as any));
    this._text_56 = this.renderer.createText(this._el_52,'\n    ',(null as any));
    this._text_57 = this.renderer.createText(this._el_3,'\n\n  ',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n',(null as any));
    compView_1.create(this._Content_1_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_58
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_59 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_54,'click',this.eventHandler(this._handle_click_54_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import32.Icon) && (10 === requestNodeIndex))) { return this._Icon_10_3.context; }
    if (((token === import33.Typography) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._Typography_13_3.context; }
    if (((token === import34.Label) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Label_22_3.context; }
    if (((token === import35.TextInput) && (25 === requestNodeIndex))) { return this._TextInput_25_4.context; }
    if (((token === import36.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Item_20_4.context; }
    if (((token === import36.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ItemContent_20_5.context; }
    if (((token === import34.Label) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Label_30_3.context; }
    if (((token === import35.TextInput) && (33 === requestNodeIndex))) { return this._TextInput_33_4.context; }
    if (((token === import36.Item) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_28_4.context; }
    if (((token === import36.ItemContent) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_28_5.context; }
    if (((token === import34.Label) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Label_38_3.context; }
    if (((token === import35.TextInput) && (41 === requestNodeIndex))) { return this._TextInput_41_4.context; }
    if (((token === import36.Item) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Item_36_4.context; }
    if (((token === import36.ItemContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ItemContent_36_5.context; }
    if (((token === import37.List) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._List_18_3.context; }
    if (((token === import38.Button) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Button_47_4.context; }
    if (((token === import33.Typography) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Typography_54_3.context; }
    if (((token === import39.Content) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Content_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_1_4.detectChangesInternal(this,this._el_1,throwOnChange)) { this._appEl_1.componentView.markAsCheckOnce(); }
    const currVal_1:any = 'light';
    this._Icon_10_3.check_color(currVal_1,throwOnChange,false);
    const currVal_2:any = 'md-restaurant';
    this._Icon_10_3.check_name(currVal_2,throwOnChange,false);
    this._Icon_10_3.detectChangesInternal(this,this._el_10,throwOnChange);
    const currVal_4:any = 'light';
    this._Typography_13_3.check_color(currVal_4,throwOnChange,false);
    this._Typography_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._List_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    if (this._Item_20_4.detectChangesInternal(this,this._el_20,throwOnChange)) { this._appEl_20.componentView.markAsCheckOnce(); }
    this._ItemContent_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    this._Label_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_5:any = 'text';
    this._TextInput_25_4.check_type(currVal_5,throwOnChange,false);
    this._TextInput_25_4.detectChangesInternal(this,this._el_25,throwOnChange);
    if (this._Item_28_4.detectChangesInternal(this,this._el_28,throwOnChange)) { this._appEl_28.componentView.markAsCheckOnce(); }
    this._ItemContent_28_5.detectChangesInternal(this,this._el_28,throwOnChange);
    this._Label_30_3.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_6:any = 'text';
    this._TextInput_33_4.check_type(currVal_6,throwOnChange,false);
    this._TextInput_33_4.detectChangesInternal(this,this._el_33,throwOnChange);
    if (this._Item_36_4.detectChangesInternal(this,this._el_36,throwOnChange)) { this._appEl_36.componentView.markAsCheckOnce(); }
    this._ItemContent_36_5.detectChangesInternal(this,this._el_36,throwOnChange);
    this._Label_38_3.detectChangesInternal(this,this._el_38,throwOnChange);
    const currVal_7:any = 'password';
    this._TextInput_41_4.check_type(currVal_7,throwOnChange,false);
    this._TextInput_41_4.detectChangesInternal(this,this._el_41,throwOnChange);
    const currVal_9:any = '';
    this._Button_47_4.check_block(currVal_9,throwOnChange,false);
    const currVal_10:any = 'primary';
    this._Button_47_4.check_color(currVal_10,throwOnChange,false);
    if (this._Button_47_4.detectChangesInternal(this,this._el_47,throwOnChange)) { this._appEl_47.componentView.markAsCheckOnce(); }
    const currVal_12:any = 'light';
    this._Typography_54_3.check_color(currVal_12,throwOnChange,false);
    this._Typography_54_3.detectChangesInternal(this,this._el_54,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset(([] as any[]));
        this._Item_20_4.context._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset(([] as any[]));
        this._Item_20_4.context._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if (this._query_Button_28_1.dirty) {
        this._query_Button_28_1.reset(([] as any[]));
        this._Item_28_4.context._buttons = this._query_Button_28_1;
        this._query_Button_28_1.notifyOnChanges();
      }
      if (this._query_Icon_28_2.dirty) {
        this._query_Icon_28_2.reset(([] as any[]));
        this._Item_28_4.context._icons = this._query_Icon_28_2;
        this._query_Icon_28_2.notifyOnChanges();
      }
      if (this._query_Button_36_1.dirty) {
        this._query_Button_36_1.reset(([] as any[]));
        this._Item_36_4.context._buttons = this._query_Button_36_1;
        this._query_Button_36_1.notifyOnChanges();
      }
      if (this._query_Icon_36_2.dirty) {
        this._query_Icon_36_2.reset(([] as any[]));
        this._Item_36_4.context._icons = this._query_Icon_36_2;
        this._query_Icon_36_2.notifyOnChanges();
      }
      this._TextInput_25_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_20_4.context.ngAfterContentInit(); }
      this._TextInput_33_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_28_4.context.ngAfterContentInit(); }
      this._TextInput_41_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_36_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_47_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_1_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_1,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_3:any = this._Icon_10_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'hide',currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_10_3.context.ngOnDestroy();
    this._TextInput_25_4.context.ngOnDestroy();
    this._TextInput_33_4.context.ngOnDestroy();
    this._TextInput_41_4.context.ngOnDestroy();
    this._Content_1_4.context.ngOnDestroy();
  }
  private _handle_click_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.register(this._TextInput_33_4.context.value,this._TextInput_41_4.context.value,this._TextInput_25_4.context.value)) !== false);
    return (true && pd_0);
  }
  private _handle_click_54_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.login()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_RegisterPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.RegisterPage> {
  if ((renderType_RegisterPage === (null as any))) { (renderType_RegisterPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_RegisterPage,{})); }
  return new _View_RegisterPage0(viewUtils,parentInjector,declarationEl);
}