/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './cart';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../services/cart-service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/menu/menu-controller';
import * as import29 from 'ionic-angular/components/toolbar/toolbar';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from 'ionic-angular/gestures/gesture-controller';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import36 from 'ionic-angular/components/navbar/navbar';
import * as import37 from 'ionic-angular/components/icon/icon';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/components/menu/menu-toggle';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from '@angular/common/src/directives/ng_for';
import * as import43 from 'ionic-angular/components/list/list';
import * as import44 from 'ionic-angular/components/content/content';
import * as import45 from 'ionic-angular/components/typography/typography';
import * as import46 from '../../node_modules/ionic-angular/components/item/item-sliding.ngfactory';
import * as import47 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import48 from '../../node_modules/ionic-angular/components/thumbnail/thumbnail.ngfactory';
import * as import49 from 'ionic-angular/util/form';
import * as import50 from 'ionic-angular/components/thumbnail/thumbnail';
import * as import51 from 'ionic-angular/components/item/item';
import * as import52 from 'ionic-angular/components/item/item-sliding';
import * as import53 from '@angular/core/src/security';
export class Wrapper_CartPage {
  context:import0.CartPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.CartPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_CartPage_Host:import2.RenderComponentType = (null as any);
class _View_CartPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _CartPage_0_4:Wrapper_CartPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CartPage_Host0,renderType_CartPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-cart',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_CartPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._CartPage_0_4 = new Wrapper_CartPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.CartService));
    this._appEl_0.initComponent(this._CartPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._CartPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.CartPage) && (0 === requestNodeIndex))) { return this._CartPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._CartPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_CartPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_CartPage_Host === (null as any))) { (renderType_CartPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_CartPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const CartPageNgFactory:import11.ComponentFactory<import0.CartPage> = new import11.ComponentFactory<import0.CartPage>('page-cart',viewFactory_CartPage_Host0,import0.CartPage);
const styles_CartPage:any[] = ([] as any[]);
var renderType_CartPage:import2.RenderComponentType = (null as any);
class _View_CartPage0 extends import1.AppView<import0.CartPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import12.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import13.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import14.Wrapper_Button;
  _MenuToggle_5_5:import15.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import16.Wrapper_ToolbarItem;
  _query_Button_5_0:import17.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import18.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _ToolbarTitle_10_4:import19.Wrapper_ToolbarTitle;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _ToolbarItem_13_3:import16.Wrapper_ToolbarItem;
  _query_Button_13_0:import17.QueryList<any>;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Button_15_4:import14.Wrapper_Button;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import18.Wrapper_Icon;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Content_23_4:import20.Wrapper_Content;
  _text_24:any;
  _el_25:any;
  _List_25_3:import21.Wrapper_List;
  _text_26:any;
  _anchor_27:any;
  /*private*/ _appEl_27:import3.AppElement;
  _TemplateRef_27_5:any;
  _NgFor_27_6:import22.Wrapper_NgFor;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _el_32:any;
  _Footer_32_3:import12.Wrapper_Footer;
  _text_33:any;
  _el_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _ToolbarTitle_34_4:import19.Wrapper_ToolbarTitle;
  _text_35:any;
  _el_36:any;
  _Typography_36_3:import23.Wrapper_Typography;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _Typography_41_3:import23.Wrapper_Typography;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _ToolbarItem_45_3:import16.Wrapper_ToolbarItem;
  _query_Button_45_0:import17.QueryList<any>;
  _text_46:any;
  _el_47:any;
  /*private*/ _appEl_47:import3.AppElement;
  _Button_47_4:import14.Wrapper_Button;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_14:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CartPage0,renderType_CartPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import12.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import14.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import14.Wrapper_Button('','',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import15.Wrapper_MenuToggle(this.parentInjector.get(import28.MenuController),new import25.ElementRef(this._el_5),this.parentInjector.get(import26.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import17.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import18.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_10 = new import3.AppElement(10,3,this,this._el_10);
    var compView_10:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(10),this._appEl_10);
    this._ToolbarTitle_10_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_10.initComponent(this._ToolbarTitle_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'Cart',(null as any));
    compView_10.create(this._ToolbarTitle_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_13,'end','');
    this._ToolbarItem_13_3 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_13_0 = new import17.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'ion-button','');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import14.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._Button_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_17,'name','md-more');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import18.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_15.create(this._Button_15_4.context,[([] as any[]).concat([
        this._text_16,
        this._el_17,
        this._text_18
      ]
    )],(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]),
      ([] as any[]).concat([this._el_13]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._el_10,
        this._text_12,
        this._text_20
      ]
      )
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_23 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','cart gray-bg');
    this.renderer.setElementAttribute(this._el_23,'padding','');
    this._appEl_23 = new import3.AppElement(23,(null as any),this,this._el_23);
    var compView_23:any = import20.viewFactory_Content0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Content_23_4 = new import20.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_23.initComponent(this._Content_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','list-no-border');
    this._List_25_3 = new import21.Wrapper_List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_25),this.renderer,this.parentInjector.get(import33.GestureController));
    this._text_26 = this.renderer.createText(this._el_25,'\n\n    ',(null as any));
    this._anchor_27 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._appEl_27 = new import3.AppElement(27,25,this,this._anchor_27);
    this._TemplateRef_27_5 = new import34.TemplateRef_(this._appEl_27,viewFactory_CartPage1);
    this._NgFor_27_6 = new import22.Wrapper_NgFor(this._appEl_27.vcRef,this._TemplateRef_27_5,this.parentInjector.get(import35.IterableDiffers),this.ref);
    this._text_28 = this.renderer.createText(this._el_25,'\n\n  ',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n',(null as any));
    compView_23.create(this._Content_23_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._el_25,
        this._text_29
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_30 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_32 = this.renderer.createElement(parentRenderNode,'ion-footer',(null as any));
    this.renderer.setElementAttribute(this._el_32,'class','cart-footer');
    this._Footer_32_3 = new import12.Wrapper_Footer(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_32),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_33 = this.renderer.createText(this._el_32,'\n  ',(null as any));
    this._el_34 = this.renderer.createElement(this._el_32,'ion-title',(null as any));
    this._appEl_34 = new import3.AppElement(34,32,this,this._el_34);
    var compView_34:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(34),this._appEl_34);
    this._ToolbarTitle_34_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_34),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this.parentInjector.get(import36.Navbar,(null as any)));
    this._appEl_34.initComponent(this._ToolbarTitle_34_4.context,([] as any[]),compView_34);
    this._text_35 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_36,'color','dark');
    this._Typography_36_3 = new import23.Wrapper_Typography(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_36),this.renderer);
    this._text_37 = this.renderer.createText(this._el_36,'Total',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_40 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_41 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','bold');
    this.renderer.setElementAttribute(this._el_41,'color','danger');
    this._Typography_41_3 = new import23.Wrapper_Typography(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_41),this.renderer);
    this._text_42 = this.renderer.createText(this._el_41,'',(null as any));
    this._text_43 = this.renderer.createText((null as any),'\n  ',(null as any));
      compView_34.create(this._ToolbarTitle_34_4.context,[([] as any[]).concat([
        this._text_35,
        this._el_36,
        this._text_38,
        this._el_39,
        this._text_40,
        this._el_41,
        this._text_43
      ]
    )],(null as any));
    this._text_44 = this.renderer.createText(this._el_32,'\n  ',(null as any));
    this._el_45 = this.renderer.createElement(this._el_32,'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_45,'end','');
    this._ToolbarItem_45_3 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_45),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this.parentInjector.get(import36.Navbar,(null as any)));
    this._query_Button_45_0 = new import17.QueryList<any>();
    this._text_46 = this.renderer.createText(this._el_45,'\n    ',(null as any));
    this._el_47 = this.renderer.createElement(this._el_45,'button',(null as any));
    this.renderer.setElementAttribute(this._el_47,'color','danger');
    this.renderer.setElementAttribute(this._el_47,'ion-button','');
    this._appEl_47 = new import3.AppElement(47,45,this,this._el_47);
    var compView_47:any = import14.viewFactory_Button0(this.viewUtils,this.injector(47),this._appEl_47);
    this._Button_47_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_47),this.renderer);
    this._appEl_47.initComponent(this._Button_47_4.context,([] as any[]),compView_47);
    this._text_48 = this.renderer.createText((null as any),'\n      BUY ALL\n    ',(null as any));
    compView_47.create(this._Button_47_4.context,[([] as any[]).concat([this._text_48])],(null as any));
    this._text_49 = this.renderer.createText(this._el_45,'\n  ',(null as any));
    this._text_50 = this.renderer.createText(this._el_32,'\n',(null as any));
    this._text_51 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_47,'click',this.eventHandler(this._handle_click_47_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._anchor_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._el_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import38.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import39.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import40.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import41.ToolbarTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarTitle_10_4.context; }
    if (((token === import37.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3.context; }
    if (((token === import38.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_15_4.context; }
    if (((token === import40.ToolbarItem) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ToolbarItem_13_3.context; }
    if (((token === import36.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Navbar_3_4.context; }
    if (((token === import29.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Header_1_3.context; }
    if (((token === import34.TemplateRef) && (27 === requestNodeIndex))) { return this._TemplateRef_27_5; }
    if (((token === import42.NgFor) && (27 === requestNodeIndex))) { return this._NgFor_27_6.context; }
    if (((token === import43.List) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._List_25_3.context; }
    if (((token === import44.Content) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Content_23_4.context; }
    if (((token === import45.Typography) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Typography_36_3.context; }
    if (((token === import45.Typography) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._Typography_41_3.context; }
    if (((token === import41.ToolbarTitle) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._ToolbarTitle_34_4.context; }
    if (((token === import38.Button) && ((47 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Button_47_4.context; }
    if (((token === import40.ToolbarItem) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._ToolbarItem_45_3.context; }
    if (((token === import29.Footer) && ((32 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Footer_32_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_7_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._ToolbarTitle_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._ToolbarItem_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    if (this._Button_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'md-more';
    this._Icon_17_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    if (this._Content_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._List_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_11:any = this.context.cart.items;
    this._NgFor_27_6.check_ngForOf(currVal_11,throwOnChange,false);
    this._NgFor_27_6.detectChangesInternal(this,this._anchor_27,throwOnChange);
    this._Footer_32_3.detectChangesInternal(this,this._el_32,throwOnChange);
    if (this._ToolbarTitle_34_4.detectChangesInternal(this,this._el_34,throwOnChange)) { this._appEl_34.componentView.markAsCheckOnce(); }
    const currVal_12:any = 'dark';
    this._Typography_36_3.check_color(currVal_12,throwOnChange,false);
    this._Typography_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    const currVal_13:any = 'danger';
    this._Typography_41_3.check_color(currVal_13,throwOnChange,false);
    this._Typography_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    this._ToolbarItem_45_3.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_16:any = 'danger';
    this._Button_47_4.check_color(currVal_16,throwOnChange,false);
    if (this._Button_47_4.detectChangesInternal(this,this._el_47,throwOnChange)) { this._appEl_47.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_13_0.dirty) {
        this._query_Button_13_0.reset([this._Button_15_4.context]);
        this._ToolbarItem_13_3.context._buttons = this._query_Button_13_0;
        this._query_Button_13_0.notifyOnChanges();
      }
      if (this._query_Button_45_0.dirty) {
        this._query_Button_45_0.reset([this._Button_47_4.context]);
        this._ToolbarItem_45_3.context._buttons = this._query_Button_45_0;
        this._query_Button_45_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_47_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = this._Icon_17_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_17,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_23_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_14:any = import4.interpolate(1,'$',this.context.cart.total,'');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_42,currVal_14);
      this._expr_14 = currVal_14;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Icon_17_3.context.ngOnDestroy();
    this._Content_23_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
  private _handle_click_47_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.buy()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_CartPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.CartPage> {
  if ((renderType_CartPage === (null as any))) { (renderType_CartPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_CartPage,{})); }
  return new _View_CartPage0(viewUtils,parentInjector,declarationEl);
}
class _View_CartPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ItemSliding_0_4:import46.Wrapper_ItemSliding;
  _query_Item_0_0:import17.QueryList<any>;
  _query_ItemOptions_0_1:import17.QueryList<any>;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Item_2_4:import47.Wrapper_Item;
  _ItemContent_2_5:import47.Wrapper_ItemContent;
  _query_Label_2_0:import17.QueryList<any>;
  _query_Button_2_1:import17.QueryList<any>;
  _query_Icon_2_2:import17.QueryList<any>;
  _text_3:any;
  _el_4:any;
  _Thumbnail_4_3:import48.Wrapper_Thumbnail;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _Typography_16_3:import23.Wrapper_Typography;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Button_23_4:import14.Wrapper_Button;
  _text_24:any;
  _el_25:any;
  _Icon_25_3:import18.Wrapper_Icon;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _Button_28_4:import14.Wrapper_Button;
  _text_29:any;
  _el_30:any;
  _Icon_30_3:import18.Wrapper_Icon;
  _text_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _ItemOptions_35_3:import46.Wrapper_ItemOptions;
  _text_36:any;
  _el_37:any;
  /*private*/ _appEl_37:import3.AppElement;
  _Button_37_4:import14.Wrapper_Button;
  _text_38:any;
  _el_39:any;
  _Icon_39_3:import18.Wrapper_Icon;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_CartPage1,renderType_CartPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item-sliding',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','card');
    this.renderer.setElementAttribute(this._el_0,'margin-top','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import46.viewFactory_ItemSliding0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ItemSliding_0_4 = new import46.Wrapper_ItemSliding((<_View_CartPage0>this.parent)._List_25_3.context,this.renderer,new import25.ElementRef(this._el_0),this.parent.parentInjector.get(import31.NgZone));
    this._query_Item_0_0 = new import17.QueryList<any>();
    this._query_ItemOptions_0_1 = new import17.QueryList<any>();
    this._appEl_0.initComponent(this._ItemSliding_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','item item-block');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import47.viewFactory_Item0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Item_2_4 = new import47.Wrapper_Item(this.parent.parentInjector.get(import49.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._ItemContent_2_5 = new import47.Wrapper_ItemContent();
    this._query_Label_2_0 = new import17.QueryList<any>();
    this._query_Button_2_1 = new import17.QueryList<any>();
    this._query_Icon_2_2 = new import17.QueryList<any>();
    this._appEl_2.initComponent(this._Item_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_4,'item-left','');
    this._Thumbnail_4_3 = new import48.Wrapper_Thumbnail();
    this._text_5 = this.renderer.createText(this._el_4,'\n          ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'img',(null as any));
    this.renderer.setElementAttribute(this._el_6,'alt','');
    this._text_7 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_8 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_9 = this.renderer.createElement((null as any),'h2',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n          ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'h2',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','price pull-left');
    this._text_15 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'span',(null as any));
    this.renderer.setElementAttribute(this._el_16,'color','primary');
    this._Typography_16_3 = new import23.Wrapper_Typography(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_14,'span',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'',(null as any));
    this._text_21 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._text_22 = this.renderer.createText(this._el_12,'\n          ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','button-qty pull-right');
    this.renderer.setElementAttribute(this._el_23,'color','primary');
    this.renderer.setElementAttribute(this._el_23,'ion-button','');
    this._appEl_23 = new import3.AppElement(23,12,this,this._el_23);
    var compView_23:any = import14.viewFactory_Button0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Button_23_4 = new import14.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_23),this.renderer);
    this._appEl_23.initComponent(this._Button_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_25,'name','add');
    this.renderer.setElementAttribute(this._el_25,'role','img');
    this._Icon_25_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText((null as any),'\n          ',(null as any));
      compView_23.create(this._Button_23_4.context,[([] as any[]).concat([
        this._text_24,
        this._el_25,
        this._text_26
      ]
    )],(null as any));
    this._text_27 = this.renderer.createText(this._el_12,'\n          ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_12,'button',(null as any));
    this.renderer.setElementAttribute(this._el_28,'class','button-qty pull-right');
    this.renderer.setElementAttribute(this._el_28,'color','primary');
    this.renderer.setElementAttribute(this._el_28,'ion-button','');
    this._appEl_28 = new import3.AppElement(28,12,this,this._el_28);
    var compView_28:any = import14.viewFactory_Button0(this.viewUtils,this.injector(28),this._appEl_28);
    this._Button_28_4 = new import14.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_28),this.renderer);
    this._appEl_28.initComponent(this._Button_28_4.context,([] as any[]),compView_28);
    this._text_29 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_30,'name','remove');
    this.renderer.setElementAttribute(this._el_30,'role','img');
    this._Icon_30_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText((null as any),'\n          ',(null as any));
      compView_28.create(this._Button_28_4.context,[([] as any[]).concat([
        this._text_29,
        this._el_30,
        this._text_31
      ]
    )],(null as any));
    this._text_32 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._query_Label_2_0.reset(([] as any[]));
    this._Item_2_4.context.contentLabel = this._query_Label_2_0.first;
    compView_2.create(this._Item_2_4.context,[
      ([] as any[]).concat([this._el_4]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._text_8,
        this._el_9,
        this._text_11,
        this._el_12,
        this._text_33
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_35 = this.renderer.createElement((null as any),'ion-item-options',(null as any));
    this._ItemOptions_35_3 = new import46.Wrapper_ItemOptions(new import25.ElementRef(this._el_35),this.renderer);
    this._text_36 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'button',(null as any));
    this.renderer.setElementAttribute(this._el_37,'ion-button','');
    this._appEl_37 = new import3.AppElement(37,35,this,this._el_37);
    var compView_37:any = import14.viewFactory_Button0(this.viewUtils,this.injector(37),this._appEl_37);
    this._Button_37_4 = new import14.Wrapper_Button((null as any),'',this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_37),this.renderer);
    this._appEl_37.initComponent(this._Button_37_4.context,([] as any[]),compView_37);
    this._text_38 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_39,'name','trash');
    this.renderer.setElementAttribute(this._el_39,'role','img');
    this._Icon_39_3 = new import18.Wrapper_Icon(this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_39),this.renderer);
    this._text_40 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_37.create(this._Button_37_4.context,[([] as any[]).concat([
        this._text_38,
        this._el_39,
        this._text_40
      ]
    )],(null as any));
    this._text_41 = this.renderer.createText(this._el_35,'\n      ',(null as any));
    this._text_42 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Item_0_0.reset([this._Item_2_4.context]);
    this._ItemSliding_0_4.context.item = this._query_Item_0_0.first;
    compView_0.create(this._ItemSliding_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]).concat([this._el_35])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    this._expr_12 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_37,'click',this.eventHandler(this._handle_click_37_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import50.Thumbnail) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Thumbnail_4_3.context; }
    if (((token === import45.Typography) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 17)))) { return this._Typography_16_3.context; }
    if (((token === import37.Icon) && (25 === requestNodeIndex))) { return this._Icon_25_3.context; }
    if (((token === import38.Button) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Button_23_4.context; }
    if (((token === import37.Icon) && (30 === requestNodeIndex))) { return this._Icon_30_3.context; }
    if (((token === import38.Button) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Button_28_4.context; }
    if (((token === import51.Item) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Item_2_4.context; }
    if (((token === import51.ItemContent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._ItemContent_2_5.context; }
    if (((token === import37.Icon) && (39 === requestNodeIndex))) { return this._Icon_39_3.context; }
    if (((token === import38.Button) && ((37 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Button_37_4.context; }
    if (((token === import52.ItemOptions) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ItemOptions_35_3.context; }
    if (((token === import52.ItemSliding) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 42)))) { return this._ItemSliding_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._ItemSliding_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    if (this._Item_2_4.detectChangesInternal(this,this._el_2,throwOnChange)) { this._appEl_2.componentView.markAsCheckOnce(); }
    this._ItemContent_2_5.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Thumbnail_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    const currVal_2:any = 'primary';
    this._Typography_16_3.check_color(currVal_2,throwOnChange,false);
    this._Typography_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_6:any = 'primary';
    this._Button_23_4.check_color(currVal_6,throwOnChange,false);
    if (this._Button_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    const currVal_7:any = 'add';
    this._Icon_25_3.check_name(currVal_7,throwOnChange,false);
    this._Icon_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_10:any = 'primary';
    this._Button_28_4.check_color(currVal_10,throwOnChange,false);
    if (this._Button_28_4.detectChangesInternal(this,this._el_28,throwOnChange)) { this._appEl_28.componentView.markAsCheckOnce(); }
    const currVal_11:any = 'remove';
    this._Icon_30_3.check_name(currVal_11,throwOnChange,false);
    this._Icon_30_3.detectChangesInternal(this,this._el_30,throwOnChange);
    this._ItemOptions_35_3.detectChangesInternal(this,this._el_35,throwOnChange);
    if (this._Button_37_4.detectChangesInternal(this,this._el_37,throwOnChange)) { this._appEl_37.componentView.markAsCheckOnce(); }
    const currVal_14:any = 'trash';
    this._Icon_39_3.check_name(currVal_14,throwOnChange,false);
    this._Icon_39_3.detectChangesInternal(this,this._el_39,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_2_1.dirty) {
        this._query_Button_2_1.reset([
          this._Button_23_4.context,
          this._Button_28_4.context
        ]
        );
        this._Item_2_4.context._buttons = this._query_Button_2_1;
        this._query_Button_2_1.notifyOnChanges();
      }
      if (this._query_Icon_2_2.dirty) {
        this._query_Icon_2_2.reset(([] as any[]));
        this._Item_2_4.context._icons = this._query_Icon_2_2;
        this._query_Icon_2_2.notifyOnChanges();
      }
      if (this._query_ItemOptions_0_1.dirty) {
        this._query_ItemOptions_0_1.reset([this._ItemOptions_35_3.context]);
        this._ItemSliding_0_4.context._itemOptions = this._query_ItemOptions_0_1;
        this._query_ItemOptions_0_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_23_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_28_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_2_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_37_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.thumb,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_6,'src',this.viewUtils.sanitizer.sanitize(import53.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = import4.interpolate(1,'$',this.context.$implicit.price,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_17,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,'x ',this.context.$implicit.quantity,'');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_20,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_8:any = this._Icon_25_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_25,'hide',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_12:any = this._Icon_30_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_30,'hide',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_15:any = this._Icon_39_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_39,'hide',currVal_15);
      this._expr_15 = currVal_15;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._Icon_25_3.context.ngOnDestroy();
    this._Icon_30_3.context.ngOnDestroy();
    this._Icon_39_3.context.ngOnDestroy();
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.plusQty(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.minusQty(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_37_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.remove(this.context.index)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_CartPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_CartPage1(viewUtils,parentInjector,declarationEl);
}