/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './news';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../services/post-service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import17 from '@angular/core/src/linker/query_list';
import * as import18 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from 'ionic-angular/config/config';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from 'ionic-angular/navigation/view-controller';
import * as import26 from 'ionic-angular/components/app/app';
import * as import27 from 'ionic-angular/components/menu/menu-controller';
import * as import28 from 'ionic-angular/components/toolbar/toolbar';
import * as import29 from 'ionic-angular/util/keyboard';
import * as import30 from '@angular/core/src/zone/ng_zone';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from 'ionic-angular/gestures/gesture-controller';
import * as import33 from '@angular/core/src/linker/template_ref';
import * as import34 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import35 from 'ionic-angular/components/icon/icon';
import * as import36 from 'ionic-angular/components/button/button';
import * as import37 from 'ionic-angular/components/menu/menu-toggle';
import * as import38 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from '@angular/common/src/directives/ng_for';
import * as import42 from 'ionic-angular/components/list/list';
import * as import43 from 'ionic-angular/components/content/content';
import * as import44 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import45 from '../../node_modules/ionic-angular/components/thumbnail/thumbnail.ngfactory';
import * as import46 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import47 from 'ionic-angular/util/form';
import * as import48 from 'ionic-angular/components/thumbnail/thumbnail';
import * as import49 from 'ionic-angular/components/typography/typography';
import * as import50 from 'ionic-angular/components/item/item';
import * as import51 from '@angular/core/src/security';
export class Wrapper_NewsPage {
  context:import0.NewsPage;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.NewsPage(p0,p1);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_NewsPage_Host:import2.RenderComponentType = (null as any);
class _View_NewsPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _NewsPage_0_4:Wrapper_NewsPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NewsPage_Host0,renderType_NewsPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-news',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NewsPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NewsPage_0_4 = new Wrapper_NewsPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.PostService));
    this._appEl_0.initComponent(this._NewsPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._NewsPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NewsPage) && (0 === requestNodeIndex))) { return this._NewsPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NewsPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NewsPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_NewsPage_Host === (null as any))) { (renderType_NewsPage_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_NewsPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const NewsPageNgFactory:import11.ComponentFactory<import0.NewsPage> = new import11.ComponentFactory<import0.NewsPage>('page-news',viewFactory_NewsPage_Host0,import0.NewsPage);
const styles_NewsPage:any[] = ([] as any[]);
var renderType_NewsPage:import2.RenderComponentType = (null as any);
class _View_NewsPage0 extends import1.AppView<import0.NewsPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import12.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import13.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import14.Wrapper_Button;
  _MenuToggle_5_5:import15.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import16.Wrapper_ToolbarItem;
  _query_Button_5_0:import17.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import18.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _ToolbarTitle_10_4:import19.Wrapper_ToolbarTitle;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _ToolbarItem_13_3:import16.Wrapper_ToolbarItem;
  _query_Button_13_0:import17.QueryList<any>;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Button_15_4:import14.Wrapper_Button;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import18.Wrapper_Icon;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Content_23_4:import20.Wrapper_Content;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _List_26_3:import21.Wrapper_List;
  _text_27:any;
  _anchor_28:any;
  /*private*/ _appEl_28:import3.AppElement;
  _TemplateRef_28_5:any;
  _NgFor_28_6:import22.Wrapper_NgFor;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NewsPage0,renderType_NewsPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import12.Wrapper_Header(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import25.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import13.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import13.Wrapper_Navbar(this.parentInjector.get(import26.App),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import14.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import14.Wrapper_Button('','',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import15.Wrapper_MenuToggle(this.parentInjector.get(import27.MenuController),new import24.ElementRef(this._el_5),this.parentInjector.get(import25.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import17.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import18.Wrapper_Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_10 = new import3.AppElement(10,3,this,this._el_10);
    var compView_10:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(10),this._appEl_10);
    this._ToolbarTitle_10_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_10.initComponent(this._ToolbarTitle_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'News',(null as any));
    compView_10.create(this._ToolbarTitle_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_13,'end','');
    this._ToolbarItem_13_3 = new import16.Wrapper_ToolbarItem(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import28.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_13_0 = new import17.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'ion-button','');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import14.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import14.Wrapper_Button((null as any),'',this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._Button_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_17,'name','md-more');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import18.Wrapper_Icon(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_15.create(this._Button_15_4.context,[([] as any[]).concat([
        this._text_16,
        this._el_17,
        this._text_18
      ]
    )],(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]),
      ([] as any[]).concat([this._el_13]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._el_10,
        this._text_12,
        this._text_20
      ]
      )
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_23 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_23 = new import3.AppElement(23,(null as any),this,this._el_23);
    var compView_23:any = import20.viewFactory_Content0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Content_23_4 = new import20.Wrapper_Content(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import26.App),this.parentInjector.get(import29.Keyboard),this.parentInjector.get(import30.NgZone),this.parentInjector.get(import25.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_23.initComponent(this._Content_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_25 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','list-full-border');
    this._List_26_3 = new import21.Wrapper_List(this.parentInjector.get(import23.Config),new import24.ElementRef(this._el_26),this.renderer,this.parentInjector.get(import32.GestureController));
    this._text_27 = this.renderer.createText(this._el_26,'\n    ',(null as any));
    this._anchor_28 = this.renderer.createTemplateAnchor(this._el_26,(null as any));
    this._appEl_28 = new import3.AppElement(28,26,this,this._anchor_28);
    this._TemplateRef_28_5 = new import33.TemplateRef_(this._appEl_28,viewFactory_NewsPage1);
    this._NgFor_28_6 = new import22.Wrapper_NgFor(this._appEl_28.vcRef,this._TemplateRef_28_5,this.parentInjector.get(import34.IterableDiffers),this.ref);
    this._text_29 = this.renderer.createText(this._el_26,'\n  ',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n',(null as any));
    compView_23.create(this._Content_23_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._text_25,
        this._el_26,
        this._text_30
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_31 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._anchor_28,
      this._text_29,
      this._text_30,
      this._text_31
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import35.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import36.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import37.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import38.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import39.ToolbarTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarTitle_10_4.context; }
    if (((token === import35.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3.context; }
    if (((token === import36.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_15_4.context; }
    if (((token === import38.ToolbarItem) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ToolbarItem_13_3.context; }
    if (((token === import40.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Navbar_3_4.context; }
    if (((token === import28.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Header_1_3.context; }
    if (((token === import33.TemplateRef) && (28 === requestNodeIndex))) { return this._TemplateRef_28_5; }
    if (((token === import41.NgFor) && (28 === requestNodeIndex))) { return this._NgFor_28_6.context; }
    if (((token === import42.List) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._List_26_3.context; }
    if (((token === import43.Content) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._Content_23_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_7_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._ToolbarTitle_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._ToolbarItem_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    if (this._Button_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'md-more';
    this._Icon_17_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    if (this._Content_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    this._List_26_3.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_11:any = this.context.posts;
    this._NgFor_28_6.check_ngForOf(currVal_11,throwOnChange,false);
    this._NgFor_28_6.detectChangesInternal(this,this._anchor_28,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_13_0.dirty) {
        this._query_Button_13_0.reset([this._Button_15_4.context]);
        this._ToolbarItem_13_3.context._buttons = this._query_Button_13_0;
        this._query_Button_13_0.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = this._Icon_17_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_17,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_23_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Icon_17_3.context.ngOnDestroy();
    this._Content_23_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_NewsPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.NewsPage> {
  if ((renderType_NewsPage === (null as any))) { (renderType_NewsPage = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_NewsPage,{})); }
  return new _View_NewsPage0(viewUtils,parentInjector,declarationEl);
}
class _View_NewsPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import44.Wrapper_Item;
  _ItemContent_0_5:import44.Wrapper_ItemContent;
  _query_Label_0_0:import17.QueryList<any>;
  _query_Button_0_1:import17.QueryList<any>;
  _query_Icon_0_2:import17.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _Thumbnail_2_3:import45.Wrapper_Thumbnail;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _Typography_12_3:import46.Wrapper_Typography;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_NewsPage1,renderType_NewsPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this.renderer.setElementAttribute(this._el_0,'text-wrap','');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import44.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import44.Wrapper_Item(this.parent.parentInjector.get(import47.Form),this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import44.Wrapper_ItemContent();
    this._query_Label_0_0 = new import17.QueryList<any>();
    this._query_Button_0_1 = new import17.QueryList<any>();
    this._query_Icon_0_2 = new import17.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'ion-thumbnail',(null as any));
    this.renderer.setElementAttribute(this._el_2,'item-left','');
    this._Thumbnail_2_3 = new import45.Wrapper_Thumbnail();
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'img',(null as any));
    this.renderer.setElementAttribute(this._el_4,'alt','');
    this._text_5 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_9 = this.renderer.createElement(this._el_7,'div',(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n        ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_7,'p',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','text-sm');
    this.renderer.setElementAttribute(this._el_12,'color','light-dark');
    this._Typography_12_3 = new import46.Wrapper_Typography(this.parent.parentInjector.get(import23.Config),new import24.ElementRef(this._el_12),this.renderer);
    this._text_13 = this.renderer.createText(this._el_12,'',(null as any));
    this._text_14 = this.renderer.createText(this._el_7,'\n      ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]).concat([this._el_2]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._text_6,
        this._el_7,
        this._text_15
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import48.Thumbnail) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._Thumbnail_2_3.context; }
    if (((token === import49.Typography) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Typography_12_3.context; }
    if (((token === import50.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Item_0_4.context; }
    if (((token === import50.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Thumbnail_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    const currVal_2:any = 'light-dark';
    this._Typography_12_3.check_color(currVal_2,throwOnChange,false);
    this._Typography_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.thumb,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_4,'src',this.viewUtils.sanitizer.sanitize(import51.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_10,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.desc,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_13,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NewsPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_NewsPage1(viewUtils,parentInjector,declarationEl);
}