/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './about';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import22 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/components/menu/menu-controller';
import * as import29 from 'ionic-angular/components/toolbar/toolbar';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from 'ionic-angular/gestures/gesture-controller';
import * as import34 from '@angular/core/src/linker/template_ref';
import * as import35 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from 'ionic-angular/components/icon/icon';
import * as import38 from 'ionic-angular/components/button/button';
import * as import39 from 'ionic-angular/components/menu/menu-toggle';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import41 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import42 from 'ionic-angular/components/navbar/navbar';
import * as import43 from 'ionic-angular/components/typography/typography';
import * as import44 from '@angular/common/src/directives/ng_for';
import * as import45 from 'ionic-angular/components/list/list';
import * as import46 from 'ionic-angular/components/item/item';
import * as import47 from 'ionic-angular/components/content/content';
export class Wrapper_AboutPage {
  context:import0.AboutPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.AboutPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_AboutPage_Host:import2.RenderComponentType = (null as any);
class _View_AboutPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AboutPage_0_4:Wrapper_AboutPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AboutPage_Host0,renderType_AboutPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-about',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AboutPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AboutPage_0_4 = new Wrapper_AboutPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._AboutPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AboutPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AboutPage) && (0 === requestNodeIndex))) { return this._AboutPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AboutPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AboutPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AboutPage_Host === (null as any))) { (renderType_AboutPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AboutPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const AboutPageNgFactory:import10.ComponentFactory<import0.AboutPage> = new import10.ComponentFactory<import0.AboutPage>('page-about',viewFactory_AboutPage_Host0,import0.AboutPage);
const styles_AboutPage:any[] = ([] as any[]);
var renderType_AboutPage:import2.RenderComponentType = (null as any);
class _View_AboutPage0 extends import1.AppView<import0.AboutPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import12.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import13.Wrapper_Button;
  _MenuToggle_5_5:import14.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import15.Wrapper_ToolbarItem;
  _query_Button_5_0:import16.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import17.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _ToolbarTitle_10_4:import18.Wrapper_ToolbarTitle;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _ToolbarItem_13_3:import15.Wrapper_ToolbarItem;
  _query_Button_13_0:import16.QueryList<any>;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Button_15_4:import13.Wrapper_Button;
  _text_16:any;
  _el_17:any;
  _Icon_17_3:import17.Wrapper_Icon;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _Content_23_4:import19.Wrapper_Content;
  _text_24:any;
  _el_25:any;
  _Typography_25_3:import20.Wrapper_Typography;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _Typography_28_3:import20.Wrapper_Typography;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _Typography_34_3:import20.Wrapper_Typography;
  _text_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _text_39:any;
  _el_40:any;
  _List_40_3:import21.Wrapper_List;
  _text_41:any;
  _anchor_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _TemplateRef_42_5:any;
  _NgFor_42_6:import22.Wrapper_NgFor;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _List_48_3:import21.Wrapper_List;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Item_50_4:import23.Wrapper_Item;
  _ItemContent_50_5:import23.Wrapper_ItemContent;
  _query_Label_50_0:import16.QueryList<any>;
  _query_Button_50_1:import16.QueryList<any>;
  _query_Icon_50_2:import16.QueryList<any>;
  _text_51:any;
  _el_52:any;
  _Icon_52_3:import17.Wrapper_Icon;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  /*private*/ _appEl_55:import3.AppElement;
  _Item_55_4:import23.Wrapper_Item;
  _ItemContent_55_5:import23.Wrapper_ItemContent;
  _query_Label_55_0:import16.QueryList<any>;
  _query_Button_55_1:import16.QueryList<any>;
  _query_Icon_55_2:import16.QueryList<any>;
  _text_56:any;
  _el_57:any;
  _Icon_57_3:import17.Wrapper_Icon;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  /*private*/ _appEl_60:import3.AppElement;
  _Item_60_4:import23.Wrapper_Item;
  _ItemContent_60_5:import23.Wrapper_ItemContent;
  _query_Label_60_0:import16.QueryList<any>;
  _query_Button_60_1:import16.QueryList<any>;
  _query_Icon_60_2:import16.QueryList<any>;
  _text_61:any;
  _el_62:any;
  _Icon_62_3:import17.Wrapper_Icon;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _List_69_3:import21.Wrapper_List;
  _text_70:any;
  _el_71:any;
  /*private*/ _appEl_71:import3.AppElement;
  _Item_71_4:import23.Wrapper_Item;
  _ItemContent_71_5:import23.Wrapper_ItemContent;
  _query_Label_71_0:import16.QueryList<any>;
  _query_Button_71_1:import16.QueryList<any>;
  _query_Icon_71_2:import16.QueryList<any>;
  _text_72:any;
  _el_73:any;
  _Icon_73_3:import17.Wrapper_Icon;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  /*private*/ _appEl_76:import3.AppElement;
  _Item_76_4:import23.Wrapper_Item;
  _ItemContent_76_5:import23.Wrapper_ItemContent;
  _query_Label_76_0:import16.QueryList<any>;
  _query_Button_76_1:import16.QueryList<any>;
  _query_Icon_76_2:import16.QueryList<any>;
  _text_77:any;
  _el_78:any;
  _Icon_78_3:import17.Wrapper_Icon;
  _text_79:any;
  _text_80:any;
  _el_81:any;
  /*private*/ _appEl_81:import3.AppElement;
  _Item_81_4:import23.Wrapper_Item;
  _ItemContent_81_5:import23.Wrapper_ItemContent;
  _query_Label_81_0:import16.QueryList<any>;
  _query_Button_81_1:import16.QueryList<any>;
  _query_Icon_81_2:import16.QueryList<any>;
  _text_82:any;
  _el_83:any;
  _Icon_83_3:import17.Wrapper_Icon;
  _text_84:any;
  _text_85:any;
  _el_86:any;
  /*private*/ _appEl_86:import3.AppElement;
  _Item_86_4:import23.Wrapper_Item;
  _ItemContent_86_5:import23.Wrapper_ItemContent;
  _query_Label_86_0:import16.QueryList<any>;
  _query_Button_86_1:import16.QueryList<any>;
  _query_Icon_86_2:import16.QueryList<any>;
  _text_87:any;
  _el_88:any;
  _Icon_88_3:import17.Wrapper_Icon;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_28:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AboutPage0,renderType_AboutPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import27.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import13.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import13.Wrapper_Button('','',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import14.Wrapper_MenuToggle(this.parentInjector.get(import28.MenuController),new import25.ElementRef(this._el_5),this.parentInjector.get(import26.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import15.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import16.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_10 = new import3.AppElement(10,3,this,this._el_10);
    var compView_10:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(10),this._appEl_10);
    this._ToolbarTitle_10_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_10.initComponent(this._ToolbarTitle_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'About',(null as any));
    compView_10.create(this._ToolbarTitle_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'ion-buttons',(null as any));
    this.renderer.setElementAttribute(this._el_13,'end','');
    this._ToolbarItem_13_3 = new import15.Wrapper_ToolbarItem(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_13),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_13_0 = new import16.QueryList<any>();
    this._text_14 = this.renderer.createText(this._el_13,'\n      ',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_15,'ion-button','');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import13.viewFactory_Button0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Button_15_4 = new import13.Wrapper_Button((null as any),'',this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_15),this.renderer);
    this._appEl_15.initComponent(this._Button_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_17,'name','md-more');
    this.renderer.setElementAttribute(this._el_17,'role','img');
    this._Icon_17_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_17),this.renderer);
    this._text_18 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_15.create(this._Button_15_4.context,[([] as any[]).concat([
        this._text_16,
        this._el_17,
        this._text_18
      ]
    )],(null as any));
    this._text_19 = this.renderer.createText(this._el_13,'\n    ',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]),
      ([] as any[]).concat([this._el_13]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._el_10,
        this._text_12,
        this._text_20
      ]
      )
    ]
    ,(null as any));
    this._text_21 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_22 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_23 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_23,'class','about gray-bg');
    this.renderer.setElementAttribute(this._el_23,'padding','');
    this._appEl_23 = new import3.AppElement(23,(null as any),this,this._el_23);
    var compView_23:any = import19.viewFactory_Content0(this.viewUtils,this.injector(23),this._appEl_23);
    this._Content_23_4 = new import19.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_23),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_23.initComponent(this._Content_23_4.context,([] as any[]),compView_23);
    this._text_24 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'h2',(null as any));
    this.renderer.setElementAttribute(this._el_25,'color','dark');
    this._Typography_25_3 = new import20.Wrapper_Typography(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_25),this.renderer);
    this._text_26 = this.renderer.createText(this._el_25,'El Gaucho restaurant ',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_28,'color','dark');
    this._Typography_28_3 = new import20.Wrapper_Typography(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText(this._el_28,'225 Valencia St, San Francisco, CA',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,'About us',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_34,'color','dark');
    this._Typography_34_3 = new import20.Wrapper_Typography(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_34),this.renderer);
    this._text_35 = this.renderer.createText(this._el_34,'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the\n    industry\'s\n    standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make\n    a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting,\n    remaining essentially unchanged',(null as any));
    this._text_36 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_37 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'Open hours',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_40,'class','list-full-border');
    this._List_40_3 = new import21.Wrapper_List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_40),this.renderer,this.parentInjector.get(import33.GestureController));
    this._text_41 = this.renderer.createText(this._el_40,'\n    ',(null as any));
    this._anchor_42 = this.renderer.createTemplateAnchor(this._el_40,(null as any));
    this._appEl_42 = new import3.AppElement(42,40,this,this._anchor_42);
    this._TemplateRef_42_5 = new import34.TemplateRef_(this._appEl_42,viewFactory_AboutPage1);
    this._NgFor_42_6 = new import22.Wrapper_NgFor(this._appEl_42.vcRef,this._TemplateRef_42_5,this.parentInjector.get(import35.IterableDiffers),this.ref);
    this._text_43 = this.renderer.createText(this._el_40,'\n  ',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'h3',(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Get in touch',(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_48,'class','list-full-border');
    this._List_48_3 = new import21.Wrapper_List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_48),this.renderer,this.parentInjector.get(import33.GestureController));
    this._text_49 = this.renderer.createText(this._el_48,'\n    ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','item item-block');
    this._appEl_50 = new import3.AppElement(50,48,this,this._el_50);
    var compView_50:any = import23.viewFactory_Item0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Item_50_4 = new import23.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_50),this.renderer);
    this._ItemContent_50_5 = new import23.Wrapper_ItemContent();
    this._query_Label_50_0 = new import16.QueryList<any>();
    this._query_Button_50_1 = new import16.QueryList<any>();
    this._query_Icon_50_2 = new import16.QueryList<any>();
    this._appEl_50.initComponent(this._Item_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_52 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_52,'item-left','');
    this.renderer.setElementAttribute(this._el_52,'name','call');
    this.renderer.setElementAttribute(this._el_52,'role','img');
    this._Icon_52_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_52),this.renderer);
    this._text_53 = this.renderer.createText((null as any),'\n      Call us\n    ',(null as any));
    this._query_Label_50_0.reset(([] as any[]));
    this._Item_50_4.context.contentLabel = this._query_Label_50_0.first;
    compView_50.create(this._Item_50_4.context,[
      ([] as any[]).concat([this._el_52]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_51,
        this._text_53
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_54 = this.renderer.createText(this._el_48,'\n    ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_48,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_55,'class','item item-block');
    this._appEl_55 = new import3.AppElement(55,48,this,this._el_55);
    var compView_55:any = import23.viewFactory_Item0(this.viewUtils,this.injector(55),this._appEl_55);
    this._Item_55_4 = new import23.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_55),this.renderer);
    this._ItemContent_55_5 = new import23.Wrapper_ItemContent();
    this._query_Label_55_0 = new import16.QueryList<any>();
    this._query_Button_55_1 = new import16.QueryList<any>();
    this._query_Icon_55_2 = new import16.QueryList<any>();
    this._appEl_55.initComponent(this._Item_55_4.context,([] as any[]),compView_55);
    this._text_56 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_57 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_57,'item-left','');
    this.renderer.setElementAttribute(this._el_57,'name','mail');
    this.renderer.setElementAttribute(this._el_57,'role','img');
    this._Icon_57_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_57),this.renderer);
    this._text_58 = this.renderer.createText((null as any),'\n      Send us and Email\n    ',(null as any));
    this._query_Label_55_0.reset(([] as any[]));
    this._Item_55_4.context.contentLabel = this._query_Label_55_0.first;
    compView_55.create(this._Item_55_4.context,[
      ([] as any[]).concat([this._el_57]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_56,
        this._text_58
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_59 = this.renderer.createText(this._el_48,'\n    ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_48,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','item item-block');
    this._appEl_60 = new import3.AppElement(60,48,this,this._el_60);
    var compView_60:any = import23.viewFactory_Item0(this.viewUtils,this.injector(60),this._appEl_60);
    this._Item_60_4 = new import23.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_60),this.renderer);
    this._ItemContent_60_5 = new import23.Wrapper_ItemContent();
    this._query_Label_60_0 = new import16.QueryList<any>();
    this._query_Button_60_1 = new import16.QueryList<any>();
    this._query_Icon_60_2 = new import16.QueryList<any>();
    this._appEl_60.initComponent(this._Item_60_4.context,([] as any[]),compView_60);
    this._text_61 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_62,'item-left','');
    this.renderer.setElementAttribute(this._el_62,'name','navigate');
    this.renderer.setElementAttribute(this._el_62,'role','img');
    this._Icon_62_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_62),this.renderer);
    this._text_63 = this.renderer.createText((null as any),'\n      Find us / Get directions\n    ',(null as any));
    this._query_Label_60_0.reset(([] as any[]));
    this._Item_60_4.context.contentLabel = this._query_Label_60_0.first;
    compView_60.create(this._Item_60_4.context,[
      ([] as any[]).concat([this._el_62]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_61,
        this._text_63
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_64 = this.renderer.createText(this._el_48,'\n  ',(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._el_66 = this.renderer.createElement((null as any),'h4',(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'Get social with us',(null as any));
    this._text_68 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_69 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_69,'class','list-full-border');
    this._List_69_3 = new import21.Wrapper_List(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_69),this.renderer,this.parentInjector.get(import33.GestureController));
    this._text_70 = this.renderer.createText(this._el_69,'\n    ',(null as any));
    this._el_71 = this.renderer.createElement(this._el_69,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_71,'class','item item-block');
    this._appEl_71 = new import3.AppElement(71,69,this,this._el_71);
    var compView_71:any = import23.viewFactory_Item0(this.viewUtils,this.injector(71),this._appEl_71);
    this._Item_71_4 = new import23.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_71),this.renderer);
    this._ItemContent_71_5 = new import23.Wrapper_ItemContent();
    this._query_Label_71_0 = new import16.QueryList<any>();
    this._query_Button_71_1 = new import16.QueryList<any>();
    this._query_Icon_71_2 = new import16.QueryList<any>();
    this._appEl_71.initComponent(this._Item_71_4.context,([] as any[]),compView_71);
    this._text_72 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_73 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_73,'item-left','');
    this.renderer.setElementAttribute(this._el_73,'name','logo-facebook');
    this.renderer.setElementAttribute(this._el_73,'role','img');
    this._Icon_73_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_73),this.renderer);
    this._text_74 = this.renderer.createText((null as any),'\n      Visit us on Facebook\n    ',(null as any));
    this._query_Label_71_0.reset(([] as any[]));
    this._Item_71_4.context.contentLabel = this._query_Label_71_0.first;
    compView_71.create(this._Item_71_4.context,[
      ([] as any[]).concat([this._el_73]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_72,
        this._text_74
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_75 = this.renderer.createText(this._el_69,'\n    ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_69,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_76,'class','item item-block');
    this._appEl_76 = new import3.AppElement(76,69,this,this._el_76);
    var compView_76:any = import23.viewFactory_Item0(this.viewUtils,this.injector(76),this._appEl_76);
    this._Item_76_4 = new import23.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_76),this.renderer);
    this._ItemContent_76_5 = new import23.Wrapper_ItemContent();
    this._query_Label_76_0 = new import16.QueryList<any>();
    this._query_Button_76_1 = new import16.QueryList<any>();
    this._query_Icon_76_2 = new import16.QueryList<any>();
    this._appEl_76.initComponent(this._Item_76_4.context,([] as any[]),compView_76);
    this._text_77 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_78 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_78,'item-left','');
    this.renderer.setElementAttribute(this._el_78,'name','logo-instagram');
    this.renderer.setElementAttribute(this._el_78,'role','img');
    this._Icon_78_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_78),this.renderer);
    this._text_79 = this.renderer.createText((null as any),'\n      Follow us on Instagram\n    ',(null as any));
    this._query_Label_76_0.reset(([] as any[]));
    this._Item_76_4.context.contentLabel = this._query_Label_76_0.first;
    compView_76.create(this._Item_76_4.context,[
      ([] as any[]).concat([this._el_78]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_77,
        this._text_79
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_80 = this.renderer.createText(this._el_69,'\n    ',(null as any));
    this._el_81 = this.renderer.createElement(this._el_69,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_81,'class','item item-block');
    this._appEl_81 = new import3.AppElement(81,69,this,this._el_81);
    var compView_81:any = import23.viewFactory_Item0(this.viewUtils,this.injector(81),this._appEl_81);
    this._Item_81_4 = new import23.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_81),this.renderer);
    this._ItemContent_81_5 = new import23.Wrapper_ItemContent();
    this._query_Label_81_0 = new import16.QueryList<any>();
    this._query_Button_81_1 = new import16.QueryList<any>();
    this._query_Icon_81_2 = new import16.QueryList<any>();
    this._appEl_81.initComponent(this._Item_81_4.context,([] as any[]),compView_81);
    this._text_82 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_83 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_83,'item-left','');
    this.renderer.setElementAttribute(this._el_83,'name','logo-twitter');
    this.renderer.setElementAttribute(this._el_83,'role','img');
    this._Icon_83_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_83),this.renderer);
    this._text_84 = this.renderer.createText((null as any),'\n      Follow us on Twitter\n    ',(null as any));
    this._query_Label_81_0.reset(([] as any[]));
    this._Item_81_4.context.contentLabel = this._query_Label_81_0.first;
    compView_81.create(this._Item_81_4.context,[
      ([] as any[]).concat([this._el_83]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_82,
        this._text_84
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_85 = this.renderer.createText(this._el_69,'\n    ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_69,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_86,'class','item item-block');
    this._appEl_86 = new import3.AppElement(86,69,this,this._el_86);
    var compView_86:any = import23.viewFactory_Item0(this.viewUtils,this.injector(86),this._appEl_86);
    this._Item_86_4 = new import23.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_86),this.renderer);
    this._ItemContent_86_5 = new import23.Wrapper_ItemContent();
    this._query_Label_86_0 = new import16.QueryList<any>();
    this._query_Button_86_1 = new import16.QueryList<any>();
    this._query_Icon_86_2 = new import16.QueryList<any>();
    this._appEl_86.initComponent(this._Item_86_4.context,([] as any[]),compView_86);
    this._text_87 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_88 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_88,'item-left','');
    this.renderer.setElementAttribute(this._el_88,'name','logo-pinterest');
    this.renderer.setElementAttribute(this._el_88,'role','img');
    this._Icon_88_3 = new import17.Wrapper_Icon(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_88),this.renderer);
    this._text_89 = this.renderer.createText((null as any),'\n      Follow us on Pinterest\n    ',(null as any));
    this._query_Label_86_0.reset(([] as any[]));
    this._Item_86_4.context.contentLabel = this._query_Label_86_0.first;
    compView_86.create(this._Item_86_4.context,[
      ([] as any[]).concat([this._el_88]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_87,
        this._text_89
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_90 = this.renderer.createText(this._el_69,'\n  ',(null as any));
    this._text_91 = this.renderer.createText((null as any),'\n',(null as any));
    compView_23.create(this._Content_23_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_24,
        this._el_25,
        this._text_27,
        this._el_28,
        this._text_30,
        this._el_31,
        this._text_33,
        this._el_34,
        this._text_36,
        this._el_37,
        this._text_39,
        this._el_40,
        this._text_44,
        this._el_45,
        this._text_47,
        this._el_48,
        this._text_65,
        this._el_66,
        this._text_68,
        this._el_69,
        this._text_91
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_92 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._anchor_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._text_92
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import38.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import39.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import40.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import41.ToolbarTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarTitle_10_4.context; }
    if (((token === import37.Icon) && (17 === requestNodeIndex))) { return this._Icon_17_3.context; }
    if (((token === import38.Button) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Button_15_4.context; }
    if (((token === import40.ToolbarItem) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._ToolbarItem_13_3.context; }
    if (((token === import42.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Navbar_3_4.context; }
    if (((token === import29.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Header_1_3.context; }
    if (((token === import43.Typography) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Typography_25_3.context; }
    if (((token === import43.Typography) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Typography_28_3.context; }
    if (((token === import43.Typography) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Typography_34_3.context; }
    if (((token === import34.TemplateRef) && (42 === requestNodeIndex))) { return this._TemplateRef_42_5; }
    if (((token === import44.NgFor) && (42 === requestNodeIndex))) { return this._NgFor_42_6.context; }
    if (((token === import45.List) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._List_40_3.context; }
    if (((token === import37.Icon) && (52 === requestNodeIndex))) { return this._Icon_52_3.context; }
    if (((token === import46.Item) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Item_50_4.context; }
    if (((token === import46.ItemContent) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._ItemContent_50_5.context; }
    if (((token === import37.Icon) && (57 === requestNodeIndex))) { return this._Icon_57_3.context; }
    if (((token === import46.Item) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Item_55_4.context; }
    if (((token === import46.ItemContent) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._ItemContent_55_5.context; }
    if (((token === import37.Icon) && (62 === requestNodeIndex))) { return this._Icon_62_3.context; }
    if (((token === import46.Item) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Item_60_4.context; }
    if (((token === import46.ItemContent) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._ItemContent_60_5.context; }
    if (((token === import45.List) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._List_48_3.context; }
    if (((token === import37.Icon) && (73 === requestNodeIndex))) { return this._Icon_73_3.context; }
    if (((token === import46.Item) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._Item_71_4.context; }
    if (((token === import46.ItemContent) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 74)))) { return this._ItemContent_71_5.context; }
    if (((token === import37.Icon) && (78 === requestNodeIndex))) { return this._Icon_78_3.context; }
    if (((token === import46.Item) && ((76 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._Item_76_4.context; }
    if (((token === import46.ItemContent) && ((76 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._ItemContent_76_5.context; }
    if (((token === import37.Icon) && (83 === requestNodeIndex))) { return this._Icon_83_3.context; }
    if (((token === import46.Item) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._Item_81_4.context; }
    if (((token === import46.ItemContent) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._ItemContent_81_5.context; }
    if (((token === import37.Icon) && (88 === requestNodeIndex))) { return this._Icon_88_3.context; }
    if (((token === import46.Item) && ((86 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._Item_86_4.context; }
    if (((token === import46.ItemContent) && ((86 <= requestNodeIndex) && (requestNodeIndex <= 89)))) { return this._ItemContent_86_5.context; }
    if (((token === import45.List) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 90)))) { return this._List_69_3.context; }
    if (((token === import47.Content) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 91)))) { return this._Content_23_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_7_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._ToolbarTitle_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this._ToolbarItem_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    if (this._Button_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    const currVal_8:any = 'md-more';
    this._Icon_17_3.check_name(currVal_8,throwOnChange,false);
    this._Icon_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    if (this._Content_23_4.detectChangesInternal(this,this._el_23,throwOnChange)) { this._appEl_23.componentView.markAsCheckOnce(); }
    const currVal_11:any = 'dark';
    this._Typography_25_3.check_color(currVal_11,throwOnChange,false);
    this._Typography_25_3.detectChangesInternal(this,this._el_25,throwOnChange);
    const currVal_12:any = 'dark';
    this._Typography_28_3.check_color(currVal_12,throwOnChange,false);
    this._Typography_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_13:any = 'dark';
    this._Typography_34_3.check_color(currVal_13,throwOnChange,false);
    this._Typography_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    this._List_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    const currVal_14:any = this.context.days;
    this._NgFor_42_6.check_ngForOf(currVal_14,throwOnChange,false);
    this._NgFor_42_6.detectChangesInternal(this,this._anchor_42,throwOnChange);
    this._List_48_3.detectChangesInternal(this,this._el_48,throwOnChange);
    if (this._Item_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    this._ItemContent_50_5.detectChangesInternal(this,this._el_50,throwOnChange);
    const currVal_15:any = 'call';
    this._Icon_52_3.check_name(currVal_15,throwOnChange,false);
    this._Icon_52_3.detectChangesInternal(this,this._el_52,throwOnChange);
    if (this._Item_55_4.detectChangesInternal(this,this._el_55,throwOnChange)) { this._appEl_55.componentView.markAsCheckOnce(); }
    this._ItemContent_55_5.detectChangesInternal(this,this._el_55,throwOnChange);
    const currVal_17:any = 'mail';
    this._Icon_57_3.check_name(currVal_17,throwOnChange,false);
    this._Icon_57_3.detectChangesInternal(this,this._el_57,throwOnChange);
    if (this._Item_60_4.detectChangesInternal(this,this._el_60,throwOnChange)) { this._appEl_60.componentView.markAsCheckOnce(); }
    this._ItemContent_60_5.detectChangesInternal(this,this._el_60,throwOnChange);
    const currVal_19:any = 'navigate';
    this._Icon_62_3.check_name(currVal_19,throwOnChange,false);
    this._Icon_62_3.detectChangesInternal(this,this._el_62,throwOnChange);
    this._List_69_3.detectChangesInternal(this,this._el_69,throwOnChange);
    if (this._Item_71_4.detectChangesInternal(this,this._el_71,throwOnChange)) { this._appEl_71.componentView.markAsCheckOnce(); }
    this._ItemContent_71_5.detectChangesInternal(this,this._el_71,throwOnChange);
    const currVal_21:any = 'logo-facebook';
    this._Icon_73_3.check_name(currVal_21,throwOnChange,false);
    this._Icon_73_3.detectChangesInternal(this,this._el_73,throwOnChange);
    if (this._Item_76_4.detectChangesInternal(this,this._el_76,throwOnChange)) { this._appEl_76.componentView.markAsCheckOnce(); }
    this._ItemContent_76_5.detectChangesInternal(this,this._el_76,throwOnChange);
    const currVal_23:any = 'logo-instagram';
    this._Icon_78_3.check_name(currVal_23,throwOnChange,false);
    this._Icon_78_3.detectChangesInternal(this,this._el_78,throwOnChange);
    if (this._Item_81_4.detectChangesInternal(this,this._el_81,throwOnChange)) { this._appEl_81.componentView.markAsCheckOnce(); }
    this._ItemContent_81_5.detectChangesInternal(this,this._el_81,throwOnChange);
    const currVal_25:any = 'logo-twitter';
    this._Icon_83_3.check_name(currVal_25,throwOnChange,false);
    this._Icon_83_3.detectChangesInternal(this,this._el_83,throwOnChange);
    if (this._Item_86_4.detectChangesInternal(this,this._el_86,throwOnChange)) { this._appEl_86.componentView.markAsCheckOnce(); }
    this._ItemContent_86_5.detectChangesInternal(this,this._el_86,throwOnChange);
    const currVal_27:any = 'logo-pinterest';
    this._Icon_88_3.check_name(currVal_27,throwOnChange,false);
    this._Icon_88_3.detectChangesInternal(this,this._el_88,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_13_0.dirty) {
        this._query_Button_13_0.reset([this._Button_15_4.context]);
        this._ToolbarItem_13_3.context._buttons = this._query_Button_13_0;
        this._query_Button_13_0.notifyOnChanges();
      }
      if (this._query_Button_50_1.dirty) {
        this._query_Button_50_1.reset(([] as any[]));
        this._Item_50_4.context._buttons = this._query_Button_50_1;
        this._query_Button_50_1.notifyOnChanges();
      }
      if (this._query_Icon_50_2.dirty) {
        this._query_Icon_50_2.reset([this._Icon_52_3.context]);
        this._Item_50_4.context._icons = this._query_Icon_50_2;
        this._query_Icon_50_2.notifyOnChanges();
      }
      if (this._query_Button_55_1.dirty) {
        this._query_Button_55_1.reset(([] as any[]));
        this._Item_55_4.context._buttons = this._query_Button_55_1;
        this._query_Button_55_1.notifyOnChanges();
      }
      if (this._query_Icon_55_2.dirty) {
        this._query_Icon_55_2.reset([this._Icon_57_3.context]);
        this._Item_55_4.context._icons = this._query_Icon_55_2;
        this._query_Icon_55_2.notifyOnChanges();
      }
      if (this._query_Button_60_1.dirty) {
        this._query_Button_60_1.reset(([] as any[]));
        this._Item_60_4.context._buttons = this._query_Button_60_1;
        this._query_Button_60_1.notifyOnChanges();
      }
      if (this._query_Icon_60_2.dirty) {
        this._query_Icon_60_2.reset([this._Icon_62_3.context]);
        this._Item_60_4.context._icons = this._query_Icon_60_2;
        this._query_Icon_60_2.notifyOnChanges();
      }
      if (this._query_Button_71_1.dirty) {
        this._query_Button_71_1.reset(([] as any[]));
        this._Item_71_4.context._buttons = this._query_Button_71_1;
        this._query_Button_71_1.notifyOnChanges();
      }
      if (this._query_Icon_71_2.dirty) {
        this._query_Icon_71_2.reset([this._Icon_73_3.context]);
        this._Item_71_4.context._icons = this._query_Icon_71_2;
        this._query_Icon_71_2.notifyOnChanges();
      }
      if (this._query_Button_76_1.dirty) {
        this._query_Button_76_1.reset(([] as any[]));
        this._Item_76_4.context._buttons = this._query_Button_76_1;
        this._query_Button_76_1.notifyOnChanges();
      }
      if (this._query_Icon_76_2.dirty) {
        this._query_Icon_76_2.reset([this._Icon_78_3.context]);
        this._Item_76_4.context._icons = this._query_Icon_76_2;
        this._query_Icon_76_2.notifyOnChanges();
      }
      if (this._query_Button_81_1.dirty) {
        this._query_Button_81_1.reset(([] as any[]));
        this._Item_81_4.context._buttons = this._query_Button_81_1;
        this._query_Button_81_1.notifyOnChanges();
      }
      if (this._query_Icon_81_2.dirty) {
        this._query_Icon_81_2.reset([this._Icon_83_3.context]);
        this._Item_81_4.context._icons = this._query_Icon_81_2;
        this._query_Icon_81_2.notifyOnChanges();
      }
      if (this._query_Button_86_1.dirty) {
        this._query_Button_86_1.reset(([] as any[]));
        this._Item_86_4.context._buttons = this._query_Button_86_1;
        this._query_Button_86_1.notifyOnChanges();
      }
      if (this._query_Icon_86_2.dirty) {
        this._query_Icon_86_2.reset([this._Icon_88_3.context]);
        this._Item_86_4.context._icons = this._query_Icon_86_2;
        this._query_Icon_86_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_50_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_55_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_60_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_71_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_76_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_81_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_86_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_9:any = this._Icon_17_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_17,'hide',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._Content_23_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_23,'statusbar-padding',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_16:any = this._Icon_52_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_52,'hide',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_18:any = this._Icon_57_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_57,'hide',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_20:any = this._Icon_62_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_62,'hide',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_22:any = this._Icon_73_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_73,'hide',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_24:any = this._Icon_78_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_78,'hide',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = this._Icon_83_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_83,'hide',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_28:any = this._Icon_88_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_88,'hide',currVal_28);
      this._expr_28 = currVal_28;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Icon_17_3.context.ngOnDestroy();
    this._Icon_52_3.context.ngOnDestroy();
    this._Icon_57_3.context.ngOnDestroy();
    this._Icon_62_3.context.ngOnDestroy();
    this._Icon_73_3.context.ngOnDestroy();
    this._Icon_78_3.context.ngOnDestroy();
    this._Icon_83_3.context.ngOnDestroy();
    this._Icon_88_3.context.ngOnDestroy();
    this._Content_23_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_AboutPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AboutPage> {
  if ((renderType_AboutPage === (null as any))) { (renderType_AboutPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_AboutPage,{})); }
  return new _View_AboutPage0(viewUtils,parentInjector,declarationEl);
}
class _View_AboutPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import23.Wrapper_Item;
  _ItemContent_0_5:import23.Wrapper_ItemContent;
  _query_Label_0_0:import16.QueryList<any>;
  _query_Button_0_1:import16.QueryList<any>;
  _query_Icon_0_2:import16.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AboutPage1,renderType_AboutPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import23.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import23.Wrapper_Item(this.parent.parentInjector.get(import36.Form),this.parent.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import23.Wrapper_ItemContent();
    this._query_Label_0_0 = new import16.QueryList<any>();
    this._query_Button_0_1 = new import16.QueryList<any>();
    this._query_Icon_0_2 = new import16.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'span',(null as any));
    this.renderer.setElementAttribute(this._el_5,'light-dark','');
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4,
        this._el_5,
        this._text_7
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Item_0_4.context; }
    if (((token === import46.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.context.$implicit.hours,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_6,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AboutPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AboutPage1(viewUtils,parentInjector,declarationEl);
}