/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './setting';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/menu/menu-toggle.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar-item.ngfactory';
import * as import16 from '@angular/core/src/linker/query_list';
import * as import17 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/typography/typography.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/list/list.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/toggle/toggle.ngfactory';
import * as import26 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import27 from 'ionic-angular/config/config';
import * as import28 from '@angular/core/src/linker/element_ref';
import * as import29 from 'ionic-angular/navigation/view-controller';
import * as import30 from 'ionic-angular/components/app/app';
import * as import31 from 'ionic-angular/components/menu/menu-controller';
import * as import32 from 'ionic-angular/components/toolbar/toolbar';
import * as import33 from 'ionic-angular/util/keyboard';
import * as import34 from '@angular/core/src/zone/ng_zone';
import * as import35 from 'ionic-angular/components/tabs/tabs';
import * as import36 from 'ionic-angular/gestures/gesture-controller';
import * as import37 from 'ionic-angular/util/form';
import * as import38 from 'ionic-angular/util/haptic';
import * as import39 from 'ionic-angular/platform/platform';
import * as import40 from '@angular/forms/src/directives/ng_control';
import * as import41 from 'ionic-angular/components/icon/icon';
import * as import42 from 'ionic-angular/components/button/button';
import * as import43 from 'ionic-angular/components/menu/menu-toggle';
import * as import44 from 'ionic-angular/components/toolbar/toolbar-item';
import * as import45 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import46 from 'ionic-angular/components/navbar/navbar';
import * as import47 from 'ionic-angular/components/grid/grid';
import * as import48 from 'ionic-angular/components/typography/typography';
import * as import49 from 'ionic-angular/components/label/label';
import * as import50 from 'ionic-angular/components/toggle/toggle';
import * as import51 from '@angular/forms/src/directives/control_value_accessor';
import * as import52 from 'ionic-angular/components/item/item';
import * as import53 from 'ionic-angular/components/input/input';
import * as import54 from 'ionic-angular/components/list/list';
import * as import55 from 'ionic-angular/components/content/content';
export class Wrapper_SettingPage {
  context:import0.SettingPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.SettingPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SettingPage_Host:import2.RenderComponentType = (null as any);
class _View_SettingPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SettingPage_0_4:Wrapper_SettingPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SettingPage_Host0,renderType_SettingPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-setting',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SettingPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SettingPage_0_4 = new Wrapper_SettingPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._SettingPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SettingPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SettingPage) && (0 === requestNodeIndex))) { return this._SettingPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SettingPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SettingPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SettingPage_Host === (null as any))) { (renderType_SettingPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SettingPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SettingPageNgFactory:import10.ComponentFactory<import0.SettingPage> = new import10.ComponentFactory<import0.SettingPage>('page-setting',viewFactory_SettingPage_Host0,import0.SettingPage);
const styles_SettingPage:any[] = ([] as any[]);
var renderType_SettingPage:import2.RenderComponentType = (null as any);
class _View_SettingPage0 extends import1.AppView<import0.SettingPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import12.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _Button_5_4:import13.Wrapper_Button;
  _MenuToggle_5_5:import14.Wrapper_MenuToggle;
  _ToolbarItem_5_6:import15.Wrapper_ToolbarItem;
  _query_Button_5_0:import16.QueryList<any>;
  _text_6:any;
  _el_7:any;
  _Icon_7_3:import17.Wrapper_Icon;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _ToolbarTitle_10_4:import18.Wrapper_ToolbarTitle;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Content_15_4:import19.Wrapper_Content;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _Grid_20_3:import20.Wrapper_Grid;
  _text_21:any;
  _el_22:any;
  _Row_22_3:import20.Wrapper_Row;
  _text_23:any;
  _el_24:any;
  _Col_24_3:import20.Wrapper_Col;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _Col_29_3:import20.Wrapper_Col;
  _text_30:any;
  _el_31:any;
  _Typography_31_3:import21.Wrapper_Typography;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _List_39_3:import22.Wrapper_List;
  _text_40:any;
  _el_41:any;
  /*private*/ _appEl_41:import3.AppElement;
  _Item_41_4:import23.Wrapper_Item;
  _ItemContent_41_5:import23.Wrapper_ItemContent;
  _query_Label_41_0:import16.QueryList<any>;
  _query_Button_41_1:import16.QueryList<any>;
  _query_Icon_41_2:import16.QueryList<any>;
  _text_42:any;
  _el_43:any;
  _Label_43_3:import24.Wrapper_Label;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _Toggle_46_4:import25.Wrapper_Toggle;
  __NG_VALUE_ACCESSOR_46_5:any[];
  _text_47:any;
  _text_48:any;
  _el_49:any;
  /*private*/ _appEl_49:import3.AppElement;
  _Item_49_4:import23.Wrapper_Item;
  _ItemContent_49_5:import23.Wrapper_ItemContent;
  _query_Label_49_0:import16.QueryList<any>;
  _query_Button_49_1:import16.QueryList<any>;
  _query_Icon_49_2:import16.QueryList<any>;
  _text_50:any;
  _el_51:any;
  _Label_51_3:import24.Wrapper_Label;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  /*private*/ _appEl_54:import3.AppElement;
  _TextInput_54_4:import26.Wrapper_TextInput;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  /*private*/ _appEl_57:import3.AppElement;
  _Item_57_4:import23.Wrapper_Item;
  _ItemContent_57_5:import23.Wrapper_ItemContent;
  _query_Label_57_0:import16.QueryList<any>;
  _query_Button_57_1:import16.QueryList<any>;
  _query_Icon_57_2:import16.QueryList<any>;
  _text_58:any;
  _el_59:any;
  _Label_59_3:import24.Wrapper_Label;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import3.AppElement;
  _TextInput_62_4:import26.Wrapper_TextInput;
  _text_63:any;
  _text_64:any;
  _el_65:any;
  /*private*/ _appEl_65:import3.AppElement;
  _Item_65_4:import23.Wrapper_Item;
  _ItemContent_65_5:import23.Wrapper_ItemContent;
  _query_Label_65_0:import16.QueryList<any>;
  _query_Button_65_1:import16.QueryList<any>;
  _query_Icon_65_2:import16.QueryList<any>;
  _text_66:any;
  _el_67:any;
  _Label_67_3:import24.Wrapper_Label;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  /*private*/ _appEl_70:import3.AppElement;
  _TextInput_70_4:import26.Wrapper_TextInput;
  _text_71:any;
  _text_72:any;
  _el_73:any;
  /*private*/ _appEl_73:import3.AppElement;
  _Item_73_4:import23.Wrapper_Item;
  _ItemContent_73_5:import23.Wrapper_ItemContent;
  _query_Label_73_0:import16.QueryList<any>;
  _query_Button_73_1:import16.QueryList<any>;
  _query_Icon_73_2:import16.QueryList<any>;
  _text_74:any;
  _el_75:any;
  _Label_75_3:import24.Wrapper_Label;
  _text_76:any;
  _text_77:any;
  _el_78:any;
  /*private*/ _appEl_78:import3.AppElement;
  _TextInput_78_4:import26.Wrapper_TextInput;
  _text_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _text_83:any;
  _el_84:any;
  _Footer_84_3:import11.Wrapper_Footer;
  _text_85:any;
  _el_86:any;
  _Grid_86_3:import20.Wrapper_Grid;
  _text_87:any;
  _el_88:any;
  _Row_88_3:import20.Wrapper_Row;
  _text_89:any;
  _el_90:any;
  _Col_90_3:import20.Wrapper_Col;
  _text_91:any;
  _el_92:any;
  /*private*/ _appEl_92:import3.AppElement;
  _Button_92_4:import13.Wrapper_Button;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _el_96:any;
  _Col_96_3:import20.Wrapper_Col;
  _text_97:any;
  _el_98:any;
  /*private*/ _appEl_98:import3.AppElement;
  _Button_98_4:import13.Wrapper_Button;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  _text_104:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_12:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SettingPage0,renderType_SettingPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  get _NG_VALUE_ACCESSOR_46_5():any[] {
    if ((this.__NG_VALUE_ACCESSOR_46_5 == (null as any))) { (this.__NG_VALUE_ACCESSOR_46_5 = [this._Toggle_46_4.context]); }
    return this.__NG_VALUE_ACCESSOR_46_5;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import30.App),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_5,'ion-button','');
    this.renderer.setElementAttribute(this._el_5,'menuToggle','');
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import13.viewFactory_Button0(this.viewUtils,this.injector(5),this._appEl_5);
    this._Button_5_4 = new import13.Wrapper_Button('','',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_5),this.renderer);
    this._MenuToggle_5_5 = new import14.Wrapper_MenuToggle(this.parentInjector.get(import31.MenuController),new import28.ElementRef(this._el_5),this.parentInjector.get(import29.ViewController,(null as any)),this._Navbar_3_4.context);
    this._ToolbarItem_5_6 = new import15.Wrapper_ToolbarItem(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._query_Button_5_0 = new import16.QueryList<any>();
    this._appEl_5.initComponent(this._Button_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_7 = this.renderer.createElement((null as any),'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_7,'name','menu');
    this.renderer.setElementAttribute(this._el_7,'role','img');
    this._Icon_7_3 = new import17.Wrapper_Icon(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_7),this.renderer);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_5.create(this._Button_5_4.context,[([] as any[]).concat([
        this._text_6,
        this._el_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_10 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_10 = new import3.AppElement(10,3,this,this._el_10);
    var compView_10:any = import18.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(10),this._appEl_10);
    this._ToolbarTitle_10_4 = new import18.Wrapper_ToolbarTitle(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_10.initComponent(this._ToolbarTitle_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'Setting',(null as any));
    compView_10.create(this._ToolbarTitle_10_4.context,[([] as any[]).concat([this._text_11])],(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]).concat([this._el_5]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._text_9,
        this._el_10,
        this._text_12
      ]
      )
    ]
    ,(null as any));
    this._text_13 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_15 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this._appEl_15 = new import3.AppElement(15,(null as any),this,this._el_15);
    var compView_15:any = import19.viewFactory_Content0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Content_15_4 = new import19.Wrapper_Content(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_15),this.renderer,this.parentInjector.get(import30.App),this.parentInjector.get(import33.Keyboard),this.parentInjector.get(import34.NgZone),this.parentInjector.get(import29.ViewController,(null as any)),this.parentInjector.get(import35.Tabs,(null as any)));
    this._appEl_15.initComponent(this._Content_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._text_17 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','profile-cover');
    this._text_19 = this.renderer.createText(this._el_18,'\n    ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-grid',(null as any));
    this._Grid_20_3 = new import20.Wrapper_Grid();
    this._text_21 = this.renderer.createText(this._el_20,'\n      ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-row',(null as any));
    this._Row_22_3 = new import20.Wrapper_Row();
    this._text_23 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_24,'text-center','');
    this.renderer.setElementAttribute(this._el_24,'width-33','');
    this._Col_24_3 = new import20.Wrapper_Col();
    this._text_25 = this.renderer.createText(this._el_24,'\n          ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'img',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','profile-picture circle');
    this.renderer.setElementAttribute(this._el_26,'src','assets/img/people/max.png');
    this._text_27 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._text_28 = this.renderer.createText(this._el_22,'\n        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_29,'width-66','');
    this._Col_29_3 = new import20.Wrapper_Col();
    this._text_30 = this.renderer.createText(this._el_29,'\n          ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'h4',(null as any));
    this.renderer.setElementAttribute(this._el_31,'color','light');
    this.renderer.setElementAttribute(this._el_31,'no-margin','');
    this.renderer.setElementAttribute(this._el_31,'padding','');
    this._Typography_31_3 = new import21.Wrapper_Typography(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_31),this.renderer);
    this._text_32 = this.renderer.createText(this._el_31,'Adam Lambert',(null as any));
    this._text_33 = this.renderer.createText(this._el_29,'\n\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._text_35 = this.renderer.createText(this._el_20,'\n    ',(null as any));
    this._text_36 = this.renderer.createText(this._el_18,'\n  ',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n\n  ',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'ion-list',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','list-full-border');
    this._List_39_3 = new import22.Wrapper_List(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_39),this.renderer,this.parentInjector.get(import36.GestureController));
    this._text_40 = this.renderer.createText(this._el_39,'\n\n    ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','item item-block');
    this._appEl_41 = new import3.AppElement(41,39,this,this._el_41);
    var compView_41:any = import23.viewFactory_Item0(this.viewUtils,this.injector(41),this._appEl_41);
    this._Item_41_4 = new import23.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_41),this.renderer);
    this._ItemContent_41_5 = new import23.Wrapper_ItemContent();
    this._query_Label_41_0 = new import16.QueryList<any>();
    this._query_Button_41_1 = new import16.QueryList<any>();
    this._query_Icon_41_2 = new import16.QueryList<any>();
    this._appEl_41.initComponent(this._Item_41_4.context,([] as any[]),compView_41);
    this._text_42 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_43 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_43,'color','primary');
    this._Label_43_3 = new import24.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_43),this.renderer,(null as any),(null as any),(null as any),(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Notification',(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_46 = this.renderer.createElement((null as any),'ion-toggle',(null as any));
    this.renderer.setElementAttribute(this._el_46,'checked','false');
    this._appEl_46 = new import3.AppElement(46,41,this,this._el_46);
    var compView_46:any = import25.viewFactory_Toggle0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Toggle_46_4 = new import25.Wrapper_Toggle(this.parentInjector.get(import37.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_46),this.renderer,this.parentInjector.get(import38.Haptic),this._Item_41_4.context);
    this._appEl_46.initComponent(this._Toggle_46_4.context,([] as any[]),compView_46);
    compView_46.create(this._Toggle_46_4.context,([] as any[]),(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_41_0.reset([this._Label_43_3.context]);
    this._Item_41_4.context.contentLabel = this._query_Label_41_0.first;
    compView_41.create(this._Item_41_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_43]),
      ([] as any[]).concat([
        this._text_42,
        this._text_45,
        this._text_47
      ]
      ),
      ([] as any[]),
      ([] as any[]).concat([this._el_46])
    ]
    ,(null as any));
    this._text_48 = this.renderer.createText(this._el_39,'\n\n    ',(null as any));
    this._el_49 = this.renderer.createElement(this._el_39,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_49,'class','item item-block');
    this._appEl_49 = new import3.AppElement(49,39,this,this._el_49);
    var compView_49:any = import23.viewFactory_Item0(this.viewUtils,this.injector(49),this._appEl_49);
    this._Item_49_4 = new import23.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_49),this.renderer);
    this._ItemContent_49_5 = new import23.Wrapper_ItemContent();
    this._query_Label_49_0 = new import16.QueryList<any>();
    this._query_Button_49_1 = new import16.QueryList<any>();
    this._query_Icon_49_2 = new import16.QueryList<any>();
    this._appEl_49.initComponent(this._Item_49_4.context,([] as any[]),compView_49);
    this._text_50 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_51 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_51,'color','primary');
    this.renderer.setElementAttribute(this._el_51,'stacked','');
    this._Label_51_3 = new import24.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_51),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'Credit card #No',(null as any));
    this._text_53 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_54 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_54,'type','text');
    this.renderer.setElementAttribute(this._el_54,'value','XXXX XXXX XXXX 4678');
    this._appEl_54 = new import3.AppElement(54,49,this,this._el_54);
    var compView_54:any = import26.viewFactory_TextInput0(this.viewUtils,this.injector(54),this._appEl_54);
    this._TextInput_54_4 = new import26.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import37.Form),this._Item_49_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import39.Platform),new import28.ElementRef(this._el_54),this.renderer,this._Content_15_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import40.NgControl,(null as any)));
    this._appEl_54.initComponent(this._TextInput_54_4.context,([] as any[]),compView_54);
    compView_54.create(this._TextInput_54_4.context,([] as any[]),(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_49_0.reset([this._Label_51_3.context]);
    this._Item_49_4.context.contentLabel = this._query_Label_49_0.first;
    compView_49.create(this._Item_49_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_51]),
      ([] as any[]).concat([
        this._text_50,
        this._text_53,
        this._text_55
      ]
      ),
      ([] as any[]).concat([this._el_54]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_56 = this.renderer.createText(this._el_39,'\n\n    ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_39,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','item item-block');
    this._appEl_57 = new import3.AppElement(57,39,this,this._el_57);
    var compView_57:any = import23.viewFactory_Item0(this.viewUtils,this.injector(57),this._appEl_57);
    this._Item_57_4 = new import23.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_57),this.renderer);
    this._ItemContent_57_5 = new import23.Wrapper_ItemContent();
    this._query_Label_57_0 = new import16.QueryList<any>();
    this._query_Button_57_1 = new import16.QueryList<any>();
    this._query_Icon_57_2 = new import16.QueryList<any>();
    this._appEl_57.initComponent(this._Item_57_4.context,([] as any[]),compView_57);
    this._text_58 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_59 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_59,'color','primary');
    this.renderer.setElementAttribute(this._el_59,'stacked','');
    this._Label_59_3 = new import24.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_59),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'Expires',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_62,'type','text');
    this.renderer.setElementAttribute(this._el_62,'value','08/16');
    this._appEl_62 = new import3.AppElement(62,57,this,this._el_62);
    var compView_62:any = import26.viewFactory_TextInput0(this.viewUtils,this.injector(62),this._appEl_62);
    this._TextInput_62_4 = new import26.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import37.Form),this._Item_57_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import39.Platform),new import28.ElementRef(this._el_62),this.renderer,this._Content_15_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import40.NgControl,(null as any)));
    this._appEl_62.initComponent(this._TextInput_62_4.context,([] as any[]),compView_62);
    compView_62.create(this._TextInput_62_4.context,([] as any[]),(null as any));
    this._text_63 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_57_0.reset([this._Label_59_3.context]);
    this._Item_57_4.context.contentLabel = this._query_Label_57_0.first;
    compView_57.create(this._Item_57_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_59]),
      ([] as any[]).concat([
        this._text_58,
        this._text_61,
        this._text_63
      ]
      ),
      ([] as any[]).concat([this._el_62]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_64 = this.renderer.createText(this._el_39,'\n\n    ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_39,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_65,'class','item item-block');
    this._appEl_65 = new import3.AppElement(65,39,this,this._el_65);
    var compView_65:any = import23.viewFactory_Item0(this.viewUtils,this.injector(65),this._appEl_65);
    this._Item_65_4 = new import23.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_65),this.renderer);
    this._ItemContent_65_5 = new import23.Wrapper_ItemContent();
    this._query_Label_65_0 = new import16.QueryList<any>();
    this._query_Button_65_1 = new import16.QueryList<any>();
    this._query_Icon_65_2 = new import16.QueryList<any>();
    this._appEl_65.initComponent(this._Item_65_4.context,([] as any[]),compView_65);
    this._text_66 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_67 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_67,'color','primary');
    this.renderer.setElementAttribute(this._el_67,'stacked','');
    this._Label_67_3 = new import24.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_67),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_68 = this.renderer.createText(this._el_67,'CVV-Code',(null as any));
    this._text_69 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_70 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_70,'type','text');
    this.renderer.setElementAttribute(this._el_70,'value','3013');
    this._appEl_70 = new import3.AppElement(70,65,this,this._el_70);
    var compView_70:any = import26.viewFactory_TextInput0(this.viewUtils,this.injector(70),this._appEl_70);
    this._TextInput_70_4 = new import26.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import37.Form),this._Item_65_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import39.Platform),new import28.ElementRef(this._el_70),this.renderer,this._Content_15_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import40.NgControl,(null as any)));
    this._appEl_70.initComponent(this._TextInput_70_4.context,([] as any[]),compView_70);
    compView_70.create(this._TextInput_70_4.context,([] as any[]),(null as any));
    this._text_71 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_65_0.reset([this._Label_67_3.context]);
    this._Item_65_4.context.contentLabel = this._query_Label_65_0.first;
    compView_65.create(this._Item_65_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_67]),
      ([] as any[]).concat([
        this._text_66,
        this._text_69,
        this._text_71
      ]
      ),
      ([] as any[]).concat([this._el_70]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_72 = this.renderer.createText(this._el_39,'\n\n    ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_39,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','item item-block');
    this._appEl_73 = new import3.AppElement(73,39,this,this._el_73);
    var compView_73:any = import23.viewFactory_Item0(this.viewUtils,this.injector(73),this._appEl_73);
    this._Item_73_4 = new import23.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_73),this.renderer);
    this._ItemContent_73_5 = new import23.Wrapper_ItemContent();
    this._query_Label_73_0 = new import16.QueryList<any>();
    this._query_Button_73_1 = new import16.QueryList<any>();
    this._query_Icon_73_2 = new import16.QueryList<any>();
    this._appEl_73.initComponent(this._Item_73_4.context,([] as any[]),compView_73);
    this._text_74 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_75 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_75,'color','primary');
    this.renderer.setElementAttribute(this._el_75,'stacked','');
    this._Label_75_3 = new import24.Wrapper_Label(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_75),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_76 = this.renderer.createText(this._el_75,'Address',(null as any));
    this._text_77 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._el_78 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_78,'type','text');
    this.renderer.setElementAttribute(this._el_78,'value','St Luiz, Barcelona');
    this._appEl_78 = new import3.AppElement(78,73,this,this._el_78);
    var compView_78:any = import26.viewFactory_TextInput0(this.viewUtils,this.injector(78),this._appEl_78);
    this._TextInput_78_4 = new import26.Wrapper_TextInput(this.parentInjector.get(import27.Config),this.parentInjector.get(import37.Form),this._Item_73_4.context,this.parentInjector.get(import30.App),this.parentInjector.get(import39.Platform),new import28.ElementRef(this._el_78),this.renderer,this._Content_15_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import40.NgControl,(null as any)));
    this._appEl_78.initComponent(this._TextInput_78_4.context,([] as any[]),compView_78);
    compView_78.create(this._TextInput_78_4.context,([] as any[]),(null as any));
    this._text_79 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._query_Label_73_0.reset([this._Label_75_3.context]);
    this._Item_73_4.context.contentLabel = this._query_Label_73_0.first;
    compView_73.create(this._Item_73_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_75]),
      ([] as any[]).concat([
        this._text_74,
        this._text_77,
        this._text_79
      ]
      ),
      ([] as any[]).concat([this._el_78]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_80 = this.renderer.createText(this._el_39,'\n\n  ',(null as any));
    this._text_81 = this.renderer.createText((null as any),'\n',(null as any));
    compView_15.create(this._Content_15_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_16,
        this._text_17,
        this._el_18,
        this._text_37,
        this._text_38,
        this._el_39,
        this._text_81
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_82 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._text_83 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_84 = this.renderer.createElement(parentRenderNode,'ion-footer',(null as any));
    this._Footer_84_3 = new import11.Wrapper_Footer(this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_84),this.renderer,this.parentInjector.get(import29.ViewController,(null as any)));
    this._text_85 = this.renderer.createText(this._el_84,'\n  ',(null as any));
    this._el_86 = this.renderer.createElement(this._el_84,'ion-grid',(null as any));
    this.renderer.setElementAttribute(this._el_86,'no-padding','');
    this._Grid_86_3 = new import20.Wrapper_Grid();
    this._text_87 = this.renderer.createText(this._el_86,'\n    ',(null as any));
    this._el_88 = this.renderer.createElement(this._el_86,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_88,'class','item-button-group');
    this.renderer.setElementAttribute(this._el_88,'no-padding','');
    this._Row_88_3 = new import20.Wrapper_Row();
    this._text_89 = this.renderer.createText(this._el_88,'\n      ',(null as any));
    this._el_90 = this.renderer.createElement(this._el_88,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_90,'no-padding','');
    this._Col_90_3 = new import20.Wrapper_Col();
    this._text_91 = this.renderer.createText(this._el_90,'\n        ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_90,'button',(null as any));
    this.renderer.setElementAttribute(this._el_92,'block','');
    this.renderer.setElementAttribute(this._el_92,'color','gray');
    this.renderer.setElementAttribute(this._el_92,'ion-button','');
    this._appEl_92 = new import3.AppElement(92,90,this,this._el_92);
    var compView_92:any = import13.viewFactory_Button0(this.viewUtils,this.injector(92),this._appEl_92);
    this._Button_92_4 = new import13.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_92),this.renderer);
    this._appEl_92.initComponent(this._Button_92_4.context,([] as any[]),compView_92);
    this._text_93 = this.renderer.createText((null as any),'\n          Cancel\n        ',(null as any));
    compView_92.create(this._Button_92_4.context,[([] as any[]).concat([this._text_93])],(null as any));
    this._text_94 = this.renderer.createText(this._el_90,'\n      ',(null as any));
    this._text_95 = this.renderer.createText(this._el_88,'\n      ',(null as any));
    this._el_96 = this.renderer.createElement(this._el_88,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_96,'no-padding','');
    this._Col_96_3 = new import20.Wrapper_Col();
    this._text_97 = this.renderer.createText(this._el_96,'\n        ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_96,'button',(null as any));
    this.renderer.setElementAttribute(this._el_98,'block','');
    this.renderer.setElementAttribute(this._el_98,'ion-button','');
    this._appEl_98 = new import3.AppElement(98,96,this,this._el_98);
    var compView_98:any = import13.viewFactory_Button0(this.viewUtils,this.injector(98),this._appEl_98);
    this._Button_98_4 = new import13.Wrapper_Button((null as any),'',this.parentInjector.get(import27.Config),new import28.ElementRef(this._el_98),this.renderer);
    this._appEl_98.initComponent(this._Button_98_4.context,([] as any[]),compView_98);
    this._text_99 = this.renderer.createText((null as any),'\n          Save\n        ',(null as any));
    compView_98.create(this._Button_98_4.context,[([] as any[]).concat([this._text_99])],(null as any));
    this._text_100 = this.renderer.createText(this._el_96,'\n      ',(null as any));
    this._text_101 = this.renderer.createText(this._el_88,'\n    ',(null as any));
    this._text_102 = this.renderer.createText(this._el_86,'\n  ',(null as any));
    this._text_103 = this.renderer.createText(this._el_84,'\n',(null as any));
    this._text_104 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._text_77,
      this._el_78,
      this._text_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._el_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._text_102,
      this._text_103,
      this._text_104
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Icon) && (7 === requestNodeIndex))) { return this._Icon_7_3.context; }
    if (((token === import42.Button) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Button_5_4.context; }
    if (((token === import43.MenuToggle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._MenuToggle_5_5.context; }
    if (((token === import44.ToolbarItem) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._ToolbarItem_5_6.context; }
    if (((token === import45.ToolbarTitle) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ToolbarTitle_10_4.context; }
    if (((token === import46.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._Navbar_3_4.context; }
    if (((token === import32.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 13)))) { return this._Header_1_3.context; }
    if (((token === import47.Col) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Col_24_3.context; }
    if (((token === import48.Typography) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Typography_31_3.context; }
    if (((token === import47.Col) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 33)))) { return this._Col_29_3.context; }
    if (((token === import47.Row) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Row_22_3.context; }
    if (((token === import47.Grid) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._Grid_20_3.context; }
    if (((token === import49.Label) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Label_43_3.context; }
    if (((token === import50.Toggle) && (46 === requestNodeIndex))) { return this._Toggle_46_4.context; }
    if (((token === import51.NG_VALUE_ACCESSOR) && (46 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_46_5; }
    if (((token === import52.Item) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Item_41_4.context; }
    if (((token === import52.ItemContent) && ((41 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._ItemContent_41_5.context; }
    if (((token === import49.Label) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._Label_51_3.context; }
    if (((token === import53.TextInput) && (54 === requestNodeIndex))) { return this._TextInput_54_4.context; }
    if (((token === import52.Item) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._Item_49_4.context; }
    if (((token === import52.ItemContent) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 55)))) { return this._ItemContent_49_5.context; }
    if (((token === import49.Label) && ((59 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._Label_59_3.context; }
    if (((token === import53.TextInput) && (62 === requestNodeIndex))) { return this._TextInput_62_4.context; }
    if (((token === import52.Item) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Item_57_4.context; }
    if (((token === import52.ItemContent) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._ItemContent_57_5.context; }
    if (((token === import49.Label) && ((67 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Label_67_3.context; }
    if (((token === import53.TextInput) && (70 === requestNodeIndex))) { return this._TextInput_70_4.context; }
    if (((token === import52.Item) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._Item_65_4.context; }
    if (((token === import52.ItemContent) && ((65 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._ItemContent_65_5.context; }
    if (((token === import49.Label) && ((75 <= requestNodeIndex) && (requestNodeIndex <= 76)))) { return this._Label_75_3.context; }
    if (((token === import53.TextInput) && (78 === requestNodeIndex))) { return this._TextInput_78_4.context; }
    if (((token === import52.Item) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._Item_73_4.context; }
    if (((token === import52.ItemContent) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 79)))) { return this._ItemContent_73_5.context; }
    if (((token === import54.List) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 80)))) { return this._List_39_3.context; }
    if (((token === import55.Content) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 81)))) { return this._Content_15_4.context; }
    if (((token === import42.Button) && ((92 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._Button_92_4.context; }
    if (((token === import47.Col) && ((90 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._Col_90_3.context; }
    if (((token === import42.Button) && ((98 <= requestNodeIndex) && (requestNodeIndex <= 99)))) { return this._Button_98_4.context; }
    if (((token === import47.Col) && ((96 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._Col_96_3.context; }
    if (((token === import47.Row) && ((88 <= requestNodeIndex) && (requestNodeIndex <= 101)))) { return this._Row_88_3.context; }
    if (((token === import47.Grid) && ((86 <= requestNodeIndex) && (requestNodeIndex <= 102)))) { return this._Grid_86_3.context; }
    if (((token === import32.Footer) && ((84 <= requestNodeIndex) && (requestNodeIndex <= 103)))) { return this._Footer_84_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._Button_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    const currVal_4:any = '';
    this._MenuToggle_5_5.check_menuToggle(currVal_4,throwOnChange,false);
    this._MenuToggle_5_5.detectChangesInternal(this,this._el_5,throwOnChange);
    this._ToolbarItem_5_6.detectChangesInternal(this,this._el_5,throwOnChange);
    const currVal_6:any = 'menu';
    this._Icon_7_3.check_name(currVal_6,throwOnChange,false);
    this._Icon_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    if (this._ToolbarTitle_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    if (this._Content_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    this._Grid_20_3.detectChangesInternal(this,this._el_20,throwOnChange);
    this._Row_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Col_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Col_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_9:any = 'light';
    this._Typography_31_3.check_color(currVal_9,throwOnChange,false);
    this._Typography_31_3.detectChangesInternal(this,this._el_31,throwOnChange);
    this._List_39_3.detectChangesInternal(this,this._el_39,throwOnChange);
    if (this._Item_41_4.detectChangesInternal(this,this._el_41,throwOnChange)) { this._appEl_41.componentView.markAsCheckOnce(); }
    this._ItemContent_41_5.detectChangesInternal(this,this._el_41,throwOnChange);
    const currVal_10:any = 'primary';
    this._Label_43_3.check_color(currVal_10,throwOnChange,false);
    this._Label_43_3.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_11:any = 'false';
    this._Toggle_46_4.check_checked(currVal_11,throwOnChange,false);
    this._Toggle_46_4.detectChangesInternal(this,this._el_46,throwOnChange);
    if (this._Item_49_4.detectChangesInternal(this,this._el_49,throwOnChange)) { this._appEl_49.componentView.markAsCheckOnce(); }
    this._ItemContent_49_5.detectChangesInternal(this,this._el_49,throwOnChange);
    const currVal_13:any = 'primary';
    this._Label_51_3.check_color(currVal_13,throwOnChange,false);
    this._Label_51_3.detectChangesInternal(this,this._el_51,throwOnChange);
    const currVal_14:any = 'XXXX XXXX XXXX 4678';
    this._TextInput_54_4.check_value(currVal_14,throwOnChange,false);
    const currVal_15:any = 'text';
    this._TextInput_54_4.check_type(currVal_15,throwOnChange,false);
    this._TextInput_54_4.detectChangesInternal(this,this._el_54,throwOnChange);
    if (this._Item_57_4.detectChangesInternal(this,this._el_57,throwOnChange)) { this._appEl_57.componentView.markAsCheckOnce(); }
    this._ItemContent_57_5.detectChangesInternal(this,this._el_57,throwOnChange);
    const currVal_16:any = 'primary';
    this._Label_59_3.check_color(currVal_16,throwOnChange,false);
    this._Label_59_3.detectChangesInternal(this,this._el_59,throwOnChange);
    const currVal_17:any = '08/16';
    this._TextInput_62_4.check_value(currVal_17,throwOnChange,false);
    const currVal_18:any = 'text';
    this._TextInput_62_4.check_type(currVal_18,throwOnChange,false);
    this._TextInput_62_4.detectChangesInternal(this,this._el_62,throwOnChange);
    if (this._Item_65_4.detectChangesInternal(this,this._el_65,throwOnChange)) { this._appEl_65.componentView.markAsCheckOnce(); }
    this._ItemContent_65_5.detectChangesInternal(this,this._el_65,throwOnChange);
    const currVal_19:any = 'primary';
    this._Label_67_3.check_color(currVal_19,throwOnChange,false);
    this._Label_67_3.detectChangesInternal(this,this._el_67,throwOnChange);
    const currVal_20:any = '3013';
    this._TextInput_70_4.check_value(currVal_20,throwOnChange,false);
    const currVal_21:any = 'text';
    this._TextInput_70_4.check_type(currVal_21,throwOnChange,false);
    this._TextInput_70_4.detectChangesInternal(this,this._el_70,throwOnChange);
    if (this._Item_73_4.detectChangesInternal(this,this._el_73,throwOnChange)) { this._appEl_73.componentView.markAsCheckOnce(); }
    this._ItemContent_73_5.detectChangesInternal(this,this._el_73,throwOnChange);
    const currVal_22:any = 'primary';
    this._Label_75_3.check_color(currVal_22,throwOnChange,false);
    this._Label_75_3.detectChangesInternal(this,this._el_75,throwOnChange);
    const currVal_23:any = 'St Luiz, Barcelona';
    this._TextInput_78_4.check_value(currVal_23,throwOnChange,false);
    const currVal_24:any = 'text';
    this._TextInput_78_4.check_type(currVal_24,throwOnChange,false);
    this._TextInput_78_4.detectChangesInternal(this,this._el_78,throwOnChange);
    this._Footer_84_3.detectChangesInternal(this,this._el_84,throwOnChange);
    this._Grid_86_3.detectChangesInternal(this,this._el_86,throwOnChange);
    this._Row_88_3.detectChangesInternal(this,this._el_88,throwOnChange);
    this._Col_90_3.detectChangesInternal(this,this._el_90,throwOnChange);
    const currVal_25:any = '';
    this._Button_92_4.check_block(currVal_25,throwOnChange,false);
    const currVal_26:any = 'gray';
    this._Button_92_4.check_color(currVal_26,throwOnChange,false);
    if (this._Button_92_4.detectChangesInternal(this,this._el_92,throwOnChange)) { this._appEl_92.componentView.markAsCheckOnce(); }
    this._Col_96_3.detectChangesInternal(this,this._el_96,throwOnChange);
    const currVal_27:any = '';
    this._Button_98_4.check_block(currVal_27,throwOnChange,false);
    if (this._Button_98_4.detectChangesInternal(this,this._el_98,throwOnChange)) { this._appEl_98.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_5_0.dirty) {
        this._query_Button_5_0.reset([this._Button_5_4.context]);
        this._ToolbarItem_5_6.context._buttons = this._query_Button_5_0;
        this._query_Button_5_0.notifyOnChanges();
      }
      if (this._query_Button_41_1.dirty) {
        this._query_Button_41_1.reset(([] as any[]));
        this._Item_41_4.context._buttons = this._query_Button_41_1;
        this._query_Button_41_1.notifyOnChanges();
      }
      if (this._query_Icon_41_2.dirty) {
        this._query_Icon_41_2.reset(([] as any[]));
        this._Item_41_4.context._icons = this._query_Icon_41_2;
        this._query_Icon_41_2.notifyOnChanges();
      }
      if (this._query_Button_49_1.dirty) {
        this._query_Button_49_1.reset(([] as any[]));
        this._Item_49_4.context._buttons = this._query_Button_49_1;
        this._query_Button_49_1.notifyOnChanges();
      }
      if (this._query_Icon_49_2.dirty) {
        this._query_Icon_49_2.reset(([] as any[]));
        this._Item_49_4.context._icons = this._query_Icon_49_2;
        this._query_Icon_49_2.notifyOnChanges();
      }
      if (this._query_Button_57_1.dirty) {
        this._query_Button_57_1.reset(([] as any[]));
        this._Item_57_4.context._buttons = this._query_Button_57_1;
        this._query_Button_57_1.notifyOnChanges();
      }
      if (this._query_Icon_57_2.dirty) {
        this._query_Icon_57_2.reset(([] as any[]));
        this._Item_57_4.context._icons = this._query_Icon_57_2;
        this._query_Icon_57_2.notifyOnChanges();
      }
      if (this._query_Button_65_1.dirty) {
        this._query_Button_65_1.reset(([] as any[]));
        this._Item_65_4.context._buttons = this._query_Button_65_1;
        this._query_Button_65_1.notifyOnChanges();
      }
      if (this._query_Icon_65_2.dirty) {
        this._query_Icon_65_2.reset(([] as any[]));
        this._Item_65_4.context._icons = this._query_Icon_65_2;
        this._query_Icon_65_2.notifyOnChanges();
      }
      if (this._query_Button_73_1.dirty) {
        this._query_Button_73_1.reset(([] as any[]));
        this._Item_73_4.context._buttons = this._query_Button_73_1;
        this._query_Button_73_1.notifyOnChanges();
      }
      if (this._query_Icon_73_2.dirty) {
        this._query_Icon_73_2.reset(([] as any[]));
        this._Item_73_4.context._icons = this._query_Icon_73_2;
        this._query_Icon_73_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Button_5_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Toggle_46_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_41_4.context.ngAfterContentInit(); }
      this._TextInput_54_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_49_4.context.ngAfterContentInit(); }
      this._TextInput_62_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_57_4.context.ngAfterContentInit(); }
      this._TextInput_70_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_65_4.context.ngAfterContentInit(); }
      this._TextInput_78_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_73_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_92_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_98_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._MenuToggle_5_5.context.isHidden;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_5,'hidden',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_7:any = this._Icon_7_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_7,'hide',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._Content_15_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_15,'statusbar-padding',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_12:any = this._Toggle_46_4.context._disabled;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_46,'toggle-disabled',currVal_12);
      this._expr_12 = currVal_12;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_7_3.context.ngOnDestroy();
    this._Toggle_46_4.context.ngOnDestroy();
    this._TextInput_54_4.context.ngOnDestroy();
    this._TextInput_62_4.context.ngOnDestroy();
    this._TextInput_70_4.context.ngOnDestroy();
    this._TextInput_78_4.context.ngOnDestroy();
    this._Content_15_4.context.ngOnDestroy();
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._MenuToggle_5_5.context.toggle()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SettingPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SettingPage> {
  if ((renderType_SettingPage === (null as any))) { (renderType_SettingPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_SettingPage,{})); }
  return new _View_SettingPage0(viewUtils,parentInjector,declarationEl);
}